import os
import sys
sys.path.append(os.path.dirname(__file__))
from batch_base import create_100_qnas

# ==============================================================================
# 1. REACT.JS (100 Questions)
# ==============================================================================
react_data = [
    ("Explain the Virtual DOM and React's Reconciliation algorithm?", "Intermediate",
     "The Virtual DOM (VDOM) is an in-memory representation of real DOM elements. React uses an O(n) heuristic diffing algorithm: 1) Elements of different types tear down and recreate the tree, 2) Keys identify stable list items across renders. In React 16+, Reconciliation is executed incrementally via the Fiber architecture.",
     "```jsx\n// Stable keys prevent unnecessary DOM node recreations during diffing\nfunction UserList({ users }) {\n  return (\n    <ul>\n      {users.map(user => (\n        <li key={user.id}>{user.name} ({user.role})</li>\n      ))}\n    </ul>\n  );\n}\n```"),
    
    ("What is React Fiber and how does it enable concurrent rendering?", "Advanced",
     "React Fiber is a rewrite of React core reconciler. It models units of work as a linked list of Fiber nodes with child, sibling, and return pointers. This enables cooperative multitasking: React can pause, resume, prioritize (via Lanes), or abort rendering work across animation frames.",
     "```javascript\n// Fiber node conceptual structure\nconst fiber = {\n  type: 'div',\n  key: null,\n  stateNode: domElement,\n  child: firstChildFiber,\n  sibling: nextSiblingFiber,\n  return: parentFiber,\n  memoizedProps: prevProps,\n  pendingProps: nextProps,\n  lanes: 0b0001000 // Priority lane\n};\n```"),

    ("Difference between `useState` and `useReducer` and when to use each?", "Intermediate",
     "`useState` is suited for independent, simple state. `useReducer` is best when: 1) State logic is complex with multiple transitions, 2) The next state depends on prior state in multiple ways, 3) Passing a stable `dispatch` function down avoids prop-drilling callbacks and prevents child re-renders.",
     "```jsx\nimport React, { useReducer } from 'react';\n\nconst initialState = { count: 0, step: 1 };\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'inc': return { ...state, count: state.count + state.step };\n    case 'setStep': return { ...state, step: action.payload };\n    case 'reset': return initialState;\n    default: return state;\n  }\n}\nexport function Counter() {\n  const [state, dispatch] = useReducer(reducer, initialState);\n  return <button onClick={() => dispatch({ type: 'inc' })}>Count: {state.count}</button>;\n}\n```"),

    ("How does `useEffect` differ from `useLayoutEffect` and `useInsertionEffect`?", "Advanced",
     "- `useInsertionEffect`: Fires synchronously BEFORE any DOM mutations. Used by CSS-in-JS libraries to inject `<style>` tags.\n- `useLayoutEffect`: Fires synchronously AFTER DOM mutations but BEFORE browser repaint. Used to measure layout or mutate DOM without flickering.\n- `useEffect`: Fires asynchronously AFTER browser paint. Used for data fetching, timers, and subscriptions.",
     "```jsx\nimport { useState, useLayoutEffect, useRef } from 'react';\n\nexport function Tooltip({ targetRect }) {\n  const [pos, setPos] = useState({ top: 0, left: 0 });\n  const ref = useRef(null);\n\n  useLayoutEffect(() => {\n    if (ref.current) {\n      const height = ref.current.offsetHeight;\n      setPos({ top: targetRect.top - height - 8, left: targetRect.left });\n    }\n  }, [targetRect]);\n\n  return <div ref={ref} style={{ position: 'fixed', top: pos.top, left: pos.left }}>Tooltip</div>;\n}\n```"),

    ("Explain `useCallback` vs `useMemo`: Rules, cost of memoization, and anti-patterns?", "Intermediate",
     "- `useMemo` caches calculation results; `useCallback` caches function definitions.\n- Anti-pattern: Memoizing trivial calculations or callbacks passed to plain DOM tags. Memoization incurs memory for dependency arrays and comparison overhead. Use only when passing to `React.memo` components, preserving object references for hook dependencies, or heavy calculations.",
     "```jsx\nimport React, { useState, useMemo, useCallback } from 'react';\n\nconst MemoRow = React.memo(({ item, onDelete }) => {\n  return <div>{item.name} <button onClick={() => onDelete(item.id)}>Delete</button></div>;\n});\n\nexport function Table({ items }) {\n  const [search, setSearch] = useState('');\n  const filtered = useMemo(() => items.filter(i => i.name.includes(search)), [items, search]);\n  const handleDelete = useCallback((id) => console.log('Delete', id), []);\n  return <div>{filtered.map(i => <MemoRow key={i.id} item={i} onDelete={handleDelete} />)}</div>;\n}\n```"),

    ("How do you implement a custom `useFetch` hook with caching and AbortController?", "Advanced",
     "A robust `useFetch` cancels in-flight requests via `AbortController` on unmount/URL change to avoid race conditions and uses a cache Map to avoid duplicate requests.",
     "```typescript\nimport { useState, useEffect } from 'react';\n\nconst cache = new Map<string, any>();\nexport function useFetch<T>(url: string) {\n  const [data, setData] = useState<T | null>(cache.get(url) || null);\n  const [loading, setLoading] = useState(!cache.has(url));\n  const [error, setError] = useState<Error | null>(null);\n\n  useEffect(() => {\n    if (!url) return;\n    if (cache.has(url)) { setData(cache.get(url)); setLoading(false); return; }\n    const controller = new AbortController();\n    setLoading(true);\n    fetch(url, { signal: controller.signal })\n      .then(res => res.json())\n      .then(d => { cache.set(url, d); setData(d); setLoading(false); })\n      .catch(err => { if (err.name !== 'AbortError') { setError(err); setLoading(false); } });\n    return () => controller.abort();\n  }, [url]);\n\n  return { data, loading, error };\n}\n```"),

    ("What is `useTransition` and how does it differ from `useDeferredValue`?", "Advanced",
     "`useTransition` wraps a state setter to mark it as low-priority (transition) with an `isPending` indicator. `useDeferredValue` wraps a value itself (props or state) and defers updating it until high-priority work (like typing) finishes.",
     "```jsx\nimport { useState, useTransition } from 'react';\n\nexport function SearchFilter({ list }) {\n  const [input, setInput] = useState('');\n  const [query, setQuery] = useState('');\n  const [isPending, startTransition] = useTransition();\n\n  const onChange = (e) => {\n    setInput(e.target.value); // Urgent\n    startTransition(() => {\n      setQuery(e.target.value); // Transition\n    });\n  };\n\n  return (\n    <div>\n      <input value={input} onChange={onChange} />\n      {isPending && <span>Filtering...</span>}\n      <ItemList query={query} list={list} />\n    </div>\n  );\n}\n```"),

    ("What are React Server Components (RSC) and how do they differ from SSR?", "Advanced",
     "SSR renders static HTML on the server and still delivers the entire component JavaScript bundle for hydration. RSC execute exclusively on the server, streaming a JSON UI format to the client, never adding their dependencies to the browser bundle.",
     "```jsx\n// app/products/page.tsx - Server Component\nimport db from '@/lib/db';\nimport LikeButton from './LikeButton';\n\nexport default async function Products() {\n  const products = await db.query('SELECT * FROM products');\n  return (\n    <div>\n      {products.map(p => (\n        <div key={p.id}>\n          <h3>{p.name}</h3>\n          <LikeButton id={p.id} />\n        </div>\n      ))}\n    </div>\n  );\n}\n```"),

    ("How does Automatic Batching in React 18 work and how do you opt out?", "Intermediate",
     "React 18 batches all state updates across promises, `setTimeout`, native events, and fetch calls into one render. Use `ReactDOM.flushSync` if you need immediate synchronous DOM updates.",
     "```jsx\nimport { useState } from 'react';\nimport { flushSync } from 'react-dom';\n\nexport function BatchDemo() {\n  const [count, setCount] = useState(0);\n  const [flag, setFlag] = useState(false);\n\n  const handleAsync = async () => {\n    await fetch('/api/data');\n    // Automatically batched in React 18\n    setCount(c => c + 1);\n    setFlag(f => !f);\n  };\n\n  const handleForceSync = () => {\n    flushSync(() => setCount(c => c + 1)); // Synchronous commit\n  };\n\n  return <button onClick={handleAsync}>Async Click</button>;\n}\n```"),

    ("How do you implement an Error Boundary with fallback UI in React?", "Intermediate",
     "Error Boundaries are class components using `static getDerivedStateFromError` (to set error state) and `componentDidCatch` (to log errors). They catch rendering, lifecycle, and constructor errors in child subtrees.",
     "```jsx\nimport React, { Component } from 'react';\n\nexport class ErrorBoundary extends Component {\n  state = { hasError: false, error: null };\n  static getDerivedStateFromError(error) { return { hasError: true, error }; }\n  componentDidCatch(err, info) { console.error('Caught:', err, info); }\n  render() {\n    if (this.state.hasError) {\n      return (\n        <div role=\"alert\">\n          <h2>Error encountered</h2>\n          <button onClick={() => this.setState({ hasError: false })}>Retry</button>\n        </div>\n      );\n    }\n    return this.props.children;\n  }\n}\n```")
]

# Build 100 questions for React
react_topics_remaining = [
    ("How do you split Context to avoid unnecessary re-renders?", "Advanced", "Context consumers re-render on any value change. Split state and dispatch into separate contexts to prevent components that only dispatch actions from re-rendering.", "```jsx\nconst StateCtx = createContext();\nconst DispatchCtx = createContext();\nexport function Provider({ children }) {\n  const [state, dispatch] = useReducer(reducer, init);\n  return (\n    <StateCtx.Provider value={state}>\n      <DispatchCtx.Provider value={dispatch}>{children}</DispatchCtx.Provider>\n    </StateCtx.Provider>\n  );\n}\n```"),
    ("How do you implement Compound Components pattern in React?", "Advanced", "Compound components share implicit state via Context, creating clean JSX composition (e.g. `<Tabs>`, `<Tabs.Tab>`).", "```jsx\nconst TabCtx = createContext();\nexport function Tabs({ children, defaultTab }) {\n  const [active, setActive] = useState(defaultTab);\n  return <TabCtx.Provider value={{ active, setActive }}>{children}</TabCtx.Provider>;\n}\nTabs.Tab = ({ id, children }) => {\n  const { active, setActive } = useContext(TabCtx);\n  return <button className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{children}</button>;\n};\n```"),
    ("How do you use `forwardRef` and `useImperativeHandle`?", "Advanced", "Forward DOM references and expose explicit imperative API methods to parents.", "```jsx\nexport const CustomInput = forwardRef((props, ref) => {\n  const inputRef = useRef();\n  useImperativeHandle(ref, () => ({\n    focus: () => inputRef.current.focus(),\n    clear: () => { inputRef.current.value = ''; }\n  }));\n  return <input ref={inputRef} {...props} />;\n});\n```"),
    ("How do you render Portals in React and handle event bubbling?", "Intermediate", "`createPortal` mounts children into an external DOM node while preserving React synthetic event bubbling up the virtual tree.", "```jsx\nimport { createPortal } from 'react-dom';\nexport function Modal({ isOpen, children, onClose }) {\n  if (!isOpen) return null;\n  return createPortal(\n    <div className=\"overlay\" onClick={onClose}>\n      <div className=\"modal\" onClick={e => e.stopPropagation()}>{children}</div>\n    </div>,\n    document.body\n  );\n}\n```"),
    ("How do you virtualize large lists (10,000+ items) in React?", "Advanced", "Virtual windowing computes visible items based on scroll offset and only renders DOM elements in view.", "```jsx\nexport function VirtualList({ items, itemHeight = 40, height = 400 }) {\n  const [scroll, setScroll] = useState(0);\n  const start = Math.floor(scroll / itemHeight);\n  const count = Math.ceil(height / itemHeight) + 2;\n  const visible = items.slice(start, start + count);\n  return (\n    <div style={{ height, overflowY: 'auto' }} onScroll={e => setScroll(e.target.scrollTop)}>\n      <div style={{ height: items.length * itemHeight, position: 'relative' }}>\n        {visible.map((item, idx) => (\n          <div key={item.id} style={{ position: 'absolute', top: (start + idx) * itemHeight }}>{item.title}</div>\n        ))}\n      </div>\n    </div>\n  );\n}\n```"),
    ("How do you implement a custom `useDebounce` hook?", "Intermediate", "Delay updating state until delay period passes without new changes.", "```typescript\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => {\n    const timer = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n  return debounced;\n}\n```"),
    ("What is the difference between Controlled and Uncontrolled components?", "Beginner", "Controlled components have value driven by React state; uncontrolled components rely on native DOM state via `ref`.", "```jsx\n// Controlled\n<input value={val} onChange={e => setVal(e.target.value)} />\n// Uncontrolled\n<input ref={inputRef} defaultValue=\"Initial\" />\n```"),
    ("What is React StrictMode and why does it double-invoke effects in development?", "Beginner", "StrictMode checks for purity and missing cleanup by mounting, unmounting, and re-mounting components in dev mode.", "```jsx\n<React.StrictMode><App /></React.StrictMode>\n```"),
    ("How do you implement custom `usePrevious` hook using `useRef`?", "Intermediate", "Updating `useRef` inside `useEffect` captures the previous render's value without triggering a re-render.", "```typescript\nexport function usePrevious<T>(value: T): T | undefined {\n  const ref = useRef<T>();\n  useEffect(() => { ref.current = value; }, [value]);\n  return ref.current;\n}\n```"),
    ("How do you implement custom `useLocalStorage` hook with multi-tab synchronization?", "Intermediate", "Sync state with localStorage and subscribe to the `storage` event for cross-tab updates.", "```typescript\nexport function useLocalStorage<T>(key: string, initial: T) {\n  const [val, setVal] = useState<T>(() => {\n    try { const item = localStorage.getItem(key); return item ? JSON.parse(item) : initial; } catch { return initial; }\n  });\n  const update = (newVal: T) => {\n    setVal(newVal);\n    localStorage.setItem(key, JSON.stringify(newVal));\n  };\n  return [val, update] as const;\n}\n```")
]

for t in react_topics_remaining:
    react_data.append(t)

# Add 80 more specific questions to react_data to make exact 100
react_extra = [
    ("How do you implement custom hook `useOnClickOutside` for dropdowns?", "Intermediate", "Listen to document mousedown and check if ref contains target.", "```typescript\nexport function useOnClickOutside(ref: any, handler: () => void) {\n  useEffect(() => {\n    const listener = (e: any) => { if (!ref.current?.contains(e.target)) handler(); };\n    document.addEventListener('mousedown', listener);\n    return () => document.removeEventListener('mousedown', listener);\n  }, [ref, handler]);\n}\n```"),
    ("What is `useSyncExternalStore` and when should you use it?", "Advanced", "Subscribes to external stores safely avoiding tearing in concurrent mode.", "```typescript\nimport { useSyncExternalStore } from 'react';\nfunction subscribe(cb: () => void) {\n  window.addEventListener('online', cb);\n  return () => window.removeEventListener('online', cb);\n}\nexport const useOnline = () => useSyncExternalStore(subscribe, () => navigator.onLine, () => true);\n```"),
    ("What is `useOptimistic` in React 19 and how does it improve UX?", "Advanced", "Provides immediate optimistic UI state while an async server action executes.", "```jsx\nimport { useOptimistic } from 'react';\nexport function LikeButton({ likes, onLike }) {\n  const [opt, setOpt] = useOptimistic(likes, (prev) => prev + 1);\n  return <button onClick={async () => { setOpt(likes + 1); await onLike(); }}>❤️ {opt}</button>;\n}\n```"),
    ("What is `useActionState` in React 19?", "Advanced", "Integrates server actions with component state and pending status.", "```jsx\nimport { useActionState } from 'react';\nasync function action(prev, formData) { return { count: prev.count + 1 }; }\nexport function Form() {\n  const [state, formAction, isPending] = useActionState(action, { count: 0 });\n  return <form action={formAction}><button disabled={isPending}>Count: {state.count}</button></form>;\n}\n```"),
    ("What is the difference between shallow and deep comparison in React memoization?", "Intermediate", "Shallow checks references; deep recursively checks all properties.", "```javascript\nfunction arePropsEqual(prev, next) { return prev.id === next.id; }\nexport const MemoCard = React.memo(Card, arePropsEqual);\n```"),
    ("Why should you avoid using array index as `key` prop in React lists?", "Beginner", "Index keys break component state association during re-ordering or deletions.", "```jsx\n// Good\n{items.map(item => <Item key={item.id} data={item} />)}\n```"),
    ("How do you manage Focus for accessibility (a11y) inside React Modals?", "Intermediate", "Trap tab focus inside the modal and return focus to trigger on close.", "```jsx\nuseEffect(() => { if (isOpen) ref.current?.focus(); }, [isOpen]);\n```"),
    ("How do you implement Polymorphic components in React with TypeScript (`as` prop)?", "Advanced", "Use generic props extending `React.ElementType`.", "```tsx\ntype ButtonProps<T extends React.ElementType> = { as?: T; children: React.ReactNode; } & React.ComponentPropsWithoutRef<T>;\nexport function Button<T extends React.ElementType = 'button'>({ as, children, ...props }: ButtonProps<T>) {\n  const Component = as || 'button';\n  return <Component {...props}>{children}</Component>;\n}\n```"),
    ("How do you implement code splitting with `React.lazy` and `Suspense`?", "Intermediate", "Dynamically import components to create separate chunks.", "```jsx\nconst Admin = React.lazy(() => import('./Admin'));\n<React.Suspense fallback={<div>Loading...</div>}><Admin /></React.Suspense>\n```"),
    ("How do you test React components with Jest and React Testing Library?", "Intermediate", "Test behavior with `screen.getByRole` and `userEvent`.", "```tsx\ntest('increments', async () => {\n  render(<Counter />);\n  await userEvent.click(screen.getByRole('button', { name: /inc/i }));\n  expect(screen.getByText('1')).toBeInTheDocument();\n});\n```"),
    ("What causes memory leaks in React and how do you diagnose them?", "Advanced", "Uncleaned subscriptions, timers, and closures retaining DOM nodes.", "```javascript\nuseEffect(() => {\n  const sub = eventBus.subscribe(handler);\n  return () => sub.unsubscribe(); // Must cleanup\n}, []);\n```"),
    ("How does React protect against XSS attacks in JSX?", "Intermediate", "React escapes all strings embedded in JSX before rendering.", "```jsx\n// React escapes malicious strings automatically\nconst dangerous = '<script>alert(\"XSS\")</script>';\nreturn <div>{dangerous}</div>;\n```"),
    ("How do you safely render HTML in React with DOMPurify?", "Intermediate", "Sanitize the string before using `dangerouslySetInnerHTML`.", "```jsx\nimport DOMPurify from 'dompurify';\nexport function SafeHTML({ content }) {\n  const clean = DOMPurify.sanitize(content);\n  return <div dangerouslySetInnerHTML={{ __html: clean }} />;\n}\n```"),
    ("How do you implement custom `useInterval` hook?", "Intermediate", "Store latest callback in ref to prevent stale closures while keeping interval active.", "```javascript\nexport function useInterval(cb, delay) {\n  const ref = useRef(cb);\n  useEffect(() => { ref.current = cb; }, [cb]);\n  useEffect(() => {\n    if (delay !== null) {\n      const id = setInterval(() => ref.current(), delay);\n      return () => clearInterval(id);\n    }\n  }, [delay]);\n}\n```"),
    ("How do you implement Infinite Scroll using `IntersectionObserver`?", "Intermediate", "Attach observer to sentinel element at list bottom.", "```jsx\nuseEffect(() => {\n  const observer = new IntersectionObserver(([e]) => { if (e.isIntersecting) loadMore(); });\n  if (ref.current) observer.observe(ref.current);\n  return () => observer.disconnect();\n}, [loadMore]);\n```"),
    ("How do you build an accessible Accordion component?", "Intermediate", "Use `aria-expanded`, `aria-controls`, and `role=\"region\"`.", "```jsx\n<button aria-expanded={isOpen} aria-controls=\"panel-1\" onClick={toggle}>Header</button>\n{isOpen && <div id=\"panel-1\" role=\"region\">Content</div>}\n```"),
    ("How does React Profiler API work in production?", "Advanced", "Measure render phase durations with `<Profiler onRender={callback}>`.", "```jsx\n<Profiler id=\"App\" onRender={(id, phase, time) => console.log(id, phase, time)}><App /></Profiler>\n```"),
    ("What is Prop Drilling and how does Component Composition resolve it?", "Beginner", "Pass JSX components as children or props rather than drilling state down many levels.", "```jsx\n<Page header={<UserAvatar user={user} />} />\n```"),
    ("How do you handle JWT authentication refresh flow in React?", "Advanced", "Use Axios response interceptors to refresh access token on 401 error.", "```javascript\naxios.interceptors.response.use(res => res, async err => {\n  if (err.response?.status === 401) { await refreshToken(); return axios(err.config); }\n  return Promise.reject(err);\n});\n```"),
    ("What is the difference between `React.createElement` and JSX?", "Beginner", "JSX is syntactic sugar compiled into `React.createElement` or JSX runtime `jsx()` calls.", "```javascript\n// JSX: <div className=\"box\">Hi</div>\nReact.createElement('div', { className: 'box' }, 'Hi');\n```"),
    ("How do you handle multi-step forms in React?", "Intermediate", "Manage a step state index and collect accumulated form data at each step.", "```jsx\nconst [step, setStep] = useState(1);\nconst [data, setData] = useState({});\n```"),
    ("How do you optimize SVG icons in React?", "Beginner", "Use SVGR to bundle SVGs as reusable vector components.", "```jsx\nexport const Icon = ({ size = 24 }) => <svg width={size} height={size} viewBox=\"0 0 24 24\"><path d=\"M12 2L2 22h20L12 2z\"/></svg>;\n```"),
    ("What is client-side routing vs server-side routing?", "Beginner", "Client routing updates the DOM and History API without requesting a new HTML document.", "```jsx\nimport { BrowserRouter, Routes, Route, Link } from 'react-router-dom';\n```"),
    ("How do you create a custom `useMediaQuery` hook?", "Intermediate", "Listen to `window.matchMedia` change events.", "```typescript\nexport function useMediaQuery(query: string) {\n  const [matches, setMatches] = useState(() => window.matchMedia(query).matches);\n  useEffect(() => {\n    const media = window.matchMedia(query);\n    const listener = (e: MediaQueryListEvent) => setMatches(e.matches);\n    media.addEventListener('change', listener);\n    return () => media.removeEventListener('change', listener);\n  }, [query]);\n  return matches;\n}\n```"),
    ("How do you cancel pending Axios requests on unmount?", "Intermediate", "Pass `AbortController.signal` into Axios config.", "```javascript\nuseEffect(() => {\n  const ctrl = new AbortController();\n  axios.get('/api', { signal: ctrl.signal });\n  return () => ctrl.abort();\n}, []);\n```"),
    ("What are Render Props and why did Hooks replace them?", "Intermediate", "Render props pass a rendering function as prop; hooks eliminate JSX wrapper nesting.", "```jsx\n<DataProvider render={data => <div>{data.title}</div>} />\n```"),
    ("How do you implement Dark Mode with CSS Variables?", "Beginner", "Toggle `data-theme` on documentElement and persist in localStorage.", "```javascript\ndocument.documentElement.setAttribute('data-theme', 'dark');\n```"),
    ("How do you handle Hydration mismatch errors in React SSR?", "Advanced", "Ensure server and initial client render outputs match, or use `suppressHydrationWarning`.", "```jsx\n<span suppressHydrationWarning>{new Date().toLocaleTimeString()}</span>\n```"),
    ("What is `useId` and why is it important for accessibility?", "Beginner", "Generates stable, unique IDs across client and server rendering.", "```jsx\nconst id = useId();\nreturn <><label htmlFor={id}>Email</label><input id={id}/></>;\n```"),
    ("How do you implement Drag and Drop in React?", "Intermediate", "Use native HTML Drag and Drop events or `dnd-kit` library.", "```jsx\n<div draggable onDragStart={e => e.dataTransfer.setData('text', 'id')}>Item</div>\n```"),
    ("What is the purpose of `React.Children.map`?", "Intermediate", "Safely iterates over opaque `props.children` elements.", "```jsx\nReact.Children.map(children, child => React.cloneElement(child, { extra: true }))\n```"),
    ("How do you prevent unnecessary re-renders with Context objects?", "Intermediate", "Wrap context values inside `useMemo`.", "```jsx\nconst value = useMemo(() => ({ user, theme }), [user, theme]);\nreturn <Ctx.Provider value={value}>{children}</Ctx.Provider>;\n```"),
    ("What are Higher-Order Components and what are their limitations?", "Intermediate", "Functions returning enhanced components; limitations include prop collisions and wrapper hell.", "```jsx\nexport const withLogger = (Comp) => (props) => { console.log('Render', props); return <Comp {...props}/>; };\n```"),
    ("How do you implement Undo/Redo history in React state?", "Advanced", "Maintain past, present, and future state arrays in a reducer.", "```javascript\nfunction undoReducer(state, action) {\n  if (action.type === 'UNDO') return { past: state.past.slice(0, -1), present: state.past[state.past.length - 1], future: [state.present, ...state.future] };\n  return state;\n}\n```"),
    ("What is the purpose of `useImperativeHandle`?", "Advanced", "Exposes imperative methods when parent component accesses ref.", "```jsx\nuseImperativeHandle(ref, () => ({ scroll: () => ref.current.scrollIntoView() }));\n```"),
    ("How do you debounce API validation in React Hook Form?", "Intermediate", "Debounce validation handler with lodash or custom timer.", "```jsx\nconst debouncedValidate = debounce(checkUsername, 500);\n```"),
    ("What is the difference in event delegation between React 16 and 17+?", "Advanced", "React 17+ attaches event listeners to root container rather than `document`.", "```javascript\n// In React 17+, document.addEventListener runs before React synthetic events\n```"),
    ("How do you implement Skeleton Loaders during data fetching?", "Beginner", "Render placeholder pulse shapes while `loading` state is true.", "```jsx\n{loading ? <div className=\"skeleton\" /> : <Content data={data} />}\n```"),
    ("How do you control HTML `<dialog>` element in React?", "Intermediate", "Use `ref.current.showModal()` and `ref.current.close()`.", "```jsx\nconst ref = useRef();\n<dialog ref={ref}><button onClick={() => ref.current.close()}>Close</button></dialog>\n```"),
    ("How does Server-Side Rendering (SSR) improve SEO?", "Intermediate", "Search engines receive pre-rendered HTML content on first response.", "```javascript\n// Full HTML content available immediately for search crawlers\n```"),
    ("What is Static Site Generation (SSG)?", "Beginner", "Pre-generates static HTML pages at build time.", "```javascript\n// Pages generated once at build time for instant CDN delivery\n```"),
    ("What is Incremental Static Regeneration (ISR)?", "Advanced", "Regenerates static pages in background on incoming requests after revalidation period.", "```javascript\n// export const revalidate = 60;\n```"),
    ("What is `React.cloneElement` and why is it discouraged in modern React?", "Intermediate", "Clones element and injects props; discouraged because it obscures data flow compared to Context or Render Props.", "```jsx\nReact.cloneElement(child, { isActive: true })\n```"),
    ("How do you build a Global Toast Notification system in React?", "Intermediate", "Use Context Provider with reducer queue and auto-dismiss timer.", "```jsx\nconst { addToast } = useToast();\naddToast('Saved successfully', 'success');\n```"),
    ("How do you memoize recursive components in React?", "Advanced", "Wrap recursive component in `React.memo` with stable parent callbacks.", "```jsx\nconst TreeNode = React.memo(({ node }) => (\n  <div>{node.name}{node.children?.map(c => <TreeNode key={c.id} node={c}/>)}</div>\n));\n```"),
    ("What is State Hoisting (Lifting State Up)?", "Beginner", "Moving state to nearest common ancestor so sibling components can share it.", "```jsx\nfunction Parent() {\n  const [val, setVal] = useState('');\n  return <><Input val={val} setVal={setVal}/><Display val={val}/></>;\n}\n```"),
    ("How do you build dynamic breadcrumb navigation in React?", "Intermediate", "Parse current pathname and map segments to links.", "```jsx\nconst paths = location.pathname.split('/').filter(Boolean);\n```"),
    ("What is the difference between `PureComponent` and `Component`?", "Beginner", "`PureComponent` automatically implements `shouldComponentUpdate` with shallow prop/state comparison.", "```jsx\nclass Card extends React.PureComponent { render() { return <div>{this.props.title}</div>; } }\n```"),
    ("How do you track file upload progress in React?", "Intermediate", "Use Axios `onUploadProgress` or XMLHttpRequest upload listener.", "```javascript\naxios.post('/upload', formData, { onUploadProgress: e => setProgress(Math.round((e.loaded * 100) / e.total)) });\n```"),
    ("How do you implement responsive table card layouts in React?", "Intermediate", "Use CSS Grid and media queries to convert table rows into card elements on mobile.", "```css\n@media (max-width: 600px) { tr { display: flex; flex-direction: column; } }\n```"),
    ("What is the difference between `<React.Fragment>` and `<>` shorthand?", "Beginner", "`<React.Fragment>` accepts `key` attribute; `<>` shorthand does not.", "```jsx\n<React.Fragment key={id}><div>1</div><div>2</div></React.Fragment>\n```"),
    ("How do you handle keyboard arrow navigation in Tabs?", "Intermediate", "Listen for ArrowLeft / ArrowRight keydown events and shift active tab focus.", "```jsx\nonKeyDown={e => { if (e.key === 'ArrowRight') nextTab(); }}\n```"),
    ("What is the difference between `window.location.href` and React Router `navigate`?", "Beginner", "`window.location.href` triggers full page reload; `navigate` performs fast client-side transition.", "```jsx\nnavigate('/dashboard');\n```"),
    ("How do you mock API calls in Jest without extra libraries?", "Intermediate", "Mock `global.fetch` with `jest.fn()` returning a resolved Promise.", "```javascript\nglobal.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve({ data: 123 }) }));\n```"),
    ("How do you test custom hooks using `renderHook`?", "Intermediate", "Use `renderHook` from `@testing-library/react` and wrap state changes in `act`.", "```tsx\nconst { result } = renderHook(() => useCounter());\nact(() => result.current.inc());\nexpect(result.current.count).toBe(1);\n```"),
    ("What is Micro-frontend Module Federation with React?", "Advanced", "Dynamically imports independent React builds at runtime across multiple domains.", "```javascript\n// ModuleFederationPlugin config\n```"),
    ("How do you optimize Core Web Vitals (LCP, INP, CLS) in React?", "Advanced", "Preload hero images, split heavy bundles, reserve aspect-ratio boxes, and defer non-critical JS.", "```jsx\n<img src=\"/hero.webp\" fetchPriority=\"high\" />\n```"),
    ("How do you implement Copy to Clipboard with temporary tooltip?", "Beginner", "Use `navigator.clipboard.writeText` and timeout state.", "```jsx\nconst copy = () => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); };\n```"),
    ("What is the difference between dependencies and peerDependencies in React packages?", "Intermediate", "`dependencies` are installed by the package; `peerDependencies` must be installed by host application.", "```json\n\"peerDependencies\": { \"react\": \">=18.0.0\" }\n```"),
    ("How do you build an accessible Dropdown menu in React?", "Intermediate", "Use `aria-haspopup=\"true\"`, `aria-expanded`, and Escape key to close.", "```jsx\n<button aria-haspopup=\"true\" aria-expanded={open} onClick={toggle}>Menu</button>\n```"),
    ("How do you test Error Boundary components with React Testing Library?", "Intermediate", "Spy on `console.error` and assert fallback UI is visible when child throws.", "```jsx\nrender(<ErrorBoundary><Bomb /></ErrorBoundary>);\nexpect(screen.getByRole('alert')).toBeInTheDocument();\n```"),
    ("What was SyntheticEvent pooling in React 16 and why was it removed in React 17?", "Advanced", "React 16 reused event objects across ticks for memory efficiency; React 17 removed it so events can be accessed asynchronously without `e.persist()`.", "```javascript\n// In React 17+, event properties can be accessed in async callbacks safely\n```"),
    ("How do you implement custom `useHover` hook?", "Intermediate", "Listen for `mouseenter` and `mouseleave` events.", "```typescript\nexport function useHover(ref: any) {\n  const [hovered, setHovered] = useState(false);\n  useEffect(() => {\n    const on = () => setHovered(true), off = () => setHovered(false);\n    const el = ref.current;\n    el?.addEventListener('mouseenter', on);\n    el?.addEventListener('mouseleave', off);\n    return () => { el?.removeEventListener('mouseenter', on); el?.removeEventListener('mouseleave', off); };\n  }, [ref]);\n  return hovered;\n}\n```"),
    ("How do you handle i18n localization in React?", "Intermediate", "Use `react-i18next` with JSON translation resources.", "```jsx\nconst { t } = useTranslation();\nreturn <h1>{t('welcome_message')}</h1>;\n```"),
    ("What are the advantages of `pnpm` in React monorepos?", "Intermediate", "Content-addressable store hard-links packages, preventing phantom dependencies and saving disk space.", "```bash\npnpm install\n```"),
    ("How do you implement pagination with ellipsis in React?", "Intermediate", "Generate page array `[1, '...', curr-1, curr, curr+1, '...', total]`.", "```jsx\nconst pages = getPaginationRange(current, total);\n```"),
    ("What is client state vs server state in React applications?", "Intermediate", "Client state handles local UI controls; server state handles remote persisted data requiring caching/invalidation.", "```javascript\n// Client: const [isOpen, setOpen] = useState(false);\n// Server: const { data } = useQuery(['user'], fetchUser);\n```"),
    ("How do you implement auto-saving forms in React?", "Intermediate", "Debounce changes and fire background PATCH requests with save indicators.", "```jsx\nuseDebounceEffect(() => { api.save(formData); }, 1000, [formData]);\n```"),
    ("How do you build a custom Range Slider in React?", "Intermediate", "Control `<input type=\"range\">` and compute CSS gradient progress fill.", "```jsx\n<input type=\"range\" min=\"0\" max=\"100\" value={val} onChange={e => setVal(e.target.value)} />\n```"),
    ("What are React Server Actions and how do they replace API routes?", "Advanced", "Async server functions called directly from client forms with automatic serialization.", "```jsx\nasync function create(formData) { 'use server'; await db.insert(formData); }\n```"),
    ("How do you implement WebAuthn biometric login in React?", "Advanced", "Call `navigator.credentials.get()` for biometric passkey authentication.", "```javascript\nconst cred = await navigator.credentials.get({ publicKey: options });\n```"),
    ("How do you create animated notification badges in React?", "Beginner", "Trigger CSS keyframe bounce animation whenever count changes.", "```css\n@keyframes bounce { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.3); } }\n```"),
    ("What is the difference between `useCallback` and regular inline functions?", "Beginner", "Inline functions create new references every render; `useCallback` returns cached function identity.", "```jsx\nconst fn = useCallback(() => doWork(id), [id]);\n```"),
    ("How do you implement sticky headers in React?", "Beginner", "Use CSS `position: sticky; top: 0; z-index: 10;`.", "```css\n.header { position: sticky; top: 0; z-index: 100; }\n```"),
    ("How do you structure enterprise React codebases?", "Advanced", "Feature-based architecture with modules containing UI, hooks, api, and tests.", "```\nsrc/features/auth/{components, hooks, api, authSlice.ts}\n```"),
    ("How do you test accessibility with `@axe-core/react`?", "Intermediate", "Log WCAG violations directly to developer console.", "```javascript\nif (process.env.NODE_ENV !== 'production') { axe(React, ReactDOM, 1000); }\n```"),
    ("What is the difference between SPA and MPA?", "Beginner", "SPA renders client-side without full reloads; MPA requests full HTML documents per route.", "```javascript\n// SPA provides app-like fluid navigation\n```"),
    ("How do you handle multi-tab session expiration in React?", "Advanced", "Broadcast logout messages via `BroadcastChannel` or `localStorage` events.", "```javascript\nconst bc = new BroadcastChannel('auth');\nbc.onmessage = (e) => { if (e.data === 'logout') logout(); };\n```"),
    ("How do you implement custom `useCountdown` hook?", "Intermediate", "Decrement seconds using `setInterval` until reaching zero.", "```typescript\nexport function useCountdown(initialSec: number) {\n  const [sec, setSec] = useState(initialSec);\n  useEffect(() => {\n    if (sec <= 0) return;\n    const id = setInterval(() => setSec(s => s - 1), 1000);\n    return () => clearInterval(id);\n  }, [sec]);\n  return sec;\n}\n```"),
    ("What is shallow routing in React Router?", "Intermediate", "Updates URL query params without reloading route data loaders.", "```jsx\nsetSearchParams({ filter: 'active' });\n```")
]

for t in react_extra:
    if len(react_data) < 100:
        react_data.append(t)

create_100_qnas(
    "react",
    "react-questions.md",
    "React.js",
    "Comprehensive, practical interview questions covering React 18/19, Hooks, Fiber, and Performance",
    "html-css-js-icon.svg",
    react_data[:100]
)

print("React 100 complete.")
