import os
import sys
sys.path.append(os.path.dirname(__file__))
from writer_helper import write_category_file

# ==============================================================================
# 3. AI ENGINEERING & LLMs (100 REAL QUESTIONS)
# ==============================================================================
ai_raw = [
    ("How does Retrieval-Augmented Generation (RAG) work, and how do you optimize Chunking, Embedding, and Reranking?", "Advanced",
     "RAG enriches LLM context with domain-specific knowledge: 1) Documents are chunked (e.g. 512 tokens with 10% overlap). 2) Chunk texts are embedded via dense encoder models into vector representations stored in a Vector DB (Qdrant/Milvus/Pinecone). 3) Approximate Nearest Neighbor (ANN) search retrieves top-K candidates. 4) A cross-encoder Reranker scores document relevance against the raw query. 5) Reranked contexts are injected into the prompt context window.",
     "```python\n# Enterprise RAG Pipeline with Cross-Encoder Reranker\nfrom sentence_transformers import CrossEncoder\n\n# Stage 1: Vector search returns top 20 candidates\ncandidates = vector_db.search(query_embedding, limit=20)\n\n# Stage 2: Cross-Encoder scores exact (query, document) pairs\nreranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')\npairs = [[query, doc.text] for doc in candidates]\nscores = reranker.predict(pairs)\n\n# Stage 3: Top 3 highest scoring documents injected into LLM prompt\ntop_docs = [candidates[i] for i in scores.argsort()[-3:][::-1]]\n```"),

    ("How does the Transformer Self-Attention mechanism work mathematically ($Q, K, V$), and what is the computational complexity?", "Advanced",
     "Self-attention maps queries ($Q$), keys ($K$), and values ($V$) via: $\\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$. Computing $QK^T$ requires an $N \\times N$ matrix multiplication where $N$ is sequence length, yielding $O(N^2)$ time and memory complexity. The $\\sqrt{d_k}$ scaling factor prevents dot products from growing excessively large in high dimensions, which would push softmax into regions with vanishing gradients.",
     "```python\n# Scaled Dot-Product Attention in PyTorch\nimport torch\nimport torch.nn.functional as F\n\ndef scaled_dot_product_attention(Q, K, V, mask=None):\n    d_k = Q.size(-1)\n    scores = torch.matmul(Q, K.transpose(-2, -1)) / (d_k ** 0.5)\n    if mask is not None:\n        scores = scores.masked_fill(mask == 0, -1e9)\n    weights = F.softmax(scores, dim=-1)\n    return torch.matmul(weights, V)\n```"),

    ("What is FlashAttention (FlashAttention-2) and how does it achieve 2-4x speedup via Tiling and Kernel Fusion?", "Advanced",
     "Standard attention reads and writes the intermediate $N \\times N$ attention matrix to slow GPU High Bandwidth Memory (HBM). FlashAttention tiles the $Q, K, V$ matrices into smaller blocks that fit into ultra-fast on-chip GPU SRAM (shared memory), computes softmax incrementally using online softmax normalization, and writes only the final output back to HBM, reducing memory bandwidth transfers from $O(N^2)$ to $O(N)$.",
     "```text\nStandard Attention: GPU SRAM -> Write N^2 Softmax to HBM -> Read from HBM (Slow!)\nFlashAttention: Tiled Q,K,V blocks stay in GPU SRAM (20TB/s) -> Online Softmax -> Single HBM Write\n```"),

    ("How does Parameter-Efficient Fine-Tuning (PEFT) with LoRA (Low-Rank Adaptation) and QLoRA work?", "Advanced",
     "LoRA freezes pretrained model weights $W_0 \\in \\mathbb{R}^{d \\times k}$ and injects trainable rank-decomposition matrices $\\Delta W = B \\cdot A$ where $B \\in \\mathbb{R}^{d \\times r}$ and $A \\in \\mathbb{R}^{r \\times k}$ with rank $r \\ll \\min(d, k)$. QLoRA quantizes the base model weights to 4-bit NormalFloat (NF4) with double quantization, maintaining full precision LoRA adapter weights, allowing fine-tuning a 70B parameter model on a single 48GB GPU.",
     "```python\n# HuggingFace PEFT LoRA Configuration\nfrom peft import LoraConfig, get_peft_model\n\nconfig = LoraConfig(\n    r=16, # Rank dimension\n    lora_alpha=32,\n    target_modules=[\"q_proj\", \"v_proj\"],\n    lora_dropout=0.05,\n    bias=\"none\",\n    task_type=\"CAUSAL_LM\"\n)\nmodel = get_peft_model(base_model, config)\nmodel.print_trainable_parameters() # Only ~0.1% parameters trained!\n```"),

    ("How do Vector Databases index high-dimensional embeddings using HNSW (Hierarchical Navigable Small World)?", "Advanced",
     "HNSW constructs a multi-layer graph hierarchy where upper layers have longer skip links (like a skip-list) and bottom layers contain dense local nearest-neighbor graphs. Queries start at top layer, perform greedy search to local minimum, drop down to next layer, achieving approximate $O(\\log N)$ search latency for million-scale vector spaces.",
     "```text\nHNSW Layer Hierarchy:\nLayer 2: [Node A] --------------------> [Node Z] (Express Highway)\nLayer 1: [Node A] ---------> [Node M] ---------> [Node Z]\nLayer 0: [Node A]->[Node B]->[Node C]... (Dense All Nodes, Exact Neighbors)\n```")
]

# 95 more distinct AI engineering topics
ai_topics = [
    ("What is PagedAttention in vLLM and how does it eliminate KV Cache memory fragmentation?", "Advanced", "Applies virtual memory paging to LLM KV caches, allocating dynamic non-contiguous physical blocks in GPU VRAM, boosting serving throughput by 2-4x."),
    ("How does Speculative Decoding accelerate LLM inference without quality loss?", "Advanced", "Uses a small draft model to generate $K$ tokens quickly; the large target model verifies all $K$ tokens in a single parallel forward pass."),
    ("What are LLM Hallucinations and what techniques mitigate them in production?", "Intermediate", "Grounding answers with RAG, chain-of-thought verification, logit bias calibration, and guardrails like NeMo Guardrails."),
    ("What is Prompt Injection (Direct vs Indirect) and how do you defend against it?", "Advanced", "Direct: user overrides system prompt. Indirect: untrusted external document contains hidden instructions. Defended with input sanitization and dual-LLM arbiters."),
    ("How does RLHF (Reinforcement Learning from Human Feedback) differ from DPO (Direct Preference Optimization)?", "Advanced", "RLHF trains a separate reward model and optimizes via PPO; DPO implicitly optimizes the policy directly on preference pairs without a reward model."),
    ("What are RoPE (Rotary Position Embeddings) and how do they scale context windows?", "Advanced", "Encodes relative position by rotating Query and Key vectors in complex 2D planes, enabling position extrapolation via Yarn/NTK-aware scaling."),
    ("How does LLM Quantization work (GPTQ, AWQ, GGUF, INT8/INT4)?", "Advanced", "Quantizes 16-bit FP weights to 4/8-bit integers; AWQ protects top 1% salient weight channels from quantization to preserve reasoning accuracy."),
    ("What is the difference between Dense Retrieval and Sparse Retrieval (BM25 vs Vector Embeddings)?", "Intermediate", "BM25 matches exact lexical keywords; Dense embeddings match semantic meaning; Hybrid Search fuses both scores using Reciprocal Rank Fusion (RRF)."),
    ("How do LLM Agents use ReAct (Reason + Act) loops and Function Calling?", "Intermediate", "The LLM generates a Thought, selects an external Tool action (e.g. SQL query or web search), parses the Observation, and iterates until final answer."),
    ("What is Multi-Query Retrieval and Query Expansion in RAG systems?", "Intermediate", "Uses an LLM to generate 3-5 alternative phrasings of a user prompt to improve recall across varied document terminologies in vector search."),
    ("How does Context Compression and Semantic Chunking improve RAG quality?", "Intermediate", "Semantic chunking splits text on semantic cosine shifts rather than fixed character counts; Context compression strips irrelevant sentences before feeding the LLM."),
    ("What is Vector Quantization (Product Quantization PQ) in Vector Databases?", "Advanced", "Decomposes high-dimensional vectors into $M$ sub-vectors, quantizing each to nearest centroid index, reducing RAM consumption by up to 90%."),
    ("How do you evaluate RAG pipelines using the RAGAS framework (Faithfulness, Answer Relevance, Context Precision)?", "Intermediate", "RAGAS evaluates generation against context (Faithfulness), answer against query (Relevance), and context against ground truth (Precision)."),
    ("What is Mixture of Experts (MoE) architecture (e.g. Mixtral 8x7B) and how does Sparse Gating work?", "Advanced", "Replaces feed-forward layers with multiple expert networks; a learned gating router activates only top-2 experts per token, keeping inference cost low."),
    ("What is Grouped-Query Attention (GQA) and Multi-Query Attention (MQA) vs Multi-Head Attention (MHA)?", "Advanced", "MHA has separate Key/Value heads per Query head; MQA shares 1 K/V head across all queries; GQA groups query heads (e.g. 8:1), drastically shrinking KV cache size."),
    ("How do you implement Structured Output Generation (JSON Schema enforcement) in LLMs?", "Intermediate", "Constrains token sampling probabilities by masking tokens at each step that violate the grammar/regex using Outlines or Guidance finite-state machines."),
    ("What is Self-RAG and Adaptive Retrieval in agentic systems?", "Advanced", "LLM generates reflection tokens determining whether retrieval is necessary, evaluates retrieved document relevance, and self-critiques response quality."),
    ("How does Semantic Caching with Redis reduce LLM API latency and cost?", "Intermediate", "Embeds incoming queries; if cosine similarity to a cached query exceeds 0.96, returns cached LLM response in <5ms without re-invoking the model."),
    ("What is Continuous Batching (Iteration-level Scheduling) in LLM inference servers (TGI, vLLM)?", "Advanced", "Instead of waiting for an entire batch of sequences to finish generation, new requests enter the batch immediately as individual sequences output EOS tokens."),
    ("How does Temperature, Top-P (Nucleus), and Top-K sampling affect LLM text generation?", "Beginner", "Temperature scales logits (lower = deterministic); Top-K restricts to top K most probable tokens; Top-P dynamically pools tokens until cumulative probability hits threshold P."),
    ("What is Model Distillation and how do you train smaller student models from large teacher models?", "Advanced", "Trains student model to match the output probability distribution (soft targets) and intermediate representations of the larger teacher model."),
    ("How do you detect Data Drift and Concept Drift in production ML embeddings?", "Intermediate", "Calculate Wasserstein Distance or Maximum Mean Discrepancy (MMD) between production query embeddings and training baseline distributions."),
    ("What are Guardrails in LLM architectures (Llama Guard, NeMo Guardrails)?", "Intermediate", "Dual-stage classifiers evaluating input prompts and output generations against safety policies (hate speech, PII leaks, system prompt extraction)."),
    ("How does Tool Use and MCP (Model Context Protocol) standardize LLM agent integrations?", "Intermediate", "MCP establishes a standardized JSON-RPC protocol allowing LLMs to discover tools, query resource schemas, and invoke functions across client environments."),
    ("What is the Needle-In-A-Haystack (NIAH) benchmark and how does it test long-context LLMs?", "Intermediate", "Hides a random factual statement at varying depth percentages in long context documents (100k+ tokens) to measure retrieval recall accuracy."),
    ("How do you optimize Vector DB search latency using Inverted File Index with Flat Quantization (IVF-Flat)?", "Intermediate", "Partitions vector space into Voronoi cells using k-means clustering; queries probe only centroids closest to query vector instead of brute-force scanning."),
    ("What is Chain-of-Thought (CoT) and Tree-of-Thoughts (ToT) prompting?", "Intermediate", "CoT prompts step-by-step reasoning tokens before final answer; ToT explores multiple reasoning branches with heuristic evaluation and backtracking."),
    ("How does Instruction Fine-Tuning differ from Pre-Training?", "Beginner", "Pre-training trains on raw text predicting next token on trillions of words; Instruction fine-tuning trains on (Instruction, Input, Response) pairs to teach following directions."),
    ("What is catastrophic forgetting and how do replay buffers and EWC prevent it in continual learning?", "Advanced", "Neural network completely forgets previously learned tasks when trained on new data; mitigated by mixing in historical replay data or penalizing weight shifts on critical weights."),
    ("How do you handle PII redaction in LLM training and inference pipelines?", "Intermediate", "Run Named Entity Recognition (NER) models (Microsoft Presidio) to detect emails, SSNs, and credit cards, replacing them with typed tokens `<EMAIL>`."),
    ("What is Cross-Encoder vs Bi-Encoder in semantic search architectures?", "Intermediate", "Bi-encoders encode query and document independently (fast, vector DB friendly); Cross-encoders process query and document together (slow, highly accurate for reranking)."),
    ("How does Activation Checkpointing (Gradient Checkpointing) save GPU VRAM during LLM training?", "Advanced", "Discards intermediate activation tensors during forward pass, recalculating them on-the-fly during backward pass, reducing peak memory from $O(N)$ to $O(\\sqrt{N})$."),
    ("What is Tensor Parallelism (Megatron-LM) vs Pipeline Parallelism?", "Advanced", "Tensor parallelism splits individual matrix multiplications (column/row parallel) across GPUs within a node; Pipeline parallelism splits model layers across nodes."),
    ("How do you implement Graph RAG with Knowledge Graphs (Neo4j)?", "Advanced", "Extracts entities and relationships into a graph database; traverses multi-hop graph neighborhoods to answer complex queries requiring reasoning across disjoint documents."),
    ("What is Zero-Shot vs Few-Shot learning in LLMs?", "Beginner", "Zero-shot tests model capability without examples; Few-shot provides 2-5 demonstrative (input, output) exemplars in the prompt context."),
    ("How do you handle Tokenizer differences (BPE vs WordPiece vs SentencePiece)?", "Intermediate", "BPE merges most frequent byte pairs iteratively; WordPiece merges pairs maximizing likelihood of training data; SentencePiece treats text as raw Unicode stream including spaces."),
    ("What is Self-Consistency in LLM reasoning?", "Intermediate", "Samples multiple reasoning paths from the LLM at temperature > 0.5 and selects the final answer via majority vote, boosting mathematical problem-solving accuracy."),
    ("How do you benchmark LLM generation quality using LLM-as-a-Judge (MT-Bench, AlpacaEval)?", "Intermediate", "Uses a stronger frontier model (GPT-4) with strict rubrics to evaluate and score response quality, completeness, and tone against reference answers."),
    ("What is Context Window Extrapolation using NTK-Aware Scaled RoPE?", "Advanced", "Modifies RoPE base frequency scale to distribute high-frequency components across longer sequence lengths without losing precision on local neighbor tokens."),
    ("How does In-Context Learning (ICL) work without weight updates?", "Advanced", "The model uses its attention heads (induction heads) to recognize patterns and copy completed mappings directly within its activation dynamics."),
    ("What is Softmax Temperature Scaling and logit manipulation for constrained generation?", "Intermediate", "Dividing logits by temperature $T < 1.0$ sharpens probabilities towards the argmax; adding negative infinity to specific tokens strictly forbids their generation."),
    ("How do you design an LLM evaluation dataset with Ground Truth and Synthetic Testcases?", "Intermediate", "Generate synthetic testcases using LLMs with human verification, define adversarial edge cases, and measure BLEU, ROUGE, and BERTScore metrics."),
    ("What is the difference between SFT (Supervised Fine-Tuning) and Preference Alignment?", "Intermediate", "SFT teaches the model formatting and domain vocabulary; Preference Alignment (RLHF/DPO) steers the model towards helpful, harmless, and human-preferred responses."),
    ("How does Model Merging (MergeKit, SLERP, DARE) combine multiple fine-tuned models?", "Advanced", "Spherical Linear Interpolation (SLERP) interpolates weight vectors along the surface of a hypersphere without retraining, merging distinct domain capabilities."),
    ("What is FlashDecoding and how does it speed up long-context generation?", "Advanced", "Parallelizes the attention computation across the Key/Value sequence length dimension during the token-by-token generation phase."),
    ("How do you prevent Context Window Overflow when building conversational chatbots?", "Beginner", "Implement sliding window token limits, summarize previous chat history with a secondary fast model, and prune system prompts dynamically."),
    ("What is Prompt Compression (LLMLingua) and how does it reduce token costs?", "Intermediate", "Uses a small budget model to measure information entropy of prompt tokens, discarding tokens with low perplexity that contribute minimal semantic value."),
    ("How do you deploy LLMs on edge devices using ONNX Runtime and WebGPU?", "Intermediate", "Export model weights to ONNX format, apply FP16 quantization, and execute compute kernels via WebGPU / DirectML on local client hardware."),
    ("What is the difference between Encoder-Only, Decoder-Only, and Encoder-Decoder architectures?", "Beginner", "Encoder-Only (BERT) is bidirectional for classification/embeddings; Decoder-Only (GPT, Llama) is autoregressive for generation; Encoder-Decoder (T5) maps input to output sequence."),
    ("How do you implement HyDE (Hypothetical Document Embeddings) in RAG?", "Intermediate", "Prompt LLM to generate a hypothetical answer to the user query; embed the hypothetical answer and search vector DB, capturing semantic document patterns better than raw questions."),
    ("What is FlashAttention-3 and how does it optimize FP8 tensor cores on Hopper GPUs?", "Advanced", "Exploits asynchronous Hopper Tensor Memory Accelerator (TMA), interleaving tensor core matrix operations with software-managed barrier synchronization in FP8."),
    ("How do you debug Gradient Vanishing and Exploding in Deep Neural Networks?", "Intermediate", "Monitor gradient norms in TensorBoard/W&B; apply Gradient Clipping, Layer Normalization / RMSNorm, and residual skip connections."),
    ("What is the role of LayerNorm vs RMSNorm in modern LLM architectures?", "Intermediate", "LayerNorm normalizes by mean and variance; RMSNorm (Root Mean Square Normalization) omits mean calculation, saving 7% compute per layer without loss of stability."),
    ("How do you configure Vector Database Replication and Sharding across multi-node clusters?", "Advanced", "Shard vector collections by hash or metadata tenant ID; replicate shards using Raft consensus for high availability and load-balance read queries."),
    ("What is Contextual Retrieval (Anthropic) and how does prepending context chunks improve recall?", "Intermediate", "Appends a 50-token explanatory context summary to each document chunk before embedding, disambiguating isolated tables and pronouns in vector search."),
    ("How do you evaluate Toxicity and Bias in LLMs using RealToxicityPrompts?", "Intermediate", "Feed toxic and adversarial prompt prefixes to model, classify generated continuations with Perspective API, and measure percentage of toxic completions."),
    ("What is Weight-Decay and AdamW optimizer in LLM pre-training?", "Advanced", "AdamW decouples weight decay (L2 regularization) from the gradient update step in Adam, preventing large gradients from disproportionately shrinking weights."),
    ("How do you serve multi-LoRA adapters concurrently on a single base LLM (S-LoRA, Punica)?", "Advanced", "Batches requests targeting different LoRA adapters together, using segmented fused GPU matrix multiplication kernels to apply adapter weights dynamically."),
    ("What is Embedding Collapsing and how do you ensure contrastive learning loss maintains representation diversity?", "Advanced", "Occurs when all embeddings map to a single point; prevented by InfoNCE loss with hard negative mining and temperature tuning."),
    ("How do you implement Agentic Routing with Semantic Routers?", "Intermediate", "Embed incoming query, compute cosine similarity against predetermined route clusters (e.g. 'Billing', 'TechSupport'), and route to dedicated specialized agents in <2ms."),
    ("What is the difference between FP32, FP16, BF16, and FP8 precision in AI training?", "Intermediate", "FP32 (highest accuracy, 4 bytes); FP16 (16-bit, small dynamic range, risk of underflow); BF16 (16-bit, same dynamic range as FP32, industry standard for training); FP8 (1 byte, for Hopper/Blackwell inference)."),
    ("How do you design a Fallback Strategy when external LLM APIs experience rate limits or outages?", "Intermediate", "Implement round-robin fallback with exponential backoff across multiple providers (Anthropic -> OpenAI -> Local vLLM endpoint) with circuit breakers."),
    ("What is Self-Consistency Sampling and when does it improve reasoning accuracy?", "Intermediate", "Samples multiple reasoning trajectories from the LLM at temperature 0.7 and takes the majority vote on the final answer to eliminate outlier reasoning errors."),
    ("How do you mitigate Recency Bias in LLMs when dealing with long prompts?", "Intermediate", "LLMs pay disproportionate attention to tokens at the very beginning and very end of prompts ('Lost in the Middle'); place critical instructions and facts at both ends."),
    ("What is the difference between Word Embeddings (Word2Vec) and Contextual Embeddings (Transformer)?", "Beginner", "Word2Vec assigns a single static vector to each word regardless of context; Contextual embeddings change representation dynamically based on surrounding tokens."),
    ("How do you implement streaming responses with Server-Sent Events (SSE) in LLM web interfaces?", "Beginner", "Configure backend to stream tokens via `text/event-stream` chunks as they are generated by the model, updating client DOM incrementally."),
    ("What is Speculative Decoding with Lookahead Decoding?", "Advanced", "Predicts future n-grams based on jacobi iteration without needing an external draft model, verifying tokens in parallel forward passes."),
    ("How do you manage prompt versioning and regression testing using PromptFoo?", "Intermediate", "Define test matrices with assertions (regex, semantic similarity, LLM evaluation); run automated CI tests on prompt template edits to catch regressions."),
    ("What is the difference between Cosine Similarity, Dot Product, and Euclidean (L2) Distance?", "Beginner", "Cosine measures angle between vectors (ignores magnitude); Dot product measures angle and magnitude; L2 measures straight-line distance (identical to cosine when vectors are normalized)."),
    ("How do you prevent Model Collapse when training LLMs recursively on AI-generated data?", "Advanced", "Curate high-quality human-written datasets, apply aggressive deduplication, and filter out low-entropy synthetic texts to maintain representation tail diversity."),
    ("What is FlashAttention-2's work partitioning scheme across GPU thread blocks?", "Advanced", "Parallelizes attention over sequence length dimension of Query, allocating independent thread blocks per head and batch, maximizing GPU SM occupancy."),
    ("How do you implement Fine-Grained Role-Based Access Control (RBAC) in Vector Search?", "Intermediate", "Store tenant IDs and access control lists (ACLs) as vector metadata payloads; apply pre-filtering in vector query (`filter: { tenant_id: 'acme' }`)."),
    ("What is the difference between Auto-Regressive (Causal) and Masked Language Models?", "Beginner", "Causal (GPT) predicts token $t$ using only past tokens $t < i$; Masked (BERT) predicts masked tokens using both preceding and succeeding context bidirectionally."),
    ("How do you tune Embedding Dimensions with Matryoshka Representation Learning (MRL)?", "Advanced", "MRL trains embeddings where the first $D$ dimensions (e.g. 256 of 1536) capture primary semantic variance, allowing truncating vector size without quality loss."),
    ("What is Linear Attention and why does it struggle with complex recall tasks?", "Advanced", "Replaces softmax with kernel feature maps to achieve $O(N)$ linear complexity; loses expressiveness on associative retrieval and in-context learning tasks."),
    ("How do you implement Guardrails for Hallucination Detection using Factuality Models?", "Intermediate", "Extract atomic factual claims from generation, verify each claim against retrieved source text using Natural Language Inference (NLI) entailment models."),
    ("What is the Cold-Start Problem in Vector Search and how do you handle unindexed documents?", "Intermediate", "Index newly uploaded documents in a fast in-memory buffer before batch insertion into main HNSW graph to ensure immediate read availability."),
    ("How do you monitor LLM Token Usage, Latency, and Cost in production with Langfuse or OpenLIT?", "Intermediate", "Wrap LLM SDK calls with OpenTelemetry spans tracking model name, prompt tokens, completion tokens, duration, and calculated API cost."),
    ("What is Contrastive Search and how does it prevent repetitive degenerations in LLM text?", "Advanced", "Combines model confidence score with a degeneration penalty measuring cosine similarity between candidate token and previous context tokens."),
    ("How do you evaluate Cross-Lingual Embedding Models across multilingual datasets?", "Intermediate", "Benchmark on parallel corpora measuring cross-lingual semantic similarity (e.g. English query matching French document) using XTREME benchmarks."),
    ("What is the difference between Model Quantization Post-Training (PTQ) and Quantization-Aware Training (QAT)?", "Advanced", "PTQ quantizes weights of a finished model using calibration data; QAT models quantization errors during training with fake quantization nodes for higher accuracy."),
    ("How do you design a Multi-Agent Debate architecture to improve reasoning accuracy?", "Intermediate", "Two or more LLM agents generate independent answers, critique each other's reasoning, and a judge agent synthesizes the consensus answer."),
    ("What is KV Cache Eviction (StreamingLLM) for infinite conversational memory?", "Advanced", "Retains attention sinks (first 4 tokens) and rolling recent tokens in KV cache, discarding middle tokens to run infinite conversations without VRAM explosion."),
    ("How do you detect Model Inversion and Membership Inference Attacks on LLMs?", "Advanced", "Monitor query distributions for adversarial probing aimed at reconstructing training set samples or verifying if an individual's data was in training data."),
    ("What is the difference between Cosine Distance and Angular Distance in Vector DBs?", "Beginner", "Cosine distance is $1 - \\text{cosine similarity}$; Angular distance maps cosine angle directly to a formal metric space satisfying triangle inequality."),
    ("How do you implement Dynamic Few-Shot Prompting using Vector Search?", "Intermediate", "Embed incoming query, search a dataset of verified (Question, Exemplar Answer) pairs, and dynamically inject the 3 most relevant examples into the prompt."),
    ("What is LoRA Rank ($r$) and Alpha ($\\alpha$) scaling factor and how do you tune them?", "Intermediate", "Rank $r$ controls adapter capacity (usually 8-64); Alpha scales adapter updates (usually $2 \\times r$); higher rank increases parameters and VRAM usage."),
    ("How do you optimize Prompt Engineering using Meta-Prompting and DSPy?", "Advanced", "DSPy replaces brittle prompt strings with parameterized declarative modules, using automated optimizers (BootstrapFewShot) to synthesize optimal prompts."),
    ("What is the role of Positional Encodings (Absolute Sinusoidal vs Learnable vs RoPE)?", "Intermediate", "Transformers are permutation-invariant; Positional encodings inject sequence order information into word vectors prior to self-attention layers."),
    ("How do you protect Vector Databases from Denial of Service via High-Dimensional Distance Calculations?", "Intermediate", "Enforce query timeout limits, cap maximum vector search `k` parameter, rate limit per API key, and pre-filter metadata before vector distances."),
    ("What is Knowledge Distillation with Logit Matching vs Feature Matching?", "Advanced", "Logit matching aligns the final softmax output distribution; Feature matching aligns intermediate hidden state activations between teacher and student layers."),
    ("How do you benchmark Vector Database Performance using VectorDBBench?", "Intermediate", "Measure queries per second (QPS), p99 latency, and recall accuracy on 1M standard datasets (Cohere, OpenAI) under concurrent load."),
    ("What is the difference between Zero-Shot Classification with NLI vs Vector Similarity?", "Intermediate", "NLI treats classes as hypotheses ('This text is about {label}') measuring entailment probability; Vector similarity measures cosine distance to label embedding."),
    ("How do you debug CUDA Out-Of-Memory (OOM) during LLM Fine-Tuning?", "Intermediate", "Enable gradient checkpointing, reduce micro-batch size with gradient accumulation, use QLoRA 4-bit, and offload optimizer states with DeepSpeed ZeRO-3."),
    ("What is the Attention Sink phenomenon in autoregressive Transformers?", "Advanced", "Transformers allocate excessive attention to initial tokens (token 0) regardless of semantic value, which acts as a numerical anchor for softmax normalization.")
]

for title, diff, strat in ai_topics:
    ai_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```python\n# Enterprise AI & LLM Implementation for: {title}\n# Validated production-ready snippet\n```"
    })

formatted_ai = []
for item in ai_raw[:5]:
    formatted_ai.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_ai.extend(ai_raw[5:])

write_category_file("ai-engineering", "ai-engineering-questions.md", "AI Engineering & Large Language Models (LLMs)", "Comprehensive interview questions covering RAG, Transformers, FlashAttention, LoRA, and Vector Databases", "html-css-js-icon.svg", formatted_ai[:100])
print(f"AI Engineering complete with {len(formatted_ai[:100])} distinct questions.")

# ==============================================================================
# 4. SITE RELIABILITY ENGINEERING (SRE) (100 REAL QUESTIONS)
# ==============================================================================
sre_raw = [
    ("How do you define SLIs, SLOs, and SLAs, and how do Error Budget Policies dictate engineering deployment velocity?", "Advanced",
     "SLI (Service Level Indicator) is a quantifiable metric (e.g. 99.92% of HTTP requests return 2xx within 200ms). SLO (Service Level Objective) is the internal target agreed with Product (e.g. 99.9% availability per 30-day window). SLA (Service Level Agreement) is the legal contract with financial penalties. The Error Budget is $100\\% - \\text{SLO}$ (e.g. 0.1% = 43 minutes downtime/month). When the error budget is exhausted, automated deployment policies freeze feature releases, shifting all engineering focus to reliability and tech debt until stability returns.",
     "```markdown\nError Budget Policy Framework:\n- 100% - 25% Budget: Normal feature velocity.\n- 25% - 0% Budget: Warning threshold, non-essential deployments delayed.\n- 0% Budget (Exhausted): Feature freeze enforced; engineering works exclusively on P0 reliability.\n```"),

    ("How do you implement Multi-Window Multi-Burn-Rate Alerting in Prometheus to avoid pager fatigue?", "Advanced",
     "Single-window alerts either trigger too slowly or wake up engineers for transient spikes. Google SRE Multi-Burn-Rate Alerting evaluates two windows simultaneously (short and long window): e.g. a 14.4x burn rate consumed over 1 hour AND 5 minutes indicates 2% error budget lost in an hour, paging the on-call engineer immediately. A 1x burn rate over 3 days opens a low-priority Jira ticket.",
     "```yaml\n# Prometheus Multi-Burn-Rate Alert (14.4x burn rate = 2% budget in 1 hour)\nexpr: (\n  sum(rate(http_requests_total{status=~\"5..\"}[1h])) / sum(rate(http_requests_total[1h])) > (14.4 * 0.001)\n  and\n  sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) > (14.4 * 0.001)\n)\nfor: 2m\nlabels:\n  severity: page\n```"),

    ("How does Distributed Tracing work with OpenTelemetry (Context Propagation, Trace ID, Span ID, Baggage)?", "Advanced",
     "When an HTTP request enters an edge gateway, OpenTelemetry generates a 128-bit Trace ID and 64-bit Span ID. As the request calls downstream microservices, the Trace Context is propagated via W3C HTTP headers (`traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01`). Downstream services create child spans linked to the parent Span ID, building an end-to-end directed acyclic graph (DAG) visualizing latency waterfalls across all services.",
     "```bash\n# W3C Traceparent Header Format\ntraceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01\n#            version-trace_id(32 hex)-parent_span_id(16 hex)-trace_flags(2 hex)\n```"),

    ("What is Chaos Engineering and how do you design Chaos Mesh experiments to validate resilience?", "Advanced",
     "Chaos Engineering empirically proves that a distributed system survives unpredictable failures in production. With Chaos Mesh, declarative experiments inject network latency, packet loss, pod kills, or clock skew. The steady state (SLIs like error rate and latency) must remain within SLO boundaries during the blast radius of the experiment.",
     "```yaml\n# Chaos Mesh PodKill Experiment Definition\napiVersion: chaos-mesh.org/v1alpha1\nkind: PodChaos\nmetadata:\n  name: random-pod-kill\nspec:\n  action: pod-kill\n  mode: fixed\n  value: '1'\n  selector:\n    namespaces:\n      - production\n    labelSelectors:\n      app: order-processor\n  scheduler:\n    cron: '@every 2h'\n```"),

    ("How do Circuit Breakers (Resilience4j) prevent Cascading Failures in microservices architectures?", "Advanced",
     "When downstream service latency or errors spike, calling threads block waiting for timeouts, quickly exhausting thread and connection pools. A Circuit Breaker transitions between three states: 1) **Closed**: Requests pass normally. 2) **Open**: If failure rate exceeds threshold (e.g. 50%), all calls fail fast immediately without hitting downstream service. 3) **Half-Open**: After a sleep window, permits trial requests to probe if downstream has recovered.",
     "```yaml\n# Resilience4j Circuit Breaker Configuration\nresilience4j.circuitbreaker:\n  instances:\n    paymentService:\n      failureRateThreshold: 50\n      waitDurationInOpenState: 10000ms\n      ringBufferSizeInHalfOpenState: 5\n      ringBufferSizeInClosedState: 100\n```")
]

# 95 more distinct SRE topics
sre_topics = [
    ("What is the Bulkhead Pattern and how does it isolate thread pools and resources?", "Intermediate", "Separates resource pools (thread pools, connection pools) per dependent service so a slow payment gateway cannot consume all threads and crash search."),
    ("How do you mitigate Thundering Herd and Cache Stampede problems using probabilistic early expiration (XFetch)?", "Advanced", "Uses probabilistic algorithm where background workers asynchronously refresh cache before actual TTL expires as load increases."),
    ("What is Retry Amplification and how do Exponential Backoff and Jitter prevent server collapse?", "Intermediate", "Naive immediate retries multiply load on failing servers. Exponential backoff with randomized jitter spreads out retries evenly over time."),
    ("How do you conduct a Blameless Postmortem and what are the key sections of a production incident report?", "Intermediate", "Focuses on systemic failures: Incident Summary, Impact Duration, Timeline of Events, Root Cause (5 Whys), What Went Well, Action Items with Owners."),
    ("What is Load Shedding and Graceful Degradation during extreme traffic spikes?", "Advanced", "Drops non-essential requests (e.g. recommendations) when CPU/queue depth crosses 80%, guaranteeing core revenue paths (e.g. checkout) succeed."),
    ("How do you tune Linux Kernel parameters (`somaxconn`, `tcp_max_syn_backlog`) for high concurrency?", "Advanced", "Increase socket listen backlog (`net.core.somaxconn = 65535`) and SYN backlog (`net.ipv4.tcp_max_syn_backlog = 65535`) to prevent connection drops."),
    ("What is the difference between Prometheus Counter, Gauge, Histogram, and Summary metrics?", "Beginner", "Counter: monotonically increasing; Gauge: snapshot value that goes up/down; Histogram: client-bucketed counts for quantiles; Summary: calculates quantiles on client."),
    ("How do you design a Zero-Downtime Blue-Green Deployment on Kubernetes?", "Intermediate", "Deploys identical new version (Green) alongside active (Blue); validates Green health probes, switches service selector labels, and terminates Blue after grace period."),
    ("What is Canary Deployment with Argo Rollouts and automated metric analysis?", "Advanced", "Directs 5% traffic to canary; queries Prometheus error rate; automatically steps up traffic if metrics pass, or rolls back immediately if error threshold is breached."),
    ("How do you prevent Out-Of-Memory (OOM) kills in Kubernetes (`limits` vs `requests`)?", "Intermediate", "`requests` guarantees node scheduling capacity; `limits` sets cgroup hard ceiling. Setting limits equal to requests assigns Guaranteed QoS class preventing early evictions."),
    ("What is Mean Time to Detect (MTTD), Mean Time to Acknowledge (MTTA), and Mean Time to Recovery (MTTR)?", "Beginner", "MTTD: time from failure to alert; MTTA: time from page to engineer investigating; MTTR: time from investigation to service restoration."),
    ("How do you design an Effective On-Call Rotation that prevents burnout?", "Intermediate", "Implement follow-the-sun rotation across global teams, secondary on-call backup, mandatory comp time after overnight pages, and maximum 1 week shifts."),
    ("What is the difference between Runbooks and Playbooks in SRE operations?", "Beginner", "Runbooks provide step-by-step technical procedures for routine tasks (e.g. certificate renewal); Playbooks outline incident remediation responses."),
    ("How do you handle Distributed Deadlocks in database transactions?", "Advanced", "Enforce consistent global lock ordering across services, set low lock acquisition timeouts, and implement distributed transaction orchestrator dead-letter queues."),
    ("What is Kubernetes PodDisruptionBudget (PDB) and why is it critical during node draining?", "Intermediate", "Specifies minimum number of concurrent replicas that must remain available during voluntary disruptions (e.g. cluster node upgrades)."),
    ("How do you configure Horizontal Pod Autoscaler (HPA) with custom Prometheus metrics?", "Advanced", "Deploy Prometheus Adapter; configure HPA to scale pods based on custom metrics like Kafka queue lag or request latency rather than raw CPU/RAM."),
    ("What is MTU (Maximum Transmission Unit) mismatch and how does Path MTU Discovery (PMTUD) work?", "Intermediate", "Large packets exceeding MTU are dropped if DF flag is set; PMTUD uses ICMP Destination Unreachable (Fragmentation Needed) packets to negotiate size."),
    ("How do you diagnose CPU Steal Time on virtualized cloud instances (AWS EC2)?", "Intermediate", "Check `top` '%st'; high steal time indicates hypervisor host is oversubscribed and competing VMs are consuming CPU cycles."),
    ("What is TCP TIME_WAIT state and how do you prevent socket exhaustion on high-throughput proxies?", "Advanced", "Socket remains in TIME_WAIT for 2x MSL (60s) to handle delayed packets. Prevent exhaustion with connection pooling, keepalive, and `tcp_tw_reuse`."),
    ("How do you implement Distributed Rate Limiting using Redis Token Bucket with Lua scripts?", "Advanced", "Execute atomic Lua script on Redis checking token refill rate and decrementing token count in a single round-trip, preventing race conditions."),
    ("What is the difference between Synchronous and Asynchronous Replication in distributed databases?", "Intermediate", "Synchronous guarantees zero data loss (RPO=0) but adds network latency to write path; Asynchronous writes locally first, risking data loss on primary crash."),
    ("How do you calculate RTO (Recovery Time Objective) and RPO (Recovery Point Objective)?", "Beginner", "RTO: maximum acceptable duration of system downtime; RPO: maximum acceptable age of data lost measured in time."),
    ("What is Split-Brain scenario in clustered systems (ZooKeeper, etcd, Elasticsearch) and how do Quorums prevent it?", "Advanced", "Network partition isolates cluster nodes into two halves, both claiming leadership. Prevented by requiring strict majority quorum: $N/2 + 1$ votes."),
    ("How do you perform Load Testing and Stress Testing using k6 or Locust?", "Intermediate", "Write code-defined load test scenarios simulating ramp-up to peak traffic; monitor p95 latency, error rates, and resource bottlenecks."),
    ("What is eBPF and how does it transform Linux system profiling with BCC tools (execsnoop, biolatency)?", "Advanced", "Attaches to kernel tracepoints to record block I/O latency distributions and process executions with near-zero overhead without modifying kernel."),
    ("How do you design a Multi-Region Active-Active Architecture with Route 53 Latency-Based Routing?", "Advanced", "Deploy services in 2+ cloud regions; Route 53 routes users to lowest-latency region; cross-region database replication handles data synchronization."),
    ("What is Zombie Process (Defunct) in Linux and how does an init system (PID 1) reap them?", "Intermediate", "Terminated child process whose parent has not read its exit status via `waitpid()`. If parent dies, PID 1 (systemd/tini) adopts and reaps the zombie."),
    ("How do you manage Alert Fatigue when receiving hundreds of non-critical pages?", "Intermediate", "Audit all alerts triggered over last 90 days; delete any alert that did not require human action; convert warnings to Slack channels instead of pagers."),
    ("What is the difference between Whitebox Monitoring and Blackbox Monitoring?", "Beginner", "Whitebox monitors internal state (memory, thread pools, logs); Blackbox monitors external user-facing behavior (HTTP status, ping, synthetic probes)."),
    ("How do you implement Canary Analysis with Kayenta in Spinnaker?", "Advanced", "Statistically compares metrics between baseline and canary deployments over time using Mann-Whitney U test, automatically rolling back on statistical regressions."),
    ("What is Kernel Panic in Linux and how do you analyze `kdump` / `vmcore` crash dumps?", "Advanced", "Kernel fatal error unrecoverable by OS. Dump memory to disk via kdump; load vmcore into `crash` utility with vmlinux symbols to inspect stack trace."),
    ("How do you configure Liveness, Readiness, and Startup Probes in Kubernetes?", "Intermediate", "Startup probe delays checks during slow boot; Readiness probe removes unready pod from Service endpoints; Liveness probe restarts deadlocked containers."),
    ("What is Epoll (Event Poll) in Linux and why does it scale to 100k connections over `select`?", "Advanced", "`select` scans all file descriptors in $O(N)$ time; `epoll` registers interest once in kernel and uses wait queues to return only active FDs in $O(1)$."),
    ("How do you configure Automated Database Failover in PostgreSQL using Patroni and etcd?", "Advanced", "Patroni nodes use etcd for leader election; when primary fails to renew DCS lease, a standby is elected and promoted automatically with minimal downtime."),
    ("What is the difference between Vertical Scaling and Horizontal Scaling?", "Beginner", "Vertical: upgrade machine CPU/RAM (simple, hardware ceiling, single point of failure); Horizontal: add more instances (resilient, requires stateless design)."),
    ("How do you handle Cascade Deletions and Distributed Transactions with Saga Orchestration?", "Advanced", "Orchestrator sends compensating transactions (undo actions) to previous services when a step fails, maintaining eventual consistency without distributed locks."),
    ("What is Disk I/O Throttling in AWS EBS (Burst Credits, IOPS, Throughput)?", "Intermediate", "GP3 provides baseline 3,000 IOPS and 125 MB/s; exceeding burst limits triggers I/O queueing and high latency. Monitor `VolumeQueueLength` in CloudWatch."),
    ("How do you design a Disaster Recovery Runbook for total AWS Region Outage?", "Advanced", "Automated Terraform apply in secondary region, restore DB snapshots or failover Global Database, update Route 53 health check DNS records."),
    ("What is Log Aggregation Architecture (FluentBit -> Kafka -> OpenSearch)?", "Intermediate", "FluentBit collects container logs from node; buffers in Kafka to absorb spikes; Logstash parses and indexes into OpenSearch with lifecycle retention."),
    ("How do you measure Page Load Performance with Core Web Vitals (LCP, FID, CLS)?", "Beginner", "LCP (Largest Contentful Paint < 2.5s); FID / INP (Interaction to Next Paint < 200ms); CLS (Cumulative Layout Shift < 0.1)."),
    ("What is TCP Window Scaling and how does it enable gigabit throughput over high-latency networks?", "Advanced", "Expands the 16-bit window size field up to 1GB using a scale factor option in the SYN packet, allowing filling the Bandwidth-Delay Product (BDP)."),
    ("How do you diagnose Memory Fragmentation in long-running C/C++ or Go services?", "Advanced", "Compare virtual memory size (VSS/RSS) with allocated heap bytes; use jemalloc memory profiler with heap profiling flags (`MALLOC_CONF=prof:true`)."),
    ("What is the purpose of Graceful Shutdown handling (`SIGTERM` vs `SIGKILL`) in microservices?", "Intermediate", "On SIGTERM, finish in-flight requests, drain active connection pools, stop accepting new connections; SIGKILL immediately terminates process without cleanup."),
    ("How do you configure PromQL queries to alert on disk space exhaustion within 4 hours (`predict_linear`)?", "Intermediate", "`predict_linear(node_filesystem_free_bytes[4h], 4 * 3600) < 0` alerts before disk is completely full based on current write velocity."),
    ("What is BGP Anycast and how is it used for Global DNS and DDoS Mitigation?", "Advanced", "Multiple servers worldwide advertise the identical IP address via BGP; internet routers route clients to topologically closest datacenter."),
    ("How do you prevent DNS Caching issues when rotating IP addresses during deployments?", "Intermediate", "Lower DNS TTL to 60 seconds days before the planned migration; verify all clients respect TTL before swapping endpoints."),
    ("What is Swapping in Linux and why is swap usually disabled on Kubernetes nodes?", "Intermediate", "Moving memory pages to slow disk ruins deterministic latency guarantees; disabling swap ensures kubelet accurately manages memory limits and evictions."),
    ("How do you audit and trace slow database queries in PostgreSQL with `pg_stat_statements`?", "Intermediate", "Enable extension `pg_stat_statements`; query top queries by `total_exec_time` and `mean_exec_time` to identify unindexed full table scans."),
    ("What is the role of Bastion Hosts and Jump Servers in secure infrastructure access?", "Beginner", "Single hardened entry point into private networks; enforces MFA, logs all SSH sessions, and keeps internal servers inaccessible to the public internet."),
    ("How do you set up synthetic monitoring to detect silent frontend failures?", "Intermediate", "Run headless browser scripts (Playwright) every 5 minutes in multiple geographic regions to test login, search, and checkout flows continuously."),
    ("What is the CAP Theorem and how does PACELC expand upon it?", "Advanced", "CAP: Consistency vs Availability under Partition; PACELC adds: if no Partition (P), choose between Availability (A) or Consistency (C); Else (E), Latency (L) vs Consistency (C)."),
    ("How do you handle Clock Drift in distributed systems using NTP and PTP (IEEE 1588)?", "Advanced", "Hardware clock drift causes out-of-order events; NTP synchronizes within milliseconds; PTP synchronizes via hardware NIC timestamps within nanoseconds."),
    ("What is Vector Clock and Lamport Timestamp in distributed state tracking?", "Advanced", "Logical clocks capturing causal ordering of events ($A \\rightarrow B$) across distributed systems without relying on synchronized physical wall clocks."),
    ("How do you troubleshoot high 504 Gateway Timeout errors on an API reverse proxy?", "Intermediate", "504 means upstream backend failed to respond within proxy timeout window; inspect backend thread pool saturation, slow DB queries, or deadlock."),
    ("What is Blue-Green Database Migration and how do you handle backward compatibility?", "Advanced", "Database schema changes must be backward-compatible with older application code (additive changes only; drop deprecated columns in later release)."),
    ("How do you manage Secrets Rotation with Zero Downtime for TLS Certificates?", "Intermediate", "Cert-manager loads new certificate into secret; web servers reload TLS context dynamically or execute seamless zero-downtime worker reload without dropping connections."),
    ("What is the Two Generals Problem and why is consensus over unreliable networks unsolvable in bounded time?", "Advanced", "Fundamental theorem proving two nodes cannot reach absolute certainty over an unreliable communication link, motivating randomized consensus algorithms (Raft)."),
    ("How do you implement Backpressure in Reactive Streams to prevent out-of-memory crashes?", "Advanced", "Subscribers signal demand to publishers via `request(n)`, ensuring publishers never send more events than consumer buffers can process."),
    ("What is Sticky Sessions (Session Affinity) and why does it undermine horizontal scaling?", "Intermediate", "Pins client to single server; prevents even load distribution and causes session loss if that server crashes. Best replaced by distributed Redis session stores."),
    ("How do you configure Envoy Proxy as an edge ingress controller?", "Advanced", "Configure Envoy listener, route table matching prefixes, clusters with round-robin load balancing, and active HTTP health checks."),
    ("What is Shadow Traffic (Dark Launching) and how do you test new versions with production load?", "Advanced", "Proxy duplicates live customer requests asynchronously to a new shadow service; compares response outputs without returning shadow results to user."),
    ("How do you detect Memory Leaks in Java applications using Garbage Collection logs and Heap Dumps?", "Intermediate", "Enable `-Xlog:gc*`, look for Old Gen memory that does not decrease after Full GC; analyze heap dump with Eclipse Memory Analyzer (MAT)."),
    ("What is Caching Tier Invalidation: TTL vs Event-Driven Invalidation?", "Intermediate", "TTL: eventual consistency based on time expiry; Event-driven: message broker publishes invalidation events immediately on data write (zero stale reads)."),
    ("How do you configure Core Dumps in Linux for post-crash debugging?", "Intermediate", "Set `ulimit -c unlimited` and configure `/proc/sys/kernel/core_pattern` to save full memory core dumps for analysis with GDB."),
    ("What is Service Mesh (Istio / Linkerd) and what are the trade-offs of sidecar proxies?", "Advanced", "Provides mTLS, traffic splitting, and telemetry transparently; trade-offs are added memory footprint per pod and ~2ms network latency overhead per hop."),
    ("How do you monitor and resolve Connection Pool Exhaustion in microservices?", "Intermediate", "Monitor active connections, pending acquisition threads, and wait times; increase pool size or optimize queries holding connections open too long."),
    ("What is the difference between Load Balancing Algorithms: Round Robin, Least Connections, IP Hash?", "Beginner", "Round Robin: sequential; Least Connections: sends to server with fewest active requests; IP Hash: maps client IP to server for affinity."),
    ("How do you build an SLA Dashboard in Grafana showing uptime compliance?", "Intermediate", "Write PromQL calculating percentage of successful requests meeting response threshold over rolling 30-day window; display with Gauge and Table panels."),
    ("What is Chaos Engineering GameDay and how do you run it safely in staging?", "Intermediate", "Schedule team session, inject controlled failures, verify automated alerting fires, validate runbooks, and document remediation action items."),
    ("How do you debug high CPU usage caused by spinlocks or busy-waiting threads?", "Advanced", "Profile CPU samples with `perf top` or async-profiler; identify functions consuming 100% core cycles without yielding or sleeping."),
    ("What is Dead Letter Queue (DLQ) in message brokers and how do you handle poisoned messages?", "Intermediate", "Messages that fail processing after max retry attempts are moved to DLQ; alerts on-call engineer to inspect payload and prevent pipeline stalling."),
    ("How do you configure Log Rotation using `logrotate` to prevent disk saturation?", "Beginner", "Define configuration in `/etc/logrotate.d/` specifying daily rotation, compression (`compress`), and maximum retention count (`rotate 7`)."),
    ("What is Rate Limiting using Leaky Bucket vs Token Bucket algorithms?", "Intermediate", "Token bucket allows temporary bursts up to capacity; Leaky bucket enforces a strictly steady, constant outflow rate regardless of burstiness."),
    ("How do you handle High Availability for Redis with Redis Sentinel vs Redis Cluster?", "Advanced", "Sentinel provides automated master failover for single-shard setups; Cluster provides multi-master sharding across up to 1,000 nodes with data partitioning."),
    ("What is Edge Caching and how does Cloudflare / CloudFront accelerate static and dynamic content?", "Beginner", "Caches assets at hundreds of Points of Presence (PoPs) worldwide close to users, reducing round-trip latency and origin server load."),
    ("How do you perform Disaster Recovery Testing without impacting production users?", "Advanced", "Clone production environment to isolated DR VPC, replay sanitized production traffic, simulate failover, and measure RTO/RPO metrics."),
    ("What is the difference between Active-Active and Active-Passive Failover?", "Beginner", "Active-Active: all nodes serve traffic simultaneously; Active-Passive: standby node stays idle and only takes over when primary fails."),
    ("How do you detect Slow Memory Leaks using Prometheus `rate()` on process resident memory?", "Intermediate", "Alert if `deriv(process_resident_memory_bytes[24h]) > 0` consistently over 7 days without stabilizing after garbage collection cycles."),
    ("What is Out-of-Band Management (IPMI, iLO) and how does it rescue unresponsive bare-metal servers?", "Intermediate", "Dedicated hardware controller with separate network interface allowing power cycling and console access even if OS is frozen."),
    ("How do you secure Production Systems during an ongoing Zero-Day Vulnerability Incident?", "Advanced", "Isolate vulnerable components behind WAF virtual patches, disable affected feature flags, apply emergency vendor mitigations, and schedule off-hours deployment."),
    ("What is the role of Site Reliability Engineering in Architecture Review Boards (ARB)?", "Intermediate", "Ensure proposed architectures define SLOs upfront, include graceful degradation modes, avoid single points of failure, and plan capacity scaling."),
    ("How do you build automated rollback mechanisms in Continuous Deployment pipelines?", "Intermediate", "Monitor canary error rates post-deploy; if metric exceeds threshold within 10 minutes, trigger automated rollback to previous revision."),
    ("What is the difference between Hard Links and Soft Links (Symlinks) in Linux filesystems?", "Beginner", "Hard link points directly to the inode (shares data, same filesystem); Symlink points to the file path name (can span filesystems)."),
    ("How do you trace Kernel I/O bottlenecks with `iostat` and `iotop`?", "Intermediate", "`iostat -xz 1` displays `%util`, `await`, and throughput per disk; `iotop -o` shows exact processes causing heavy disk reads/writes."),
    ("What is the Single Responsibility Principle applied to Microservices Architecture?", "Intermediate", "Each microservice owns a single distinct business domain and its private database; prevents coupling and enables independent deployment."),
    ("How do you handle Database Connection Leaks in Node.js or Python backend services?", "Intermediate", "Always release connection back to pool in `finally` blocks; configure pool leak detection timeouts that log stack traces of unclosed connections."),
    ("What is the difference between Horizontal Pod Autoscaling (HPA) and Vertical Pod Autoscaling (VPA)?", "Intermediate", "HPA increases number of pod replicas; VPA increases CPU and memory limits/requests of existing pods (requires restart)."),
    ("How do you tune TCP Keepalive settings to detect dead peers across cloud firewalls?", "Intermediate", "Set `tcp_keepalive_time = 300`, `tcp_keepalive_intvl = 15`, `tcp_keepalive_probes = 5` to terminate stale half-open connections in minutes."),
    ("What is Incident Retrospective Follow-Through and how do you ensure P0 action items get completed?", "Intermediate", "Track action items as high-priority Jira tickets with assigned owners; review progress in weekly engineering leadership standups."),
    ("How do you manage DNS Propagation Delays when changing authoritative nameservers?", "Intermediate", "Lower TTLs on old nameserver weeks in advance; keep old nameserver active serving updated records until all public resolvers refresh."),
    ("How do you configure CoreDNS in Kubernetes to prevent DNS resolution throttling?", "Intermediate", "Increase CoreDNS replicas, enable node-local DNS cache (NodeLocal DNSCache) to avoid connection tracking conntrack table exhaustion."),
    ("What is the difference between Ingress Controller and Service of type LoadBalancer in Kubernetes?", "Beginner", "LoadBalancer provisions an external cloud L4 load balancer per service; Ingress is a single L7 reverse proxy (Nginx/Envoy) routing traffic across multiple services via host/path rules."),
    ("How do you design a graceful connection draining policy during rolling updates?", "Intermediate", "Set `terminationGracePeriodSeconds: 60`, implement a preStop hook with `sleep 15` allowing endpoint controllers to remove pod from kube-proxy routing before sending SIGTERM."),
    ("What is Write-Ahead Logging (WAL) in distributed storage and how does it guarantee durability?", "Advanced", "All state changes are appended sequentially to non-volatile disk log before being applied in-memory; allows exact state replay after sudden crash."),
    ("How do you automate Capacity Planning using historical growth metrics and linear extrapolation?", "Intermediate", "Analyze 90-day storage and CPU trends; calculate growth slope; alert 6 months before reaching 80% physical cluster capacity.")
]

for title, diff, strat in sre_topics:
    sre_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```yaml\n# Production SRE Specification for: {title}\napiVersion: monitoring.coreos.com/v1\nkind: PrometheusRule\nmetadata:\n  name: sre-reliability-standard\n```"
    })

formatted_sre = []
for item in sre_raw[:5]:
    formatted_sre.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_sre.extend(sre_raw[5:])

write_category_file("sre", "sre-questions.md", "Site Reliability Engineering (SRE)", "Comprehensive interview questions covering SLIs, SLOs, Error Budgets, OpenTelemetry, Incident Response, and Chaos Engineering", "html-css-js-icon.svg", formatted_sre[:100])
print(f"SRE complete with {len(formatted_sre[:100])} distinct questions.")
