import os
import sys
sys.path.append(os.path.dirname(__file__))
from writer_helper import write_category_file

# ==============================================================================
# 2. DEVSECOPS & THREAT MODELING (100 REAL QUESTIONS)
# ==============================================================================
devsecops_raw = [
    ("How do you implement the STRIDE Threat Modeling Framework in an enterprise microservices architecture?", "Advanced",
     "STRIDE categorizes threats into 6 dimensions: Spoofing (mitigated by mTLS & RS256 JWTs), Tampering (TLS 1.3 & HMAC), Repudiation (WORM audit trails), Information Disclosure (least privilege IAM & encryption at rest), Denial of Service (rate limiters & circuit breakers), and Elevation of Privilege (RBAC/ABAC & rootless containers).",
     "```markdown\nSTRIDE Threat Model Mapping:\n- Spoofing -> SPIFFE/SPIRE Workload Identities\n- Tampering -> SHA-256 Signatures & Mutual TLS\n- Repudiation -> Append-only Immutable S3 CloudTrail Logs\n- Info Disclosure -> KMS Envelope Encryption (AES-256-GCM)\n- DoS -> Token Bucket WAF Rate Limiting\n- Elevation -> Linux Kernel Capabilities Dropping (cap_drop: ALL)\n```"),

    ("How do you design a Zero-Trust Security Architecture for Kubernetes and container workloads?", "Advanced",
     "Enforce 'Never Trust, Always Verify': Implement SPIFFE/SPIRE for cryptographic pod identity, Istio service mesh for mutual TLS encryption between all pods, default-deny Kubernetes NetworkPolicies, and admission controllers enforcing non-root container execution.",
     "```yaml\n# Kubernetes Zero-Trust NetworkPolicy (Default Deny)\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: default-deny-all\nspec:\n  podSelector: {}\n  policyTypes:\n    - Ingress\n    - Egress\n```"),

    ("How do you secure CI/CD pipelines against Software Supply Chain Attacks (SLSA Level 3/4)?", "Advanced",
     "Enforce hermetic builds, generate Software Bills of Materials (SBOM) using Syft/CycloneDX, sign container images and provenance metadata cryptographically using Sigstore Cosign with keyless OIDC, and enforce admission verification in Kubernetes clusters.",
     "```bash\n# Cryptographic Container Image Signing with Cosign\ncosign sign --yes ghcr.io/company/core-service@sha256:abc1234...\ncosign verify --certificate-identity devops@company.com ghcr.io/company/core-service:v1.0\n```"),

    ("What is the difference between SAST, DAST, IAST, and RASP in the DevSecOps lifecycle?", "Intermediate",
     "SAST analyzes static source code without execution; DAST tests running applications from the outside like a black-box attacker; IAST uses runtime instrumentation agents inside the app to detect vulnerabilities during test execution; RASP resides in the production runtime to actively block exploit payloads.",
     "```markdown\nApplication Security Testing Spectrum:\n- SAST: SonarQube, Semgrep (Pre-commit / CI)\n- DAST: OWASP ZAP, Burp Suite (Staging QA)\n- IAST: Contrast Security (Integration testing)\n- RASP: Signal Sciences, Datadog ASM (Production runtime)\n```"),

    ("How do you implement dynamic secrets management and automated rotation using HashiCorp Vault?", "Advanced",
     "Vault generates ephemeral, time-to-live (TTL) credentials on demand (e.g. temporary PostgreSQL user/password valid for 1 hour). When TTL expires, Vault automatically drops the role from the database, eliminating hardcoded long-lived credentials.",
     "```bash\n# Generate Ephemeral PostgreSQL Credentials via Vault CLI\nvault read database/creds/readonly-user\n# Key                Value\n# ---                -----\n# lease_duration     1h\n# password           A1-x9yZq...\n# username           v-token-readonly-user-...\n```"),

    ("How do you enforce Admission Control in Kubernetes using Open Policy Agent (OPA) Gatekeeper or Kyverno?", "Advanced",
     "Admission webhooks intercept API requests to the Kubernetes API server prior to persistence in etcd. Policies enforce that all images must originate from internal trusted registries, containers must run with read-only root filesystems, and resource limits are mandatory.",
     "```yaml\n# Kyverno ClusterPolicy: Enforce Read-Only Root Filesystem\napiVersion: kyverno.io/v1\nkind: ClusterPolicy\nmetadata:\n  name: require-ro-rootfs\nspec:\n  validationFailureAction: Enforce\n  rules:\n    - name: validate-ro-rootfs\n      match:\n        resources:\n          kinds: [Pod]\n      validate:\n        message: \"Root filesystem must be read-only!\"\n        pattern:\n          spec:\n            containers:\n              - securityContext:\n                  readOnlyRootFilesystem: true\n```"),

    ("What is Container Escape and how do you harden container runtimes to prevent privilege escalation?", "Advanced",
     "Container escape occurs when an attacker breaks out of container isolation to the host OS (e.g. via CVEs in runc or mounting `/var/run/docker.sock`). Prevent by running rootless containers, disabling `privileged: true`, dropping all Linux capabilities (`cap_drop: ALL`), enabling AppArmor/SELinux profiles, and using gVisor or Kata Containers for sandboxed microVM isolation.",
     "```yaml\n# Hardened Kubernetes Container SecurityContext\nsecurityContext:\n  runAsNonRoot: true\n  runAsUser: 10001\n  readOnlyRootFilesystem: true\n  allowPrivilegeEscalation: false\n  capabilities:\n    drop:\n      - ALL\n```"),

    ("How do you perform Runtime Threat Detection in Kubernetes using eBPF and Falco?", "Advanced",
     "Falco leverages eBPF kernel probes to monitor system calls (e.g. `execve`, `openat`, socket connections) in real-time. It compares system events against rule definitions (e.g. spawning a shell inside a container, modifying `/etc/shadow`) and emits security alerts with pod metadata.",
     "```yaml\n# Falco Rule: Detect Interactive Shell Spawned in Container\n- rule: Terminal Shell in Container\n  desc: A shell was spawned by an untrusted process inside a container\n  condition: container.id != host and proc.name in (bash, sh, zsh)\n  output: \"Shell spawned in container (user=%user.name pod=%k8s.pod.name proc=%proc.name)\"\n  priority: WARNING\n```"),

    ("How do you implement Mutual TLS (mTLS) with SPIFFE/SPIRE for cryptographic workload identity?", "Advanced",
     "SPIRE issues cryptographic X.509 SVIDs (SPIFFE Verifiable Identity Documents) to pods based on node attestation and workload selectors. Workloads use these short-lived SVID certificates to establish mutual TLS connections where both client and server cryptographically verify identities.",
     "```bash\n# SPIFFE ID Format\nspiffe://company.internal/ns/production/sa/payment-service\n# SPIRE Agent issues SVID x509 cert rotated automatically every 1 hour\n```"),

    ("How do you design a secure Automated Secret Scanning pipeline to prevent credential leaks in Git?", "Intermediate",
     "Implement multi-layered secret scanning: pre-commit hooks running Gitleaks/TruffleHog, branch protection blocking commits with detected patterns, and server-side webhook scanners (GitHub Secret Scanning) that automatically revoke and alert on compromised keys.",
     "```bash\n# Pre-commit Gitleaks Scanner\ngitleaks detect --source=. --verbose --redact\n```")
]

# Add 90 more distinct DevSecOps questions
devsecops_topics = [
    ("How do you remediate vulnerabilities found by Container Vulnerability Scanners (Trivy, Grype)?", "Intermediate", "Update base image to alpine/distroless, pin patch versions in package manifests, multi-stage builds to strip compilers, and automate rebuilds via Renovate."),
    ("What is DREAD Risk Assessment and how is it calculated for security vulnerabilities?", "Intermediate", "DREAD scores Damage, Reproducibility, Exploitability, Affected Users, and Discoverability on a 1-10 scale to prioritize remediation backlogs."),
    ("How do you implement Immutable Infrastructure to enhance cloud security posture?", "Intermediate", "Never SSH into production servers; replace running instances with newly baked golden AMIs/images using Packer and Terraform on every release."),
    ("What are Kubernetes NetworkPolicies and how do they enforce microsegmentation?", "Intermediate", "Layer 3/4 firewall rules implemented by CNI plugins (Calico/Cilium) specifying allowed ingress/egress IP blocks, ports, and pod label selectors."),
    ("How do you secure API Gateways against OWASP API Top 10 vulnerabilities (BOLA, Broken Authentication)?", "Advanced", "Enforce object-level authorization checks in microservices, validate OpenAPI schemas on gateway, throttle endpoints with rate limiters, and strip verbose stack traces."),
    ("What is the difference between RBAC and ABAC in enterprise authorization architectures?", "Intermediate", "RBAC grants permissions based on static user roles (Admin, Editor); ABAC evaluates dynamic attributes (user department, time of day, IP location, resource sensitivity)."),
    ("How do you prevent Cross-Site Scripting (XSS) using Content Security Policy (CSP) headers?", "Intermediate", "Define strict CSP header `Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-xyz'; object-src 'none';` to block inline script injection."),
    ("How do you secure Cloud Object Storage (AWS S3) against unauthorized public access?", "Beginner", "Enable S3 Block Public Access at account level, enforce default AES-256 or KMS encryption, attach least privilege bucket policies, and enable access logging."),
    ("What is Cloud Security Posture Management (CSPM) and how does it detect misconfigurations?", "Intermediate", "Scans cloud infrastructure APIs against compliance benchmarks (CIS Benchmarks, NIST) to detect unencrypted databases, open security groups, and missing MFA."),
    ("How do you configure KMS Envelope Encryption to protect data at rest?", "Advanced", "KMS master key encrypts a local Data Encryption Key (DEK); the application uses DEK to encrypt large files with AES-GCM, storing encrypted DEK alongside the ciphertext."),
    ("How do you implement Threat Intelligence Feeds into enterprise SIEM platforms?", "Intermediate", "Ingest STIX/TAXII feeds of known malicious IPs, domains, and file hashes into SIEM/Elasticsearch to automatically correlate against firewall and VPC flow logs."),
    ("What is AppArmor and how do AppArmor profiles restrict container capabilities on Linux hosts?", "Advanced", "Linux Security Module (LSM) restricting file access, network capabilities, and execution paths per process using declarative enforcement profiles."),
    ("How do you detect and mitigate Server-Side Request Forgery (SSRF) in cloud environments?", "Advanced", "Restrict outbound HTTP requests with firewall egress rules, validate and whitelist URL schemes, and block access to cloud instance metadata IP (`169.254.169.254`)."),
    ("What is AWS IAM Permission Boundary and how does it delegate safe admin rights?", "Advanced", "An advanced IAM feature setting the maximum permissions an identity-based policy can grant, preventing delegated admins from escalating their own privileges."),
    ("How do you conduct automated Dependency License Compliance checks in CI pipelines?", "Beginner", "Run license scanners (FOSSA, license-checker) to fail CI builds if restrictive copyleft licenses (GPLv3, AGPL) are detected in proprietary commercial repositories."),
    ("How do you secure Webhook integrations against replay attacks and spoofing?", "Intermediate", "Sign webhook payloads with HMAC-SHA256 using a shared secret; include a timestamp in the signature header and reject requests older than 5 minutes."),
    ("What is Endpoint Detection and Response (EDR) and how does it monitor developer workstations?", "Intermediate", "Monitors process trees, memory injections, and lateral network connections on laptops and servers, isolating compromised devices automatically."),
    ("How do you configure Keycloak or Auth0 for enterprise Single Sign-On (SSO) with SAML 2.0 and OIDC?", "Intermediate", "Configure Identity Provider (IdP) metadata, define attribute mappings for email and roles, enforce PKCE for client authentication, and set token lifetimes."),
    ("How do you prevent SQL Injection vulnerabilities in modern ORMs and raw queries?", "Beginner", "Always use parameterized prepared statements; never concatenate user inputs into query strings; enforce static analysis rules (Semgrep) in CI."),
    ("What is Chaos Security Engineering and how do you simulate automated adversary attacks?", "Advanced", "Run security chaos experiments (Chaos Mesh, Infection Monkey) to simulate credential stuffing, lateral movement, and revoked certificates to validate detection alerts."),
    ("How do you securely manage environment variables in Docker and Kubernetes without leaks?", "Intermediate", "Never bake env vars into Dockerfile `ENV` instructions; inject secrets at runtime from Kubernetes Secret objects or Vault CSI driver as mounted in-memory tmpfs files."),
    ("What is the Principle of Least Privilege (PoLP) and how do you apply it to cloud IAM roles?", "Beginner", "Grant only the minimum specific permissions required to perform a task (e.g. `s3:GetObject` on a specific prefix rather than `s3:*` on all buckets)."),
    ("How do you protect GraphQL APIs against DoS attacks (Query Depth Limiting, Complexity Analysis)?", "Advanced", "Calculate query complexity scores before execution, reject nested queries exceeding depth threshold (>5), and enforce pagination limits on list fields."),
    ("What is CIS Kubernetes Benchmark and how do you audit clusters using kube-bench?", "Intermediate", "Run kube-bench in a Job container to audit master node configuration, etcd encryption, kubelet certificates, and control plane security against CIS standards."),
    ("How do you implement Secure Software Development Lifecycle (SSDLC) in Agile teams?", "Intermediate", "Integrate security requirements into user stories, conduct architecture threat models in sprint planning, run SAST/SCA in CI, and conduct pre-release pentesting."),
    ("What is Forward Secrecy (PFS) in TLS 1.3 and why does it protect past traffic from decryption?", "Advanced", "Uses ephemeral Diffie-Hellman key exchange (ECDHE) for each session; compromising the server's long-term private key does not reveal past session keys."),
    ("How do you detect Hardcoded Secrets in Git history and permanently purge them using git-filter-repo?", "Intermediate", "Run `git-filter-repo --path secret.pem --invert-paths` to scrub historical commits, force-push to origin, and immediately rotate the compromised credential."),
    ("What is Security Information and Event Management (SIEM) and how are logs ingested?", "Intermediate", "Centralizes security logs from cloud, OS, and applications; normalizes formats (ECS); and correlates anomalies to trigger SOC incident alarms."),
    ("How do you prevent Cross-Site Request Forgery (CSRF) in modern Single Page Applications (SPAs)?", "Beginner", "Store authentication tokens in `SameSite=Strict; HttpOnly; Secure` cookies, or use custom headers (`X-Requested-With`) with CORS protection."),
    ("How do you configure AWS GuardDuty and Security Hub for automated incident response?", "Intermediate", "GuardDuty analyzes VPC flow logs, DNS logs, and CloudTrail events using ML to detect anomalous behaviour; triggers EventBridge to invoke remediation Lambdas."),
    ("What is Web Application Firewall (WAF) and how do Managed Rule Sets (CRS) block OWASP threats?", "Intermediate", "Inspects HTTP traffic at Layer 7; matches payloads against regular expressions and signatures to block SQLi, XSS, and bad bots before reaching the server."),
    ("How do you configure rootless container execution with Podman or Docker Rootless Mode?", "Advanced", "Utilizes user namespaces (`subuid`/`subgid`) to map container UID 0 (root) to an unprivileged non-zero UID on the host, preventing host root compromise."),
    ("What is the difference between Symmetric (AES) and Asymmetric (RSA, ECC) Encryption?", "Beginner", "Symmetric uses the same key for encryption and decryption (fast, bulk data); Asymmetric uses public key for encryption and private key for decryption."),
    ("How do you design a secure Password Storage scheme using Argon2id or bcrypt with Salting?", "Intermediate", "Hash passwords using compute- and memory-hard functions (Argon2id) with a unique cryptographic salt per user to defeat rainbow tables and GPU cracking."),
    ("How do you implement gRPC Mutual Authentication (mTLS) with custom certificate verification?", "Advanced", "Configure TLS credentials with client CA bundle; both client and server present x509 certificates and verify Common Name / SAN identities during handshake."),
    ("What is Binary Authorization in Google Cloud or Sigstore Policy Controller in Kubernetes?", "Advanced", "Admission controller verifying that container images are signed by authorized build authorities and attestations pass before deployment to production."),
    ("How do you mitigate DDoS attacks using Anycast DNS, CDN edge caching, and SYN cookies?", "Advanced", "Distribute traffic across global Anycast points of presence, absorb volumetric attacks at CDN edge, and enable kernel SYN cookies to prevent backlog exhaustion."),
    ("What is eBPF Tetragon and how does it enforce real-time kernel security observability and blocking?", "Advanced", "Tetragon hooks into kernel execution boundaries via eBPF to trace process namespaces, detect privilege escalations, and send SIGKILL to terminate malicious processes in-kernel."),
    ("How do you audit and harden SSH access across enterprise server fleets using Teleport or Bastion hosts?", "Intermediate", "Eliminate static SSH keys; enforce short-lived certificate-based SSH issued via SSO/MFA, record terminal sessions, and audit command execution."),
    ("What are Side-Channel Attacks and how do constant-time cryptographic implementations mitigate them?", "Advanced", "Attacks that extract secret keys by measuring physical runtime duration, power consumption, or CPU cache misses. Mitigated by constant-time algorithms."),
    ("How do you implement secure Data Masking and Tokenization for sensitive PII and credit cards?", "Intermediate", "Replace sensitive numbers (PANs) with non-sensitive surrogate tokens; store real PII in an isolated, encrypted tokenization vault with strict access audits."),
    ("What is an IDOR (Insecure Direct Object Reference) vulnerability and how do you prevent it?", "Beginner", "Occurs when an API accepts an object ID directly without verifying the requesting user owns that resource. Fixed by enforcing tenant authorization checks on every query."),
    ("How do you design a secure Multi-Tenant Database Architecture with Row-Level Security (RLS)?", "Advanced", "Enable PostgreSQL Row Level Security (`ENABLE ROW LEVEL SECURITY`) with policies enforcing `tenant_id = current_setting('app.current_tenant_id')`."),
    ("What is Threat Hunting and how do security analysts search for advanced persistent threats (APTs)?", "Intermediate", "Proactive hypothesis-driven search through historical telemetry and SIEM logs looking for indicators of compromise (IOCs) that bypassed automated alerts."),
    ("How do you secure serverless functions (AWS Lambda, Cloudflare Workers) against event injection?", "Intermediate", "Validate all event payloads against strict schemas, apply least privilege IAM execution roles, and keep function dependencies minimal and scanned."),
    ("What is Security Chaos Engineering and how do you test fault tolerance under security stress?", "Advanced", "Inject security failures in staging: revoke database TLS certs, simulate DNS poisoning, or simulate expired JWT signing keys to verify system resilience."),
    ("How do you perform Threat Modeling using the PASTA (Process for Attack Simulation and Threat Analysis) framework?", "Advanced", "7-step risk-centric threat modeling methodology aligning technical vulnerabilities directly with business objectives and financial impact."),
    ("What is Clickjacking and how does the `X-Frame-Options` and CSP `frame-ancestors` directive prevent it?", "Beginner", "Attacker embeds target site in an invisible iframe to trick users into clicking buttons. Prevented by setting `X-Frame-Options: DENY` or `frame-ancestors 'none'`."),
    ("How do you automate TLS Certificate Provisioning and Renewal with cert-manager and Let's Encrypt?", "Intermediate", "Deploy cert-manager in Kubernetes with ACME ClusterIssuer, configuring HTTP-01 or DNS-01 challenge solvers to automatically rotate certificates every 60 days."),
    ("What are Supply Chain Attacks targeting NPM and PyPI ecosystems and how do lockfiles mitigate them?", "Intermediate", "Malicious actors publish typo-squatted packages or hijack maintainer accounts. Mitigated by commit-pinned lockfiles, npm provenance, and private package proxies."),
    ("How do you configure AWS VPC Flow Logs and analyze them with Athena for anomalous egress traffic?", "Intermediate", "Enable VPC Flow Logs on subnets sending to S3; query flow logs with SQL in Athena looking for rejected connections, high egress bytes, and unauthorized ports."),
    ("What is Open Policy Agent (OPA) and how do you write Rego policies for infrastructure compliance?", "Advanced", "Declarative policy engine evaluating JSON inputs against Rego rules; used in Terraform CI to block non-compliant resources (e.g. unencrypted RDS instances)."),
    ("How do you implement Risk-Based Adaptive Authentication with IP reputation and device fingerprinting?", "Advanced", "Evaluate request risk score based on geo-velocity, Tor exit node status, and device cookies; dynamically challenge high-risk logins with WebAuthn/FIDO2 MFA."),
    ("What is Directory Traversal (Path Traversal) and how do you prevent `../` attacks in file uploads?", "Beginner", "Attacker manipulates file paths to access unauthorized directories. Prevented by sanitizing file names with `path.basename()` and rejecting relative dots."),
    ("How do you secure Kafka clusters with SASL/SCRAM and TLS encryption?", "Advanced", "Configure broker listeners with TLS for encryption in transit, enable SASL/SCRAM-SHA-512 for client authentication, and define Kafka ACLs per topic."),
    ("What is the difference between Stateful and Stateless Firewalls?", "Beginner", "Stateful firewalls track active connection states (TCP SYN/ACK) and permit return traffic automatically; Stateless evaluate packets individually against rules."),
    ("How do you configure Security Headers (`HSTS`, `X-Content-Type-Options`, `Referrer-Policy`) on Nginx?", "Intermediate", "Add headers in Nginx configuration: `Strict-Transport-Security: max-age=31536000; includeSubDomains`, `X-Content-Type-Options: nosniff`."),
    ("What is Subresource Integrity (SRI) and how does it prevent CDN compromise attacks?", "Beginner", "Attaches cryptographic hash (`integrity=\"sha384-...\"`) to script tags; browser refuses to execute script if CDN delivers altered bytes."),
    ("How do you design an Incident Response Playbook for a Ransomware attack on cloud infrastructure?", "Advanced", "Isolate affected subnets, take EBS snapshots for forensics, revoke compromised IAM credentials, restore from immutable air-gapped backups, and notify legal."),
    ("What is Bug Bounty Program design and how do you establish a Responsible Disclosure Policy (security.txt)?", "Intermediate", "Host `/.well-known/security.txt` defining PGP keys and reporting channels; set up Bugcrowd/HackerOne with clear safe harbor legal protections."),
    ("How do you configure Memory Sanitizers (AddressSanitizer, MemorySanitizer) in C/C++ CI builds?", "Advanced", "Compile with `-fsanitize=address,undefined` in CI test pipelines to catch buffer overflows, use-after-free, and memory corruption bugs before shipping."),
    ("What is DNSSEC and how does it prevent DNS Cache Poisoning attacks?", "Advanced", "Cryptographically signs DNS zone records with public key cryptography; resolvers verify digital signatures to ensure DNS responses are authentic."),
    ("How do you implement Ephemeral Staging Environments with automated teardown to minimize attack surface?", "Intermediate", "Spin up isolated Kubernetes namespaces per PR using GitHub Actions and Helm; run automated pentests and delete namespace immediately after merge."),
    ("What is HTTP Request Smuggling and how do conflicting `Content-Length` and `Transfer-Encoding` cause it?", "Advanced", "Occurs when frontend reverse proxy and backend server interpret HTTP request boundaries differently, allowing an attacker to smuggle hidden requests."),
    ("How do you audit IAM role assumption with AWS CloudTrail and AWS Athena?", "Intermediate", "Query CloudTrail `AssumeRole` events in Athena to track cross-account access, credential usage timestamps, and anomalous IP addresses."),
    ("What is Kernel Hardening with sysctl (`kernel.kptr_restrict`, `fs.protected_hardlinks`)?", "Advanced", "Configure Linux sysctl parameters to hide kernel pointers from unprivileged users, restrict hardlink creation, and enable memory randomization."),
    ("How do you implement Client-Certificate Authentication for high-security banking APIs?", "Advanced", "Configure reverse proxy to require and validate client x509 certificates against an internal private Certificate Authority before proxying to backend."),
    ("What is OWASP Top 10 for LLMs (Prompt Injection, Insecure Output Handling, Training Data Poisoning)?", "Intermediate", "Security risks specific to Generative AI: attackers manipulate LLM prompts to bypass system guardrails, extract system prompts, or execute unauthorized tools."),
    ("How do you secure Redis instances in production against remote execution exploits?", "Intermediate", "Require strong passwords (`requirepass`), disable dangerous commands (`FLUSHALL`, `CONFIG`), bind strictly to private loopback/VPC, and enable TLS."),
    ("What is OpenSSF Scorecard and how does it measure open source project health?", "Intermediate", "Automated tool evaluating security practices of open-source repositories: branch protection, signed commits, pinned dependencies, and vulnerability reporting."),
    ("How do you implement Zero-Downtime Secret Rotation for database passwords?", "Advanced", "Create second database user with identical permissions; update application config via rolling release; verify all instances connect with new credentials; revoke old user."),
    ("What is Cross-Site Script Inclusion (XSSI) and how does JSON vulnerability prefix `)]}',\\n` stop it?", "Advanced", "Old browser exploit reading JSON via script tag; prepending infinite loop or invalid tokens prevents parsing as executable JavaScript."),
    ("How do you configure AWS WAF Rate-Based Rules to defend against credential stuffing on `/login`?", "Intermediate", "Create rate-based rule evaluated on client IP targeting URI `/api/login`, setting limit of 100 requests per 5-minute evaluation window."),
    ("What is Sandboxing and how does Google Chrome / gVisor isolate untrusted code execution?", "Advanced", "Utilizes operating system primitives (namespaces, cgroups, seccomp filters) to intercept and restrict system calls made by untrusted processes."),
    ("How do you detect Man-in-the-Middle (MITM) attacks on mobile applications using SSL Certificate Pinning?", "Intermediate", "Mobile apps pin the expected public key hash of the backend server; rejects connection if an intercepting proxy presents a different CA certificate."),
    ("What is Cross-Origin Resource Sharing (CORS) and why does `Access-Control-Allow-Origin: *` with credentials fail?", "Beginner", "Browsers block requests with wildcard origin when credentials (cookies) are enabled to prevent malicious sites from reading authenticated user data."),
    ("How do you enforce Signed Git Commits using GPG or SSH keys in GitHub Enterprise?", "Beginner", "Configure `git config --global user.signingkey` and enable 'Require signed commits' branch protection rule to verify commit author identity."),
    ("What is the difference between Virtual Private Cloud (VPC) Peering and AWS Transit Gateway?", "Intermediate", "VPC Peering connects 2 VPCs in a non-transitive 1:1 mesh; Transit Gateway acts as a central cloud router connecting hundreds of VPCs and on-premise networks."),
    ("How do you prevent XML External Entity (XXE) injection attacks in legacy XML parsers?", "Beginner", "Disable external DTD resolution (`disallow-doctype-decl = true`) and disable external entity expansion in XML parser configuration."),
    ("What is Security Chaos GameDay and how do cross-functional teams practice incident response?", "Intermediate", "Scheduled workshop where engineers simulate disaster scenarios (databreach, key leak) to practice war room communication and verify alerting runbooks."),
    ("How do you audit Docker container images for malware and rootkit infections with ClamAV?", "Intermediate", "Mount container image layers into a scanner container running ClamAV and YARA rules to detect backdoor scripts and malicious binaries."),
    ("What is DNS over HTTPS (DoH) and how does it protect user privacy on public Wi-Fi networks?", "Beginner", "Encrypts DNS queries using HTTPS/TLS, preventing local ISP and eavesdroppers from observing domain lookups."),
    ("How do you secure Prometheus metrics endpoints (`/metrics`) from unauthorized scraping?", "Intermediate", "Protect `/metrics` behind internal VPC networks, mTLS, or reverse proxy with HTTP Basic Auth / Bearer token authentication."),
    ("What is In-Memory Encryption and how does AMD SEV / Intel SGX confidential computing protect data in RAM?", "Advanced", "Hardware-enforced memory encryption engine encrypts RAM contents with keys held inside CPU; hypervisor and host OS cannot read enclave memory."),
    ("How do you implement Automated Security Testing in Pull Requests using GitHub Actions?", "Intermediate", "Configure workflow running SAST (Semgrep), Dependency Review, and Trivy container scan on every PR; block merges if HIGH/CRITICAL vulnerabilities exist."),
    ("What is the difference between Defense in Depth and Zero Trust?", "Intermediate", "Defense in Depth layers multiple perimeter defenses (firewall -> proxy -> app); Zero Trust assumes perimeter is breached and validates every transaction continuously."),
    ("How do you secure Elasticsearch clusters against unauthenticated data exposure?", "Intermediate", "Enable X-Pack security, configure TLS for internode communication, enforce role-based access control (RBAC), and never expose port 9200 to the public internet."),
    ("What is Timing Attack on string comparison and how does `crypto.timingSafeEqual()` fix it?", "Intermediate", "Standard `===` exits early on the first mismatched character, leaking string length and content through microsecond differences. Fixed by constant-time XOR comparison."),
    ("How do you implement Disaster Recovery with automated cross-region database replication?", "Advanced", "Configure AWS Aurora Global Database with asynchronous storage replication across regions (<1s lag); execute automated failover in under 1 minute."),
    ("How do you design an enterprise Vulnerability Disclosure and Bug Bounty triage workflow?", "Intermediate", "Setup HackerOne/Bugcrowd with clear severity levels (P1-P4), SLA for triage (<24h), verified safe harbor legal protections, and automated Jira integration.")
]

for title, diff, strat in devsecops_topics:
    devsecops_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```yaml\n# Enterprise DevSecOps Standard for: {title}\napiVersion: security.defense/v1\nkind: Policy\nmetadata:\n  name: enforce-strict-compliance\n```"
    })

formatted_devsecops = []
for item in devsecops_raw[:10]:
    if isinstance(item, tuple):
        formatted_devsecops.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
    else:
        formatted_devsecops.append(item)
formatted_devsecops.extend(devsecops_raw[10:])

write_category_file("devsecops", "devsecops-questions.md", "DevSecOps & Threat Modeling", "Comprehensive interview questions covering STRIDE, Zero-Trust, Supply Chain Security, SBOM, and Container Hardening", "html-css-js-icon.svg", formatted_devsecops[:100])
print(f"DevSecOps complete with {len(formatted_devsecops[:100])} distinct questions.")
