import os
import sys
sys.path.append(os.path.dirname(__file__))
from writer_helper import write_category_file

# ==============================================================================
# 9. LINUX KERNEL & eBPF ENGINEERING (100 REAL QUESTIONS)
# ==============================================================================
kernel_raw = [
    ("How does the in-kernel eBPF Verifier guarantee safety, non-termination prevention, and memory isolation without kernel panics?", "Advanced",
     "The eBPF verifier executes an exhaustive static analysis of the bytecode before loading it into the kernel: 1) Checks that the Control Flow Graph (CFG) is a Directed Acyclic Graph (DAG) by detecting and rejecting unbounded loops (bounded loops unrolled up to limit). 2) Simulates all possible execution paths tracking register types, pointer provenance, and memory offsets. 3) Enforces that all memory dereferences stay strictly within valid allocated memory boundaries (e.g. context, stack, or map value buffers). 4) Proves that uninitialized register values are never read, guaranteeing the program cannot panic the kernel or leak memory.",
     "```c\n// Clang/LLVM C to eBPF Target Compilation\n// SEC(\"xdp\") defines the ELF section loaded by libbpf into kernel\n#include <linux/bpf.h>\n#include <bpf/bpf_helpers.h>\n\nSEC(\"xdp\")\nint xdp_drop_all(struct xdp_md *ctx) {\n    void *data = (void *)(long)ctx->data;\n    void *data_end = (void *)(long)ctx->data_end;\n    \n    // Mandatory verifier boundary check: must verify packet length before read!\n    if (data + sizeof(struct ethhdr) > data_end)\n        return XDP_DROP;\n        \n    return XDP_PASS;\n}\nchar _license[] SEC(\"license\") = \"GPL\";\n```"),

    ("What is XDP (eXpress Data Path) and how do `XDP_DROP`, `XDP_TX`, and `XDP_REDIRECT` achieve line-rate 100GbE packet processing?", "Advanced",
     "XDP runs eBPF programs directly inside the network interface card (NIC) driver at the lowest possible software layer, before the Linux kernel allocates a Socket Buffer (`sk_buff` / SKB). `XDP_DROP` drops malicious packets instantly at the wire (handling 24+ million packets/sec per core). `XDP_TX` bounces packets back out the same interface. `XDP_REDIRECT` forwards packets to other network interfaces, CPUs, or directly into user-space bypass applications via AF_XDP sockets (`XSK`).",
     "```text\nLinux Network Ingress Path Comparison:\nStandard Linux: NIC DMA -> Kernel Allocates SKB (Heavy) -> Netfilter/iptables -> TCP Stack -> Socket\nXDP Hook:      NIC DMA -> [eBPF XDP Hook executes here in Driver] -> Fast Drop/Redirect (Zero SKB!)\n```"),

    ("What is the architectural difference between eBPF Perf Ring Buffers and the modern BPF Ring Buffer (`BPF_MAP_TYPE_RINGBUF`)?", "Advanced",
     "Perf Ring Buffer allocates independent per-CPU circular buffers. If a core generates heavy events while another core is idle, the busy core drops events (buffer overflow) while memory on idle cores is wasted. The modern BPF Ring Buffer (`BPF_MAP_TYPE_RINGBUF`) is a single, globally shared multi-producer single-consumer ring buffer with atomic memory reservations (`bpf_ringbuf_reserve` / `bpf_ringbuf_submit`), guaranteeing global memory efficiency and deterministic event ordering across all CPU cores.",
     "```c\n// Modern BPF Ring Buffer Reservation in Kernel eBPF\nstruct {\n    __uint(type, BPF_MAP_TYPE_RINGBUF);\n    __uint(max_entries, 256 * 1024);\n} events_ringbuf SEC(\".maps\");\n\n// Zero-copy reservation directly in ring buffer memory\nstruct event *e = bpf_ringbuf_reserve(&events_ringbuf, sizeof(*e), 0);\nif (e) {\n    e->pid = bpf_get_current_pid_tgid() >> 32;\n    bpf_ringbuf_submit(e, 0);\n}\n```"),

    ("What is CO-RE (Compile Once - Run Everywhere) and how does BPF Type Format (BTF) eliminate kernel header dependencies?", "Advanced",
     "Historically, BCC compiled eBPF programs on target servers using Clang against local installed kernel headers (`linux-headers-$(uname -r)`), which was slow and memory-heavy. CO-RE records kernel data structure layouts in compact BPF Type Format (BTF) metadata (`/sys/kernel/btf/vmlinux`). Libbpf dynamically patches struct member field byte offsets at runtime before loading, allowing a single pre-compiled eBPF ELF binary to run across multiple different Linux kernel versions.",
     "```c\n// CO-RE Field Access using BPF_CORE_READ helper macro\n#include <vmlinux.h>\n#include <bpf/bpf_core_read.h>\n\nSEC(\"kprobe/sys_enter_openat\")\nint trace_openat(struct pt_regs *ctx) {\n    struct task_struct *task = (struct task_struct *)bpf_get_current_task();\n    pid_t ppid = BPF_CORE_READ(task, real_parent, tgid); // Automatically relocates offset!\n    return 0;\n}\n```"),

    ("How do AF_XDP (`XSK`) Sockets achieve zero-copy user-space packet streaming with UMEM buffers?", "Advanced",
     "AF_XDP connects an XDP driver directly to a user-space application memory buffer called UMEM. UMEM is registered via memory mapping (`mmap`). The driver and user-space communicate through lock-free single-producer single-consumer (SPSC) ring queues (Fill Ring, Rx Ring, Tx Ring, Completion Ring). Packets arrive via DMA directly into user-space UMEM chunks, achieving zero memory copies and line-rate packet inspection without proprietary kernel bypass drivers.",
     "```text\nAF_XDP UMEM Ring Queue Architecture:\nUser Space Allocates Memory -> [UMEM Buffer Pool]\n[Fill Ring]: User space deposits free buffer descriptors to NIC\n[Rx Ring]:   NIC deposits received packet descriptors to User space\n[Tx Ring]:   User space deposits outgoing packet descriptors to NIC\n[Comp Ring]: NIC notifies User space that transmission buffer can be reused\n```")
]

# 95 more distinct Linux Kernel & eBPF topics
kernel_topics = [
    ("What are kprobes, kretprobes, tracepoints, and fentry/fexit in kernel instrumentation?", "Intermediate", "kprobes dynamically patch kernel instruction bytes with breakpoint traps (higher overhead); tracepoints are statically compiled trace hooks; fentry/fexit use compiler mcount instrumentation for near-zero overhead."),
    ("How does the Linux Completely Fair Scheduler (CFS) allocate CPU time using `vruntime` (Virtual Runtime)?", "Advanced", "CFS tracks execution time scaled by process nice value in a red-black tree; the leftmost node with the lowest `vruntime` is always picked next for execution."),
    ("What is Copy-on-Write (CoW) during Linux `fork()` and how does the kernel manage page table entries?", "Intermediate", "Parent and child processes share identical physical RAM pages marked read-only; when either writes to a page, a Page Fault triggers copying the page to a new physical frame."),
    ("How does Linux Virtual Memory manage 4-level and 5-level Page Tables (PGD, P4D, PUD, PMD, PTE)?", "Advanced", "MMU translates 48-bit or 57-bit virtual addresses by indexing through hierarchical page directories in physical RAM, caching translation in hardware TLB."),
    ("What is Translation Lookaside Buffer (TLB) Shootdown and why does it cause multi-core latency spikes?", "Advanced", "When a core invalidates a page table mapping, it must broadcast Inter-Processor Interrupts (IPIs) to all other cores sharing that address space to flush their local TLBs."),
    ("How does `epoll` work internally in the Linux kernel (rbtree + ready list wait queue)?", "Advanced", "`epoll_ctl` stores monitored file descriptors in a red-black tree; device drivers wake up wait queues which place active events into a doubly-linked ready list returned in $O(1)$ by `epoll_wait`."),
    ("What is the difference between Edge-Triggered (`EPOLLET`) and Level-Triggered (`EPOLLIN`) in `epoll`?", "Intermediate", "Level-triggered returns event continuously as long as buffer has data; Edge-triggered notifies only when new state transition occurs, requiring non-blocking read until `EAGAIN`."),
    ("How do Linux cgroups v2 (Control Groups) manage CPU, Memory, and I/O resource isolation?", "Intermediate", "Unified hierarchical directory tree under `/sys/fs/cgroup`; applies strict resource limits (e.g. `memory.max`, `cpu.weight`, `io.weight`) per process tree."),
    ("What is Linux Namespaces (PID, NET, MNT, IPC, UTS, USER, CGROUP) and how do they power containers?", "Beginner", "Kernel feature providing process isolation: PID isolates process trees; NET isolates network interfaces and IP routing; MNT isolates filesystem mounts."),
    ("How does the Linux Page Cache work and how do `pdflush` / `flush` threads write dirty pages to disk?", "Intermediate", "Kernel buffers disk reads/writes in unused RAM; write calls write to Page Cache marking pages 'dirty'; background kernel threads flush dirty pages to disk based on `vm.dirty_ratio`."),
    ("What is OOM Killer (Out Of Memory Killer) and how does it calculate `oom_score`?", "Intermediate", "When physical RAM and swap are exhausted, kernel computes `oom_score` based on percentage of RAM consumed and `oom_score_adj`; terminates process with highest score via SIGKILL."),
    ("How do Linux Kernel Softirqs, Tasklets, and Workqueues differ for deferred interrupt handling?", "Advanced", "Softirqs run in interrupt context on any core (strictly serialized); Tasklets run in interrupt context pinned to core; Workqueues run in process context and can sleep/block."),
    ("What is `task_struct` and how does the Linux kernel represent processes and threads?", "Intermediate", "C struct representing process control block: holds PID, state, memory maps (`mm_struct`), file descriptor table (`files_struct`), signal handlers, and scheduling attributes."),
    ("How does BPF Map type `BPF_MAP_TYPE_HASH` vs `BPF_MAP_TYPE_ARRAY` differ in lookup performance?", "Intermediate", "Array maps have pre-allocated fixed memory with $O(1)$ direct index lookup; Hash maps support dynamic keys using MurmurHash/xxHash with bucket collision chaining."),
    ("What is Per-CPU BPF Map (`BPF_MAP_TYPE_PERCPU_ARRAY`) and how does it eliminate CPU cache contention?", "Advanced", "Allocates independent memory buffer for each CPU core; eBPF programs read and write only their local core's buffer without locks or cross-core cache invalidation."),
    ("How does Linux TC (Traffic Control) BPF classifier attach to network ingress and egress queues?", "Advanced", "Attaches to kernel queuing discipline (qdisc); can inspect, modify, and drop packets or redirect packets between network interfaces on ingress or egress."),
    ("What is cgroup v2 BPF socket filtering (`BPF_PROG_TYPE_CGROUP_SOCK_ADDR`)?", "Advanced", "Intercepts `connect()`, `bind()`, and `sendmsg()` system calls inside container cgroups to redirect network traffic (e.g. Istio ambient mesh redirecting traffic without iptables)."),
    ("How does Kernel Memory Allocation differ: `kmalloc` vs `vmalloc`?", "Intermediate", "`kmalloc` allocates physically contiguous memory (fast, required for DMA); `vmalloc` allocates virtually contiguous but physically non-contiguous memory (slower, for large buffers)."),
    ("What is SLAB, SLUB, and SLOB memory allocators in the Linux kernel?", "Advanced", "Object-based memory allocators caching pre-allocated kernel structs (`inode`, `task_struct`); SLUB is the modern un-queued, lockless default allocator replacing SLAB."),
    ("How does `mmap()` work internally and how do Anonymous vs File-Backed mappings differ?", "Intermediate", "Allocates Virtual Memory Areas (VMAs) in process address space; Anonymous mappings allocate zero-initialized RAM pages; File-backed mappings map disk file blocks via Page Cache."),
    ("What is HugeTLB (hugetlbfs) and Transparent Huge Pages (THP) in Linux memory management?", "Intermediate", "Allocates 2MB or 1GB memory pages instead of standard 4KB pages; dramatically reduces TLB cache misses for database buffer pools and high-throughput systems."),
    ("How do RCU (Read-Copy-Update) locks achieve lock-free reads in the Linux kernel?", "Advanced", "Readers access shared data concurrently without locks; writers copy object, modify copy, and atomically swap pointer; old object is freed only after a grace period when all readers finish."),
    ("What is the purpose of `seccomp` (Secure Computing Mode) and BPF seccomp filters in container sandboxing?", "Intermediate", "Restricts available system calls a process can make; unallowed system calls trigger immediate process termination (`SECCOMP_RET_KILL`) or error return."),
    ("How does Direct I/O (`O_DIRECT`) bypass the Linux Page Cache?", "Intermediate", "Transfers data directly between user-space memory buffer and disk controller DMA without copying into kernel Page Cache, used by database engines managing private caches."),
    ("What is `io_uring` and how does its submission and completion queue pair eliminate system call overhead?", "Advanced", "Shares two lock-free ring buffers (SQ and CQ) between user space and kernel via `mmap`; user writes multiple I/O requests into SQ; kernel processes them and posts to CQ without syscalls."),
    ("How do Linux Virtual Filesystems (VFS) abstract heterogeneous filesystems (ext4, XFS, NFS, Btrfs)?", "Intermediate", "Provides standard object-oriented interface structs: `super_block` (filesystem instance), `inode` (file metadata), `dentry` (directory entry cache), and `file` (open file handle)."),
    ("What is the dentry cache (dcache) and inode cache in Linux VFS?", "Intermediate", "In-memory cache mapping file path components to directory entries (dentries) and inodes, avoiding repeated disk reads during file path resolution."),
    ("How does the Linux Kernel handle Context Switching (`switch_to` macro and hardware registers)?", "Advanced", "Saves user registers on kernel stack; switches Kernel Stack Pointer (KSP) and page table root register (CR3 on x86); restores registers of target process."),
    ("What is Kernel Space vs User Space memory split (3G/1G on 32-bit, canonical addresses on 64-bit)?", "Beginner", "User space processes occupy lower address range; kernel occupies upper address range; hardware ring levels (Ring 0 vs Ring 3) enforce execution privilege."),
    ("How does Linux implement Inter-Process Communication (IPC): Unix Domain Sockets vs Named Pipes (FIFOs)?", "Intermediate", "Unix domain sockets support bidirectional stream/datagram communication and passing file descriptors (`SCM_RIGHTS`); Pipes are unidirectional byte streams."),
    ("What is Netfilter and how do `iptables` / `nftables` hook into packet traversal points (PREROUTING, FORWARD, POSTROUTING)?", "Intermediate", "Framework in kernel networking stack providing hooks at 5 traversal points to inspect, alter, and drop packets via packet filtering and NAT rules."),
    ("How do Linux Virtual Interfaces (veth pairs) route traffic between container network namespaces?", "Beginner", "Acts as a bidirectional virtual Ethernet cable: packets sent into `veth0` inside container namespace emerge immediately at `veth1` in host root namespace."),
    ("What is Network Device Polling (`NAPI`) in Linux network drivers?", "Advanced", "Hybrid interrupt-polling mechanism: initial packet generates hardware interrupt; driver switches to polling mode to process batch of packets, avoiding interrupt storms."),
    ("How do eBPF tail calls (`bpf_tail_call`) chain multiple eBPF programs together?", "Advanced", "Transfers execution from one eBPF program to another without returning, reusing current stack frame to bypass the 1-million instruction verifier limit."),
    ("What is BPF-to-BPF function calls and how do they differ from tail calls?", "Intermediate", "Standard subprogram calls with caller-callee argument passing conforming to BPF ABI; allows modular code reuse within a single verified eBPF ELF binary."),
    ("How do you debug eBPF programs using `bpftool` and `bpftrace`?", "Intermediate", "`bpftool prog show` lists loaded programs; `bpftool map dump` inspects map contents; `bpftool prog trace_pipe` streams `bpf_printk` debug outputs."),
    ("What is Kernel Address Space Layout Randomization (KASLR) and how does it defend against exploits?", "Intermediate", "Randomizes base memory address where the kernel image is loaded at boot time, preventing attackers from using hardcoded memory offsets for ROP gadgets."),
    ("How does Linux handle Synchronous vs Asynchronous Signals (`kill`, `sigaction`)?", "Intermediate", "Kernel marks pending signal bit in `task_struct`; on return from kernel to user space, kernel sets up user stack frame to execute custom signal handler."),
    ("What is the difference between Block Devices and Character Devices in Linux?", "Beginner", "Character devices transfer unbuffered sequential stream of bytes (keyboard, serial); Block devices transfer fixed-size blocks with random access and caching (SSD, HDD)."),
    ("How does the Linux Kernel handle Hardware Interrupt (IRQ) balancing with `irqbalance`?", "Intermediate", "Daemon dynamically distributes peripheral hardware interrupts across available CPU cores to prevent a single core from being saturated by network/disk IRQs."),
    ("What is Memory Compaction and Page Reclaim in Linux virtual memory management?", "Advanced", "Scans physical memory zones; moves allocated pages together to create contiguous free blocks, preventing allocation failures for multi-page requests (huge pages)."),
    ("How do you prevent Kernel Deadlocks using Lockdep (Lock Dependency Validator)?", "Advanced", "Compile-time and runtime kernel subsystem tracking lock acquisition ordering; automatically detects potential circular lock dependency deadlocks before they occur."),
    ("What is Mellanox / NVIDIA mlx5 driver architecture and its integration with eBPF XDP?", "Advanced", "ConnectX NICs support native hardware offload of eBPF XDP rules directly into NIC hardware ASIC, filtering packets at 200+ Gbps wire speed."),
    ("How does eBPF LSM (Linux Security Module) hooks enforce MAC (Mandatory Access Control)?", "Advanced", "Hooks directly into LSM security checkpoints (`bpf_lsm_file_open`, `bpf_lsm_bprm_check_security`); returns `-EPERM` to deny unauthorized operations in-kernel."),
    ("What is Virtio and vhost-net in Linux Kernel virtualization (KVM / QEMU)?", "Advanced", "Standardized paravirtualized device architecture; vhost-net moves virtual network packet processing into host kernel space, bypassing QEMU user space."),
    ("How does the Linux Kernel handle File Locking (`flock` vs `fcntl` record locking)?", "Intermediate", "`flock` applies advisory lock to entire open file description; `fcntl` applies byte-range record locks to specific byte offsets of an inode."),
    ("What is Kernel Preemption (`CONFIG_PREEMPT`) and Real-Time Linux (`PREEMPT_RT`)?", "Advanced", "`CONFIG_PREEMPT` allows high-priority tasks to preempt kernel execution; `PREEMPT_RT` converts spinlocks to sleeping mutexes and forces all IRQs to run as threads."),
    ("How does eBPF trace User-Space applications using uprobes and USDT (User Statically-Defined Tracing)?", "Intermediate", "Instruments user-space binary by replacing instruction byte with `int3` breakpoint; kernel intercepts trap, executes eBPF probe, and resumes user app."),
    ("What is BPF Type Format (BTF) deduplication algorithm?", "Advanced", "Analyzes millions of type definitions across kernel headers; merges structurally identical structs, unions, and typedefs, shrinking metadata from 100MB to 3MB."),
    ("How does the Linux Kernel implement Memory Swapping algorithms (LRU Active vs Inactive lists)?", "Intermediate", "Maintains Active and Inactive lists of memory pages; pages not accessed recently migrate from Active to Inactive, and are reclaimed or written to swap."),
    ("What is eBPF Map Pinned Paths in BPF Virtual Filesystem (`/sys/fs/bpf`)?", "Intermediate", "Pins BPF maps to persistent filesystem paths so maps stay alive and retain state in kernel memory even after the user-space loader process terminates."),
    ("How do you profile Linux Kernel CPU usage using `perf record` and FlameGraphs?", "Intermediate", "Samples CPU instruction pointers at 99Hz (`perf record -F 99 -a -g -- sleep 10`); parses stack traces with `stackcollapse-perf.pl` to render SVG FlameGraph."),
    ("What is Kernel Memory Leak detection using KMEMLEAK?", "Intermediate", "Tracks memory allocations made by `kmalloc`; periodically scans kernel memory for pointer references; flags allocated blocks with zero pointers as memory leaks."),
    ("How does the Linux Kernel handle Clock Sources (TSC, HPET, ACPI PM Timer)?", "Intermediate", "Time Stamp Counter (TSC) is fastest on-die CPU register; kernel verifies invariant TSC stability across cores, falling back to HPET if clock drift occurs."),
    ("What is Transparent Inter-Process Communication (TIPC) in clustered Linux systems?", "Advanced", "Cluster-aware transport protocol allowing processes on different nodes to communicate via service-name addressing without managing IP addresses."),
    ("How do eBPF programs read and write Socket Buffers (`__sk_buff`) in socket filter programs?", "Intermediate", "Accesses mirrored fields via BPF helper functions (`bpf_skb_load_bytes`, `bpf_skb_store_bytes`); direct packet access allowed via `skb->data` pointers."),
    ("What is Linux Memory Overcommit and `vm.overcommit_memory` settings (0, 1, 2)?", "Intermediate", "0: heuristic overcommit; 1: always allow overcommit; 2: strict no-overcommit (refuses `malloc` if total committed memory exceeds RAM + Swap percentage)."),
    ("How does Linux implement Asynchronous I/O (POSIX AIO vs Linux Native Kernel AIO)?", "Intermediate", "POSIX AIO emulates async I/O using user-space pthreads; Linux Native AIO (`io_submit`) executes in kernel but only works reliably on `O_DIRECT` file I/O."),
    ("What is `sysfs` vs `procfs` in Linux kernel communication?", "Beginner", "`procfs` (`/proc`) exposes process state and kernel configuration; `sysfs` (`/sys`) exposes structured hierarchical device driver and hardware bus tree."),
    ("How does eBPF implement zero-copy Socket Redirection via `sockmap` and `bpf_msg_redirect_hash`?", "Advanced", "Intercepts TCP payloads at socket layer (`bpf_sockmap`); redirects packets directly from sender's socket buffer to receiver's socket buffer, bypassing TCP/IP stack."),
    ("What is Dirty Cow (CVE-2016-5195) and how did race condition in Copy-on-Write compromise kernel memory?", "Advanced", "Race condition between `madvise(MADV_DONTNEED)` and write to private read-only mmap allowed unprivileged users to write directly to read-only page cache files."),
    ("How does the Linux Kernel implement Dynamic Module Loading (`insmod`, `rmmod`, `modprobe`)?", "Beginner", "Loads compiled `.ko` ELF object files into kernel memory; resolves kernel symbol dependencies via `/proc/kallsyms`; calls module initialization entry point."),
    ("What is Memory Barrier instruction `smp_mb()`, `smp_rmb()`, and `smp_wmb()` in Linux device drivers?", "Advanced", "Prevents compiler and out-of-order CPU hardware from reordering memory reads and writes across synchronization boundaries on SMP multi-core systems."),
    ("How do eBPF helper functions pass data to user space via `bpf_probe_read_kernel` and `bpf_probe_read_user`?", "Intermediate", "Safely dereferences arbitrary pointers from kernel or user virtual memory, handling page faults transparently without crashing the kernel."),
    ("What is Network Device Offloading: TSO, GSO, LRO, and GRO?", "Advanced", "TSO/GSO segment large 64KB TCP packets into MTU frames in NIC hardware; LRO/GRO reassemble multiple incoming packets into a single large packet before CPU stack."),
    ("How does the Linux Kernel handle Meltdown and Spectre CPU hardware vulnerabilities (KPTI, Retpolines)?", "Advanced", "Kernel Page Table Isolation (KPTI) separates user and kernel page tables to prevent speculative cache leaks; Retpolines replace indirect jumps with return trampolines."),
    ("What is Real-Time Scheduling Class in Linux (SCHED_FIFO and SCHED_RR)?", "Intermediate", "Fixed priority classes (1-99) that preempt normal CFS tasks; SCHED_FIFO runs until it blocks or yields; SCHED_RR runs with round-robin time slice."),
    ("How do eBPF programs monitor and alter TCP Congestion Control algorithms (`bpf_setsockopt`)?", "Advanced", "Dynamically attaches to socket initialization; switches TCP congestion algorithm from CUBIC to BBR based on destination IP or client connection parameters."),
    ("What is `ptrace` system call and how do debuggers (GDB) inspect running processes?", "Intermediate", "Allows tracing process to observe and control target execution, read/write memory and CPU registers, and intercept system calls via `PTRACE_PEEKTEXT` / `PTRACE_POKETEXT`."),
    ("How does Linux handle Dynamic Linker (`ld.so`) symbol resolution (`DT_NEEDED`, `PLT`, `GOT`)?", "Intermediate", "Dynamic linker loads shared libraries; Global Offset Table (GOT) and Procedure Linkage Table (PLT) resolve external function addresses lazily on first invocation."),
    ("What is Kernel Live Patching (kpatch / livepatch) and how does it update kernel code without rebooting?", "Advanced", "Redirects function entry points to patched functions using ftrace; waits until all threads exit the old function before committing replacement."),
    ("How does eBPF verify and enforce Loop Bounds in Linux kernel 5.3+?", "Advanced", "Allows bounded loops if the verifier can prove all branches terminate within 1 million instructions, tracking loop induction variable limits."),
    ("What is the difference between Kernel Threads (`kthreads`) and User Threads?", "Beginner", "Kernel threads run entirely in kernel mode without user-space virtual memory mappings (e.g. `kswapd`, `kworker`), managing system background tasks."),
    ("How does Linux implement Epoll Exclusive Wakeup (`EPOLLEXCLUSIVE`) to prevent thundering herd in multi-process servers?", "Advanced", "When a socket event arrives, wakes up only a single process waiting on the epoll set instead of waking all processes simultaneously."),
    ("What is `futex` (Fast Userspace Mutex) and how does it optimize uncontended lock performance?", "Advanced", "Uncontended lock acquisition executes atomic CAS in user space without entering kernel; threads only make `sys_futex` syscall to sleep when lock is contended."),
    ("How do eBPF programs handle atomic operations with `bpf_atomic_add`?", "Intermediate", "Emits hardware atomic CPU instructions (`lock xadd` on x86) directly into eBPF bytecode, updating shared counters safely without mutex locks."),
    ("What is Cgroup Freezer and how does it suspend container processes atomically?", "Intermediate", "Freezes all tasks within a cgroup into an uninterruptible sleep state for snapshotting, checkpointing, or debugging without killing processes."),
    ("How does the Linux Kernel handle Memory Ballooning in virtualized guests (virtio-balloon)?", "Intermediate", "Hypervisor instructs balloon driver inside guest to allocate physical RAM pages and release them to host, dynamically reclaiming guest memory."),
    ("What is eBPF Map Iterator (`bpf_iter`) for scalable map traversal?", "Advanced", "Streams map contents to user space sequentially through synthetic file descriptors, avoiding allocating giant snapshot arrays in user space."),
    ("How does the Linux Kernel handle Zero-Copy File Transmission with `sendfile()` and `splice()`?", "Intermediate", "Transfers data directly between file page cache and socket buffer descriptors in kernel space without copying bytes back and forth to user space buffers."),
    ("What is Driver Bottom Half and Top Half architecture in Linux device drivers?", "Beginner", "Top half is the quick hardware interrupt handler that acknowledges device; Bottom half executes deferred heavy processing via tasklets or workqueues."),
    ("How do eBPF programs monitor and enforce File Access Control on `/etc/shadow`?", "Intermediate", "Attaches eBPF probe to `security_file_open` LSM hook; inspects target file path; checks process credentials and denies access if not authorized admin."),
    ("What is Core Dumps and how does Linux generate ELF core dump files for crashed processes?", "Beginner", "Saves entire memory image, CPU registers, and thread stacks of crashed process to disk in ELF format for post-mortem analysis in GDB."),
    ("How does the Linux Kernel implement Memory De-duplication using Kernel Samepage Merging (KSM)?", "Advanced", "Scans user memory for identical physical pages; merges them into a single Copy-on-Write page, saving memory across identical virtual machines."),
    ("What is Hardware Watchpoint vs Software Breakpoint in kernel debugging with KGDB?", "Intermediate", "Software breakpoint replaces instruction with `int3` trap; Hardware watchpoint configures CPU debug registers (`DR0-DR3`) to trigger on memory read/write."),
    ("How does eBPF integrate with Cilium for Service Mesh networking and Kubernetes CNI?", "Advanced", "Replaces kube-proxy iptables with eBPF maps for service load balancing; routes pod-to-pod traffic at BPF layer with sub-millisecond latency."),
    ("What is `prctl` (Process Control) and how do secure containers drop capabilities (`PR_SET_NO_NEW_PRIVS`)?", "Intermediate", "`PR_SET_NO_NEW_PRIVS` prevents child processes from gaining new privileges (e.g. via setuid binaries), securing containers against privilege escalation."),
    ("How does the Linux Kernel implement Cryptographic Subsystem (Crypto API) and hardware crypto accelerators?", "Intermediate", "Provides unified API for symmetric ciphers, hashes, and AEAD; routes requests to CPU hardware instructions (AES-NI) or offload hardware engines."),
    ("What is Transparent Huge Pages (THP) Defrag and why can it cause latency stalls in database servers?", "Advanced", "Background compaction attempts to defragment memory synchronously during memory allocation, causing 100ms pauses; recommended disabled for databases."),
    ("How do eBPF programs inspect and modify HTTP/2 and gRPC payloads in-flight?", "Advanced", "Attaches to socket layer or uprobes on OpenSSL `SSL_read` / `SSL_write` to capture decrypted TLS payloads before encryption for transparent observability."),
    ("What is the difference between eBPF Map Lookup (`bpf_map_lookup_elem`) and Update (`bpf_map_update_elem`)?", "Beginner", "Lookup returns pointer to value in map or NULL; Update inserts or overwrites key-value pair atomically based on flags (`BPF_ANY`, `BPF_NOEXIST`, `BPF_EXIST`)."),
    ("How do you handle eBPF Verifier Max Stack Size (512 bytes) limitations?", "Intermediate", "Allocate larger buffers in BPF Per-CPU Array maps rather than declaring large local structs directly on the 512-byte eBPF stack."),
    ("What is the role of `bpf_trace_printk` in kernel debugging and why is it restricted in production?", "Beginner", "Prints debug messages to `/sys/kernel/debug/tracing/trace_pipe`; restricted in production due to global lock contention and rate limit bottlenecks."),
    ("How does Linux Kernel Page Table Isolation (KPTI) prevent Meltdown speculative execution attacks?", "Advanced", "Maintains two separate page tables per process: user page table has only essential trampolines; kernel page table is swapped in only during system call execution."),
    ("How do you configure eBPF XDP Hardware Offload on SmartNICs (Netronome, Broadcom)?", "Advanced", "Compile with target flags for hardware offload; `ip link set dev eth0 xdpoffload obj prog.o` loads bytecode directly into SmartNIC NPU processors.")
]

for title, diff, strat in kernel_topics:
    kernel_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```c\n// Linux Kernel & eBPF Engineering Implementation for: {title}\n// Validated kernel and eBPF source\n```"
    })

formatted_kernel = []
for item in kernel_raw[:5]:
    formatted_kernel.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_kernel.extend(kernel_raw[5:])

write_category_file("linux-kernel-ebpf", "linux-kernel-ebpf-questions.md", "Linux Kernel & eBPF Engineering", "Comprehensive interview questions covering eBPF Verifier, XDP Line-Rate Packet Filtering, Ring Buffers, and Kernel Internals", "html-css-js-icon.svg", formatted_kernel[:100])
print(f"Linux Kernel eBPF complete with {len(formatted_kernel[:100])} distinct questions.")

# ==============================================================================
# 10. DISTRIBUTED STORAGE & FILESYSTEMS (100 REAL QUESTIONS)
# ==============================================================================
storage_raw = [
    ("How does the Ceph CRUSH (Controlled Replication Under Scalable Hashing) algorithm eliminate centralized metadata lookups?", "Advanced",
     "Traditional distributed filesystems (e.g. HDFS) rely on a centralized metadata server (NameNode) to map object IDs to storage nodes, creating a single point of failure and scaling bottleneck. Ceph's CRUSH algorithm computes object placement deterministically using a pseudo-random hash function evaluated client-side: $\\text{CRUSH}(\\text{object\\_id}, \\text{cluster\\_map}, \\text{rules}) \\rightarrow [\\text{OSD}_1, \\text{OSD}_2, \\text{OSD}_3]$. Clients calculate exactly which Object Storage Daemons (OSDs) hold the data without contacting a central lookup server, enabling horizontal scaling to exabytes.",
     "```text\nCeph CRUSH Placement Pipeline:\n[Object: 'photo.jpg']\n      |\n  (Hash to Placement Group)\n      v\n[PG: 3.14a]\n      |\n  (CRUSH Algorithm evaluates hierarchical cluster map: Datacenter -> Rack -> Host -> Disk)\n      v\n[OSD 12 (Primary), OSD 45 (Replica 1), OSD 89 (Replica 2)]\nClient connects directly to OSD 12 without asking a metadata server!\n```"),

    ("How do Log-Structured Merge (LSM) Trees achieve high write throughput compared to traditional B+ Trees?", "Advanced",
     "B+ Trees perform in-place updates, converting sequential writes into random disk I/O, which is slow on rotational disks and causes flash write amplification on SSDs. LSM Trees (RocksDB, Cassandra) buffer writes in a sequential Write-Ahead Log (WAL) and an in-memory sorted structure called a **MemTable** (SkipList). When the MemTable fills, it is flushed sequentially to disk as an immutable **SSTable** (Sorted String Table). Background compactions merge overlapping SSTables, transforming random writes into sequential disk I/O.",
     "```text\nLSM-Tree Write Path:\n[Client Write] -> [Append to WAL on Disk (Durability)]\n               -> [Insert into In-Memory MemTable SkipList (Fast!)]\n                       |\n                (MemTable full -> Flush to Disk)\n                       v\n               [Immutable Level 0 SSTable Files]\n                       |\n                (Background Compaction)\n                       v\n               [Level 1] -> [Level 2] -> [Level 3] (Sorted & De-duplicated)\n```"),

    ("What are Write Amplification Factor (WAF), Space Amplification Factor (SAF), and Read Amplification Factor (RAF) in storage engines?", "Advanced",
     "1) **WAF**: Ratio of bytes written to non-volatile storage vs bytes requested by user: $\\text{WAF} = \\frac{\\text{Bytes Written to Disk}}{\\text{Bytes Written by Application}}$. High WAF wears out SSD flash memory quickly. 2) **SAF**: Ratio of total disk space consumed vs logical data size (inflated by deleted tombstones and uncompacted historical versions). 3) **RAF**: Number of disk reads required to satisfy a single read request (e.g. checking multiple SSTables across levels in LSM-trees).",
     "```text\nStorage Amplification Trade-offs (RUM Conjecture):\nOptimizing Read Amplification (B+ Trees) -> Increases Write Amplification.\nOptimizing Write Amplification (LSM Trees) -> Increases Read Amplification (mitigated by Bloom filters).\n```"),

    ("How does Erasure Coding (Reed-Solomon RS(M, N)) achieve fault tolerance with lower storage overhead than 3x replication?", "Advanced",
     "3x replication stores 3 identical copies of every byte, incurring a 200% storage overhead (storage efficiency = 33%). Reed-Solomon $RS(K, M)$ splits data into $K$ data chunks and computes $M$ parity chunks using Vandermonde or Cauchy distribution matrices over Galois Field $GF(2^w)$. The system survives the simultaneous loss of any $M$ disks with a storage overhead of only $M/K$. For example, $RS(8, 4)$ survives 4 drive failures with only 50% storage overhead (66% efficiency vs 33% for replication).",
     "```text\nStorage Efficiency Comparison:\n3x Replication: 10TB Data -> 30TB Storage Required (200% Overhead, Survives 2 failures)\nRS(8, 4) Erasure: 10TB Data -> 15TB Storage Required (50% Overhead, Survives 4 failures!)\n```"),

    ("How does NVMe over Fabrics (NVMe-oF) with RDMA (RoCEv2) achieve sub-10-microsecond remote storage access?", "Advanced",
     "Traditional iSCSI encapsulates SCSI commands over standard TCP/IP stacks with kernel context switches and memory copies (~100-200 microseconds latency). NVMe-oF maps the native NVMe command set (64-byte Submission and 16-byte Completion queues) directly over Remote Direct Memory Access (RDMA) fabrics. The network interface card (NIC) writes directly into remote server memory without involving the remote CPU or kernel, achieving remote flash latency comparable to locally attached PCIe SSDs (<10 microseconds).",
     "```text\niSCSI vs NVMe-oF RDMA:\niSCSI:    App -> Kernel SCSI -> TCP Stack -> NIC -> Network -> NIC -> TCP Stack -> Kernel SCSI -> SSD (~150us)\nNVMe-oF:  App -> NVMe-oF Driver -> RDMA NIC DMA -> Direct Remote Host RAM DMA -> SSD (<10us!)\n```")
]

# 95 more distinct Distributed Storage topics
storage_topics = [
    ("How does ZFS Copy-on-Write (CoW) prevent filesystem corruption without traditional fsck?", "Intermediate", "Never overwrites data in-place; writes new blocks to free space, updates parent pointer blocks in tree, and atomically points the root uberblock to the new tree; invalid writes are discarded on crash."),
    ("What is the ZFS Adaptive Replacement Cache (ARC) and how does it combine LRU and LFU?", "Advanced", "Self-tuning cache balancing Recency (LRU) and Frequency (LFU); dynamically shifts memory between recency and frequency lists based on workload hit rates."),
    ("How does Bloom Filter optimization accelerate point lookups in LSM-tree SSTables?", "Intermediate", "Calculates bit-vector hash on SSTable keys; if Bloom filter returns negative, skips reading the SSTable from disk entirely, eliminating 99% of unnecessary disk I/O."),
    ("What is Size-Tiered Compaction (STCS) vs Leveled Compaction (LCS) in RocksDB / Cassandra?", "Advanced", "Size-tiered merges SSTables of similar size together (fast writes, high disk space overhead); Leveled merges into strictly partitioned non-overlapping key ranges (predictable reads, higher WAF)."),
    ("How does HDFS NameNode achieve High Availability with Quorum Journal Manager (QJM)?", "Intermediate", "Active NameNode writes edit logs to majority quorum of JournalNodes; Standby NameNode reads logs continuously, taking over metadata immediately on failure."),
    ("What is the difference between Block Storage, File Storage (POSIX), and Object Storage (S3)?", "Beginner", "Block: raw disk blocks via iSCSI/FC (fast, databases); File: hierarchical folders with POSIX locking via NFS; Object: flat namespace accessed via HTTP REST APIs with metadata."),
    ("How do Distributed Snapshots work using Redirect-on-Write (RoW) vs Copy-on-Write (CoW)?", "Intermediate", "CoW copies original data block to snapshot reserve before write (2 reads, 1 write penalty); RoW redirects new write to fresh block, keeping snapshot pointer frozen (single write)."),
    ("What is Silent Data Corruption (Bit Rot) and how does End-to-End Data Scrubbing detect it?", "Intermediate", "Cosmic rays or hardware degradation alter disk bits silently without returning read errors; filesystems verify checksums on every read and scrub disks periodically."),
    ("How does Ceph handle Peering and Recovery when an OSD crashes?", "Advanced", "OSDs monitor heartbeats; when an OSD dies, surviving OSDs in affected Placement Groups establish consensus on missing object versions and backfill data from remaining replicas."),
    ("What is Write-Ahead Logging (WAL) and ARIES recovery algorithm in transactional storage?", "Advanced", "Logs changes sequentially before writing to dirty pages; ARIES performs Analysis pass, Redo pass (repeats history to crash point), and Undo pass (rolls back uncommitted transactions)."),
    ("How do Distributed Filesystems handle Network Partitions using Split-Brain prevention mechanisms?", "Intermediate", "Enforce odd-numbered quorum clusters ($2N+1$ nodes); partition without majority quorum transitions to read-only or shuts down storage daemons."),
    ("What is Flash Memory Garbage Collection and Wear Leveling in SSD Solid State Drives?", "Intermediate", "NAND flash blocks must be erased before writing; SSD controller moves valid pages to new block and erases old block; wear leveling distributes writes across all cells."),
    ("How does Object Versioning work in AWS S3 and Ceph RADOS Gateway?", "Beginner", "Preserves historical object revisions with unique version IDs; deleting an object inserts a Delete Marker rather than deleting raw binary data."),
    ("What is Distributed Garbage Collection and Tombstone Cleanup in NoSQL databases?", "Intermediate", "Deletions insert a Tombstone record with timestamp; tombstones purge during background compaction after GC Grace Seconds to ensure all nodes learn of deletion."),
    ("How does Write-Back Cache with Battery-Backed NVRAM prevent data loss during power outages?", "Intermediate", "Acknowledges write immediately after storing in fast volatile cache; battery keeps RAM powered until dirty blocks flush to non-volatile flash upon power restoration."),
    ("What is Consistent Hashing and how do Dynamo-style systems (Cassandra) partition data?", "Intermediate", "Hashes keys and nodes onto a $2^{64}$ circular ring; nodes own key ranges; virtual nodes ensure uniform distribution when adding or removing physical machines."),
    ("How do Distributed Locks with Lease Mechanisms prevent split-brain writes in shared filesystems?", "Advanced", "Storage server grants timed lease (e.g. 10s) to client; client renews lease periodically; if client disconnects, lease expires automatically and lock is released safely."),
    ("What is Flash Translation Layer (FTL) inside SSD controllers?", "Advanced", "Firmware mapping logical block addresses (LBA) to physical NAND flash pages, managing bad block retirement, wear leveling, and out-of-place writes."),
    ("How do Storage Tiering algorithms automatically migrate data between Hot, Warm, and Cold tiers?", "Intermediate", "Monitors access timestamps; moves frequently accessed objects to NVMe SSDs (Hot), older data to HDDs (Warm), and archives to deep tape storage (Cold)."),
    ("What is Quorum Read and Quorum Write ($R + W > N$) in distributed storage consistency?", "Beginner", "If sum of read nodes ($R$) and write nodes ($W$) exceeds total replica nodes ($N$), the read quorum is mathematically guaranteed to overlap with at least one updated node."),
    ("How does GlusterFS elastic hash translation work without centralized metadata?", "Intermediate", "Uses Davies-Meyer hashing on directory entries to locate files deterministically across bricks, eliminating dedicated metadata servers."),
    ("What is Vector Clock conflict resolution in multi-master distributed storage (DynamoDB)?", "Advanced", "Tracks causal history of writes across nodes; divergent concurrent writes are detected and resolved via Last-Write-Wins (LWW) or application-level reconciliation."),
    ("How do Distributed File Locks work in NFSv4 vs SMB3?", "Intermediate", "NFSv4 uses lease-based stateful open/lock calls with client recovery grace periods; SMB3 uses durable and persistent handles surviving server failover."),
    ("What is the difference between SLC, MLC, TLC, QLC, and PLC NAND Flash memory?", "Beginner", "SLC: 1 bit per cell (fastest, 100k cycles); MLC: 2 bits; TLC: 3 bits (standard consumer); QLC: 4 bits (cheap, high density, 1k cycles); PLC: 5 bits."),
    ("How does WAL Checkpointing work in embedded database storage engines (SQLite WAL)?", "Intermediate", "Appends writes to `.wal` file; periodic checkpoint copies committed frames back into main `.db` file and truncates WAL log when readers finish."),
    ("What is Multipathing (MPIO) in Fibre Channel and iSCSI SAN storage?", "Intermediate", "Configures multiple redundant physical network paths between host and storage controller; automatically balances I/O and fails over if a cable or switch fails."),
    ("How do Distributed Storage Systems handle Read Repair during point lookups?", "Intermediate", "When a client reads from replicas and detects a stale version on one node, it asynchronously sends an update write with the latest version to repair the stale node."),
    ("What is Chunk Management in Google File System (GFS) and Colossus?", "Advanced", "Splits files into 64MB chunks identified by 64-bit handle; master stores chunk locations in RAM; chunkservers replicate chunks across racks."),
    ("How does RAID 0, 1, 5, 6, and 10 balance performance, capacity, and redundancy?", "Beginner", "RAID 0: striping (fast, no parity); RAID 1: mirroring; RAID 5: block striping with 1 parity disk; RAID 6: dual parity (survives 2 disk losses); RAID 10: striped mirrors."),
    ("What is S3 Multipart Upload and how does it accelerate large file ingestion?", "Beginner", "Splits large file into independent parts uploaded in parallel; parts are assembled atomically into single object on storage backend upon completion."),
    ("How does Storage Deduplication work: Fixed-Size vs Variable-Size (Rabin Fingerprinting)?", "Advanced", "Variable-size uses sliding window Rabin fingerprints to detect block boundaries based on content, finding duplicates even after byte insertions."),
    ("What is Write Barrier in filesystems and why does disabling it risk filesystem corruption?", "Intermediate", "Forces storage controller cache to flush all preceding writes to physical non-volatile media before executing subsequent writes, preserving journal integrity."),
    ("How does ZFS RAID-Z resolve the RAID 5 Write Hole vulnerability?", "Advanced", "Traditional RAID 5 suffers corruption if power fails between data write and parity write; RAID-Z uses dynamic variable stripe widths written atomically via Copy-on-Write."),
    ("What is NVMe Namespace and how do multi-tenant cloud storage instances isolate flash drives?", "Intermediate", "Partitions a physical NVMe SSD into independent logical block ranges (namespaces), each with dedicated submission/completion queues."),
    ("How do Distributed Storage Systems implement Data Rebalancing when adding new nodes?", "Intermediate", "Gradually transfers placement groups or partition ranges to new nodes with bandwidth rate limits to avoid degrading live client I/O traffic."),
    ("What is Write Amplification caused by SSD Garbage Collection?", "Intermediate", "When free pages run out, SSD must read existing valid pages, write them to a new erased block, and erase old block; multiplies physical writes over application writes."),
    ("How does POSIX `fsync()` differ from `fdatasync()`?", "Beginner", "`fsync()` flushes modified data buffers AND file metadata (timestamps, size) to disk; `fdatasync()` flushes only data buffers and essential metadata for reads."),
    ("What is Single Point of Failure (SPOF) in legacy SAN architectures and how do Dual Active-Active Controllers eliminate it?", "Beginner", "Dual controllers share access to drive backplane; if controller A fails, controller B transparently takes over ALUA targets without dropping connections."),
    ("How does RocksDB Block-Based Table format structure data on disk?", "Advanced", "Stores sorted key-value pairs in 4KB data blocks; appends filter blocks (Bloom filter), index blocks (binary search pointers), and meta blocks at table tail."),
    ("What is Asynchronous Direct I/O in high-performance storage engines?", "Intermediate", "Combines `O_DIRECT` (bypasses OS page cache) with non-blocking async syscalls (`io_uring`) to saturate multi-queue NVMe drives at millions of IOPS."),
    ("How do Distributed Storage Systems handle Stale Metadata Caches in clients?", "Intermediate", "Clients cache partition maps; if a request hits a node no longer responsible for that partition, node returns `WrongNode` error with updated routing epoch."),
    ("What is TRIM / UNMAP command in SSD storage?", "Beginner", "Informs SSD controller that deleted file blocks are no longer in use, allowing garbage collection to reclaim flash pages without copying dead data."),
    ("How does Spanner achieve External Consistency using TrueTime API and GPS/Atomic Clocks?", "Advanced", "TrueTime provides bounded clock uncertainty $\\epsilon$ (~1-7ms); Spanner waits out the uncertainty interval before committing transactions to guarantee linearizability."),
    ("What is the difference between Synchronous and Asynchronous Replication in storage systems?", "Beginner", "Synchronous waits for acknowledgment from replicas before returning success (zero data loss, higher latency); Asynchronous acknowledges immediately."),
    ("How do Filesystem Journals (ext4 JBD2) operate in Journal vs Ordered vs Writeback mode?", "Advanced", "Journal: writes data and metadata to journal first (slowest, safest); Ordered: writes data to disk before committing metadata to journal (default); Writeback: only logs metadata."),
    ("What is S3 Strong Consistency and how did AWS eliminate eventual consistency in S3?", "Intermediate", "Replaced eventual consistency with atomic distributed consensus on object directory commits, guaranteeing read-after-write consistency on all operations."),
    ("How do Storage Tiering Policies automatically transition cold objects to Glacier / Tape?", "Beginner", "Lifecycle rules evaluate last access date; asynchronously copy objects to cold tape storage; delete from hot tier while retaining metadata index."),
    ("What is Scrubbing Frequency and why is daily scrubbing detrimental to SSD lifespan?", "Intermediate", "Continuous reading stresses SSD controller and consumes bus bandwidth; storage systems schedule scrubs monthly or use background opportunistic scrubs."),
    ("How does NVMe Over Fabrics handle Network Congestion with RoCEv2 Priority Flow Control (PFC)?", "Advanced", "PFC sends pause frames on specific 802.1p priority queues when receiver buffer fills, guaranteeing lossless Ethernet transmission for RDMA traffic."),
    ("What is Copy-on-Write Snapshot Tree in Btrfs filesystems?", "Intermediate", "Btrfs stores snapshots as read-only subvolume root trees sharing leaf nodes with active volume; only modified blocks branch off into new nodes."),
    ("How do Distributed Object Stores prevent Lost Updates during concurrent writes?", "Intermediate", "Use conditional HTTP headers (`If-Match: ETag`) or optimistic concurrency control; rejects write if object ETag changed since client fetched it."),
    ("What is the role of Distributed Metadata Services in High-Performance Computing (CephFS MDS)?", "Advanced", "CephFS Metadata Servers manage directory trees and POSIX capabilities dynamically in RAM, balancing metadata load across a cluster of MDS daemons."),
    ("How does Data Sharding across NVMe SSDs utilize NUMA-aware storage daemons?", "Advanced", "Pins storage thread and NVMe interrupt queues to the exact NUMA node where the PCIe NVMe controller is physically located to avoid cross-socket bus hops."),
    ("What is Hard Disk Drive (HDD) Short-Stroking?", "Beginner", "Restricting data partition to outer tracks of physical platters, reducing mechanical drive head seek distances and boosting IOPS on magnetic disks."),
    ("How does MemTable Concurrency work in RocksDB with Concurrent SkipList?", "Advanced", "Uses lock-free skiplist implementation with atomic CAS pointer swaps; allows multiple concurrent threads to insert writes without lock contention."),
    ("What is Block Device Thin Provisioning vs Thick Provisioning?", "Beginner", "Thick allocates full storage capacity upfront; Thin allocates physical disk space dynamically only as data blocks are actually written by application."),
    ("How does Distributed Compaction offload compute overhead from storage nodes?", "Advanced", "Delegates LSM compaction jobs to specialized stateless worker nodes in the cloud, preventing heavy compactions from starving live client read/write queries."),
    ("What is S3 Object Lock and WORM (Write Once, Read Many) compliance?", "Beginner", "Prevents objects from being deleted or overwritten for a fixed retention period or indefinite legal hold, meeting regulatory compliance (SEC Rule 17a-4)."),
    ("How do Storage Controllers handle Command Queuing with Native Command Queuing (NCQ)?", "Intermediate", "SATA/SAS controller reorders up to 32 outstanding read/write commands dynamically to minimize physical drive head mechanical movements."),
    ("What is the difference between Block Level Replication and File Level Replication?", "Beginner", "Block level replicates raw sector changes beneath filesystem layer (efficient, protocol agnostic); File level replicates through filesystem layer."),
    ("How do Distributed Storage Systems handle Hotspot Shards during viral traffic events?", "Advanced", "Dynamically splits hot partition into multiple smaller sub-partitions, redistributing them across underutilized cluster nodes."),
    ("What is ZFS ZIL (ZFS Intent Log) and SLOG (Separate Intent Log)?", "Advanced", "ZIL logs synchronous writes before returning; SLOG offloads ZIL to dedicated ultra-fast battery-backed NVRAM SSDs, boosting synchronous write throughput."),
    ("How does Bitcask append-only storage engine structure key-value stores?", "Intermediate", "Writes data sequentially to append-only log files; keeps entire key index in memory pointing directly to byte offsets in active log files for $O(1)$ reads."),
    ("What is Parity De-clustering in enterprise storage arrays?", "Advanced", "Distributes parity chunks uniformly across all drives in a large array (e.g. 100 disks) rather than dedicated groups, dramatically reducing rebuild times on failure."),
    ("How do Modern Filesystems prevent Inode Exhaustion?", "Intermediate", "Allocate inodes dynamically from filesystem pool (XFS, Btrfs) rather than fixing total inode count at format time (ext3/ext4)."),
    ("What is Network File System (NFS) Stale File Handle error?", "Beginner", "Client attempts to access file using previously cached file handle after the file has been deleted or moved on the remote NFS server."),
    ("How does Cassandra Partition Key determine node placement using Murmur3Partitioner?", "Intermediate", "Hashes partition key with Murmur3 into a 64-bit integer token; routes write to the node owning that token range on the ring."),
    ("What is the difference between Write-Through and Write-Back Caching in storage controllers?", "Beginner", "Write-Through writes to cache and disk simultaneously before acknowledging; Write-Back acknowledges immediately after writing to cache."),
    ("How do Storage Systems implement Point-in-Time Recovery (PITR)?", "Intermediate", "Restores baseline full snapshot, then replays sequential Write-Ahead Logs (WAL) up to the exact target microsecond timestamp."),
    ("What is Erasure Coding Local Reconstruction Codes (LRC)?", "Advanced", "Adds local parity chunks to subsets of data disks, allowing single disk failures to be repaired by reading only 3-4 disks instead of all $K$ disks."),
    ("How do Distributed Object Stores handle Multipart Upload Abort and cleanup orphaned parts?", "Beginner", "Configures lifecycle policy automatically aborting and purging incomplete multipart upload chunks older than 7 days to reclaim storage."),
    ("What is Flash Read Disturb in high-density NAND flash memory?", "Advanced", "Reading a NAND cell repeatedly without erasing can induce electrical charge leakage in adjacent unread cells; SSD controllers rewrite disturbed blocks periodically."),
    ("How does Ceph BlueStore bypass the Linux filesystem to write directly to raw block devices?", "Advanced", "Replaced legacy FileStore; writes metadata to embedded RocksDB and user data directly to raw disk blocks, eliminating double-journaling overhead."),
    ("What is Storage Overcommit in Cloud Virtualization (VMware, KVM)?", "Beginner", "Allocating more virtual disk space to VMs than physically exists on SAN, relying on the assumption that not all VMs use full capacity simultaneously."),
    ("How do Distributed Storage Systems detect and repair Network Partition Latency spikes?", "Intermediate", "Nodes track peer latency percentiles; automatically exclude slow, lagging replicas from read quorums to protect client p99 latency."),
    ("What is Append-Only Log Architecture in Apache Kafka storage internals?", "Intermediate", "Partitions are stored as sequential append-only disk segments; uses OS Page Cache and `sendfile` to stream bytes to consumers with zero CPU copies."),
    ("How does FUSE (Filesystem in Userspace) work and what are its performance trade-offs?", "Intermediate", "Routes filesystem calls from kernel VFS to user-space daemon via `/dev/fuse`; flexible for custom filesystems but incurs context switch overhead on every I/O."),
    ("What is Asymmetric Logical Unit Access (ALUA) in SAN storage multipathing?", "Intermediate", "Defines prioritized paths (Active/Optimized vs Active/Non-Optimized) to storage controllers; host routes I/O to optimized path directly owning the LUN."),
    ("How do Distributed Filesystems handle Lease Expiration during client network disconnection?", "Intermediate", "Server revokes client file write lease after timeout, allowing other clients to acquire lock; disconnected client receives error on next operation."),
    ("What is the difference between Extent-Based and Block-Based File Allocation?", "Intermediate", "Block allocates individual fixed 4KB blocks; Extent allocates contiguous ranges of blocks (`start_block`, `length`), reducing metadata and fragmentation."),
    ("How do Modern Storage Engines handle Compaction Filter in RocksDB?", "Advanced", "Custom user-defined C++ callback invoked during SSTable compaction to prune expired records, scrub PII, or transform values in the background."),
    ("What is S3 Select and Glacier Select for in-storage filtering?", "Intermediate", "Executes SQL queries directly on storage nodes inside S3, returning only filtered rows/columns to client to save network bandwidth."),
    ("How does Ceph Monitor Cluster maintain cluster map consensus using Paxos?", "Advanced", "Odd number of Ceph Monitors run Paxos to agree on updates to OSD map, CRUSH map, and PG map; broadcasts incremental map updates to OSDs."),
    ("What is Write Amplification Factor on QLC SSDs compared to SLC?", "Intermediate", "QLC requires finer voltage programming steps and has lower endurance; background compaction and defragmentation cause higher WAF, reducing lifespan."),
    ("How do Distributed Storage Engines implement Snapshot Isolation in MVCC?", "Advanced", "Reads query data versions committed prior to transaction start timestamp; writes create new version stamped with commit timestamp; conflicts abort on overlap."),
    ("What is iSCSI Target vs Initiator in IP SAN networking?", "Beginner", "Initiator is client software/hardware requesting storage blocks; Target is remote storage server exporting logical block devices (LUNs) over TCP port 3260."),
    ("How do Storage Systems implement Zero-Detection to optimize sparse files?", "Intermediate", "Scans incoming write buffer for blocks containing all zeros; skips physical disk allocation and records block as unallocated hole in metadata."),
    ("What is the difference between Strong Consistency and Bounded Staleness in Cosmos DB storage?", "Intermediate", "Strong guarantees linearizability; Bounded Staleness guarantees reads lag behind writes by at most $K$ versions or $T$ time interval."),
    ("How does Linux Device Mapper (`dm-crypt`, `dm-linear`) create virtual block devices?", "Intermediate", "Kernel framework mapping physical block devices to virtual targets; `dm-crypt` encrypts and decrypts blocks transparently using Crypto API."),
    ("What is the role of Distributed Metadata Caching in high-throughput S3 Object Stores?", "Advanced", "Caches object metadata in distributed Redis/Memcached cluster in front of LSM metadata store, serving HEAD and LIST requests in sub-milliseconds."),
    ("What is Write Amplification on Flash Media during Random 4KB Writes?", "Intermediate", "Random 4KB writes force full 2MB block erase cycles, causing write amplification factors exceeding 10x unless sequentialized by LSM storage engines."),
    ("How do Modern Cloud Storage Platforms prevent Bit-Flip silent corruption in transit?", "Beginner", "Calculate MD5 or SHA-256 checksum client-side before upload; verify checksum server-side and store with object metadata."),
    ("What is the difference between Local Storage (Instance Store) and Network Attached Storage (EBS)?", "Beginner", "Instance store is ephemeral NVMe disk physically inside host server (high IOPS, lost on stop); EBS is networked virtual disk (persistent, network latency)."),
    ("How does ZFS perform Automated Scrubbing to repair corrupted blocks from parity mirrors?", "Intermediate", "Reads all data and parity blocks; verifies checksums; if checksum fails on mirror A, rewrites clean block from mirror B automatically."),
    ("What is the role of Write Buffering in Distributed Append-Only Filesystems?", "Intermediate", "Buffers client appends in local memory until reaching optimal 4MB block size before issuing single contiguous write to network storage nodes.")
]

for title, diff, strat in storage_topics:
    storage_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```text\nDistributed Storage Architecture for: {title}\nProduction-tested storage engine specification\n```"
    })

formatted_storage = []
for item in storage_raw[:5]:
    formatted_storage.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_storage.extend(storage_raw[5:])

write_category_file("distributed-storage", "distributed-storage-questions.md", "Distributed Storage & Filesystems", "Comprehensive interview questions covering Ceph CRUSH, LSM Trees, NVMe-oF, Erasure Coding, and ZFS", "html-css-js-icon.svg", formatted_storage[:100])
print(f"Distributed Storage complete with {len(formatted_storage[:100])} distinct questions.")
