import os
import sys
sys.path.append(os.path.dirname(__file__))
from writer_helper import write_category_file

# ==============================================================================
# 5. LOW-LATENCY FINTECH & HFT (100 REAL QUESTIONS)
# ==============================================================================
fintech_raw = [
    ("How does Kernel Bypass Networking (DPDK, Solarflare EF_VI, OpenOnload) achieve sub-microsecond tick-to-trade latency?", "Advanced",
     "Standard Linux networking copies packets through multiple kernel layers (NIC driver -> SKB allocation -> IP stack -> socket buffer -> user space), incurring context switches, softirqs, and memory copies (~5-15 microseconds). Kernel bypass maps the NIC's ring buffer memory directly into user-space virtual address space. User-space polling loops read raw Ethernet frames directly from PCIe registers, eliminating interrupts and OS context switches, reducing roundtrip latency to <800 nanoseconds.",
     "```cpp\n// Solarflare EF_VI Zero-Copy Packet Receive Loop\n#include <etherfabric/vi.h>\n\nvoid poll_market_data(ef_vi* vi, ef_memreg* mr, void* pkt_buf) {\n    ef_event evs[16];\n    while (true) {\n        int n_ev = ef_eventq_poll(vi, evs, 16);\n        for (int i = 0; i < n_ev; ++i) {\n            if (EF_EVENT_TYPE(evs[i]) == EF_EVENT_TYPE_RX) {\n                const char* payload = (const char*)pkt_buf + EF_EVENT_RX_RQ_ID(evs[i]);\n                process_market_tick(payload); // Zero-copy processing!\n            }\n        }\n    }\n}\n```"),

    ("What is False Sharing and how do you prevent Cache Line Bouncing using Cache-Line Alignment (`alignas(64)`)?", "Advanced",
     "Modern x86 CPUs maintain L1/L2 cache coherence via the MESI protocol in 64-byte cache line chunks. If two independent variables accessed by different CPU cores reside on the same 64-byte cache line, modifying one variable invalidates the other core's cache line, forcing bus snooping and memory stalls (False Sharing). Solved by aligning independent atomic variables to 64-byte boundaries with padding.",
     "```cpp\n#include <atomic>\n#include <new>\n\nstruct alignas(64) CacheAlignedCounter {\n    std::atomic<uint64_t> count{0};\n    char padding[64 - sizeof(std::atomic<uint64_t>)]; // Guarantees private cache line\n};\n```"),

    ("How does the LMAX Disruptor Pattern achieve lock-free high-throughput concurrency over standard queues?", "Advanced",
     "Standard queues (e.g. `BlockingQueue`) suffer from lock contention, dynamic memory allocation per node, and cache misses. The Disruptor pre-allocates a contiguous circular Ring Buffer sized to a power of 2 (enabling bitwise mask indexing `seq & (size - 1)`). Producers claim sequential sequence numbers using lock-free CAS operations; consumers poll sequence barriers without locks, maximizing CPU L1/L2 instruction cache locality.",
     "```cpp\n// Lock-Free Ring Buffer Index Calculation\nconstexpr size_t RING_SIZE = 1024 * 1024; // Power of 2\nconstexpr size_t MASK = RING_SIZE - 1;\n\ninline size_t get_index(uint64_t sequence) {\n    return sequence & MASK; // Fast bitwise AND instead of expensive modulo (%)\n}\n```"),

    ("How do you design a High-Performance Limit Order Book (LOB) matching engine with O(1) order insertion and cancellation?", "Advanced",
     "Represent price levels in a dual structure: 1) A doubly linked list of orders at each price level preserving price-time FIFO priority. 2) A hash map or fixed-size array mapping `order_id` directly to the `Order` node pointer for $O(1)$ cancellation. 3) A sparse price array or AVL/Radix tree of active price levels for $O(1)$ Best-Bid-Offer (BBO) lookup.",
     "```cpp\nstruct Order {\n    uint64_t order_id;\n    uint32_t price;\n    uint32_t qty;\n    Order* prev;\n    Order* next;\n};\n\nstruct PriceLevel {\n    uint32_t price;\n    Order* head;\n    Order* tail;\n};\n// order_map[order_id] gives O(1) pointer to directly splice node out on cancel\n```"),

    ("What is Simple Binary Encoding (SBE) and how does it outperform JSON and Protobuf in financial market data feeds?", "Advanced",
     "SBE encodes fields at fixed binary byte offsets matching native hardware word alignments. Unlike Protobuf (which requires variable-length varint parsing) or JSON (which requires text parsing), SBE requires zero decoding logic: data fields are accessed by direct pointer casting (`*(uint64_t*)(buf + offset)`), achieving zero-allocation and single-cycle CPU reads.",
     "```cpp\n// Direct Zero-Copy SBE Field Access via Memory Pointer\n#pragma pack(push, 1)\nstruct MarketUpdateSBE {\n    uint16_t msg_type;\n    uint64_t timestamp_ns;\n    uint32_t symbol_id;\n    int64_t  price_mantissa;\n    int8_t   price_exponent;\n    uint32_t quantity;\n};\n#pragma pack(pop)\n```")
]

# 95 more distinct FinTech topics
fintech_topics = [
    ("How do you configure Linux CPU Core Isolation (`isolcpus`, `nohz_full`, `rcu_nocbs`) for HFT trading processes?", "Advanced", "Isolates dedicated CPU cores from the OS scheduler, eliminates timer interrupt ticks (`nohz_full`), and routes RCU callbacks away from trading threads."),
    ("What are Memory Barriers and C++ memory models (`memory_order_relaxed`, `acquire`, `release`, `seq_cst`)?", "Advanced", "Acquire/Release semantics guarantee writes before a release store are visible to threads performing an acquire load, avoiding expensive `seq_cst` memory fences."),
    ("How do you eliminate Garbage Collection pauses in Java HFT systems (Chronicle Queue, Agrona, Object Pooling)?", "Advanced", "Pre-allocate all objects off-heap in native memory, use flat byte buffers (Agrona DirectBuffer), and avoid creating short-lived objects on the JVM heap."),
    ("What is Branch Prediction and how do compiler hints (`[[likely]]`, `[[unlikely]]`, PGO) reduce pipeline stalls?", "Intermediate", "Predicts outcome of conditional branches to keep the CPU instruction pipeline full; incorrect predictions cause 15-20 cycle pipeline flushes."),
    ("How do you implement Lock-Free Single-Producer Single-Consumer (SPSC) Ring Buffers in C++?", "Advanced", "Use head and tail sequence atomic integers with `memory_order_relaxed` for local reads and `acquire`/`release` for cross-thread synchronization."),
    ("What is Precision Time Protocol (PTP IEEE 1588) and how do hardware NIC timestamping chips achieve nanosecond accuracy?", "Advanced", "PTP synchronizes clocks over Ethernet with sub-microsecond precision; hardware NICs record hardware PHY timestamps at the exact moment the start-of-frame delimiter passes."),
    ("How do you handle Market Data Feed Gaps and packet loss over Multicast UDP?", "Advanced", "Monitor sequence numbers on multicast feed; on missing sequence, request historical replay from TCP historical recovery servers."),
    ("What is the FIX (Financial Information eXchange) Protocol and what is FIX FAST compression?", "Intermediate", "Standard ASCII tag-value protocol for financial messaging (`35=D` for New Order Single); FAST compresses FIX using implicit dictionaries and delta encoding."),
    ("How do you optimize NUMA (Non-Uniform Memory Access) node affinity for trading threads and NICs?", "Advanced", "Bind trading threads to CPU cores on the exact NUMA socket physically wired to the PCIe slot of the 10GbE network card using `numactl --cpunodebind`."),
    ("What is Total Cost of Ownership (TCO) of FPGA vs Software matching engines?", "Intermediate", "FPGAs achieve deterministic ~100-300ns tick-to-trade latency in hardware gates, but have high compilation times and complex development cycles."),
    ("How do you handle Order Book Crosses and Locked Markets in algorithmic market making?", "Intermediate", "Detect when Best Bid >= Best Ask; automatically execute crossing orders or route aggressive orders to clear arbitrage opportunities."),
    ("What is Volume Weighted Average Price (VWAP) and how do algorithmic execution strategies minimize market impact?", "Intermediate", "Slices large institutional orders into small blocks scheduled proportionally to historical intraday volume curves to avoid moving the market price."),
    ("How do you design a Risk Gateway checking Pre-Trade Risk Controls in under 100 nanoseconds?", "Advanced", "Check price collars, fat-finger size limits, and credit limits using bitwise operations on cached in-memory structures before sending orders to exchange."),
    ("What is the difference between Colocation (Colo) and Proximity Hosting in financial exchanges?", "Beginner", "Colocation places trading servers inside the exchange's private datacenter with equal-length fiber optic cables to eliminate distance latency."),
    ("How do you prevent Thread Context Switching using busy-wait spin loops?", "Intermediate", "Trade thread runs an infinite `while (true)` loop with CPU pause instructions (`_mm_pause()`), avoiding OS thread sleep and wake-up latencies."),
    ("What is Time-Weighted Average Price (TWAP) execution and how does it differ from VWAP?", "Beginner", "TWAP slices an order evenly across fixed time intervals throughout the day regardless of volume; VWAP weights slices by volume distribution."),
    ("How do you optimize Serialization using FlatBuffers for financial telemetry?", "Intermediate", "FlatBuffers encodes data in binary format that can be read directly in-place without memory allocation or unpack passes."),
    ("What is Crossing Network and Dark Pool matching engine architecture?", "Intermediate", "Matches anonymous orders off public exchanges without displaying quotes on public order books, preventing front-running on large institutional blocks."),
    ("How do you implement atomic Price-Time Priority matching in an order book?", "Intermediate", "Orders at the best price are executed first; orders at the same price are filled in chronological order of arrival (FIFO)."),
    ("What is the difference between Market Orders, Limit Orders, and Stop-Loss Orders?", "Beginner", "Market: executes immediately at best available price; Limit: executes only at specified price or better; Stop-Loss: triggers market order when price drops to stop level."),
    ("How do you profile cache misses using Linux `perf` and Hardware Performance Counters?", "Advanced", "Run `perf stat -e L1-dcache-load-misses,LLC-load-misses ./engine` to detect instructions causing memory stalls."),
    ("What is SIMD (Single Instruction, Multiple Data) and how does AVX-512 accelerate order valuation?", "Advanced", "Processes 8 double-precision or 16 single-precision floating point numbers in a single CPU instruction, evaluating options pricing models in parallel."),
    ("How do you design an Order State Machine (Pending New, New, Partially Filled, Filled, Canceled)?", "Intermediate", "Maintain state transitions with strict validation rules; reject cancellation requests for already filled orders atomically."),
    ("What is Synthetic Spread Trading and how do statistical arbitrage algorithms identify mean-reversion?", "Intermediate", "Calculate cointegration between two correlated assets (e.g. Shell vs BP); buy undervalued leg and short overvalued leg when spread diverges by 2 standard deviations."),
    ("How do you implement Zero-Allocation Ring Buffers for high-throughput market logging?", "Advanced", "Pre-allocate fixed-size byte slots in a memory-mapped file; producer writes directly into mapped buffer using atomic sequence increment."),
    ("What is the difference between Direct Market Access (DMA) and Sponsored Access?", "Intermediate", "DMA routes orders through broker's infrastructure; Sponsored Access allows trading firm to connect directly to exchange using broker's participant ID with ultra-fast risk checks."),
    ("How do you mitigate Tail Latency (p99.99) spikes caused by Linux kernel page faults?", "Advanced", "Lock all application virtual memory into physical RAM using `mlockall(MCL_CURRENT | MCL_FUTURE)` to prevent OS from swapping pages to disk."),
    ("What is the ITCH and OUCH protocol suite used by NASDAQ?", "Intermediate", "ITCH is the outbound binary market data protocol broadcasting order additions, cancellations, and trades; OUCH is the inbound order entry protocol."),
    ("How do you calculate Implied Volatility using Black-Scholes and Newton-Raphson approximation?", "Advanced", "Iteratively refine volatility guess until the theoretical Black-Scholes option price matches the observed market market price."),
    ("What is the role of Garbage-Free Collections in HFT Java development?", "Intermediate", "Use primitive collections (Koloboke, FastUtil, Trove) that store unboxed `long` and `int` primitives without creating `java.lang.Long` wrapper objects."),
    ("How do you implement Lock-Free Multi-Producer Single-Consumer (MPSC) Queues?", "Advanced", "Producers use atomic exchange (`atomic::exchange`) to update queue tail; consumer traverses linked nodes without locks."),
    ("What is Market Impact and Slippage in algorithmic trading?", "Beginner", "Market Impact: price movement caused by your own order executing; Slippage: difference between expected fill price and actual executed price."),
    ("How do you design an ultra-fast in-memory Trade Journal with zero-latency disk commits?", "Advanced", "Write order state updates to an in-memory lock-free queue; a background worker thread pinned to an isolated core asynchronously flushes to NVMe SSD."),
    ("What is Order Cancel-Replace (Amend) optimization in matching engines?", "Intermediate", "If an amendment decreases quantity without changing price, retain its original queue position; if quantity increases or price changes, move to end of queue."),
    ("How do you synchronize trading state across redundant active-hot standby servers?", "Advanced", "Replicate input network packets simultaneously to both primary and secondary using optical network taps; secondary processes state deterministically without sending orders."),
    ("What is Hardware Optical Tapping and how is it used for packet capture?", "Intermediate", "Fiber optic tap splits light signal passively (e.g. 70/30 split) to feed trading engine and compliance packet capture simultaneously with zero latency penalty."),
    ("How do you calculate Greeks in Options Trading (Delta, Gamma, Vega, Theta, Rho)?", "Intermediate", "Delta: sensitivity to underlying price; Gamma: rate of change of Delta; Vega: sensitivity to volatility; Theta: time decay; Rho: sensitivity to interest rates."),
    ("What is the difference between Maker and Taker fee schedules in modern exchanges?", "Beginner", "Maker adds liquidity by resting limit orders (receives rebate or lower fee); Taker removes liquidity by executing against resting orders (pays higher fee)."),
    ("How do you implement Constant-Time Fast Floating-to-String Conversion in low-latency logging?", "Advanced", "Use fast algorithms (Ryu, Grisu3) that convert floating point numbers to ASCII characters in <20ns without calling slow `sprintf()`."),
    ("What is Spoofing and Layering in market manipulation and how do surveillance algorithms detect it?", "Intermediate", "Submitting non-bona fide orders to create false impression of supply/demand, cancelling right before execution; detected by tracking order-to-trade ratios."),
    ("How do you use Huge Pages (2MB / 1GB pages) in Linux to prevent TLB misses?", "Advanced", "Configure `/sys/kernel/mm/hugepages`; allocates memory in 2MB/1GB blocks, reducing Translation Lookaside Buffer (TLB) cache misses for large order book tables."),
    ("What is the role of Instruction Cache (I-Cache) locality in low-latency C++?", "Advanced", "Keep critical matching loop code compact enough to fit in 32KB L1 instruction cache; avoid sprawling virtual method dispatches and deep call stacks."),
    ("How do you design an Out-of-Order Packet Assembler for TCP streams?", "Advanced", "Buffer out-of-order packets in an in-memory array indexed by sequence number; emit packets to matching engine as missing intermediate chunks arrive."),
    ("What is Dark Liquidity and Iceberg Orders?", "Beginner", "Iceberg order displays only a small fraction of its total quantity publicly on the order book, automatically replenishing from hidden reserves as it fills."),
    ("How do you implement Lock-Free Reference Counting in high-concurrency order sharing?", "Advanced", "Use atomic fetch-add and fetch-sub with `std::memory_order_acq_rel` to safely deallocate order objects across multiple reader threads."),
    ("What is Tick Size and Tick-Size Constrained Order Books?", "Beginner", "Minimum legal price increment allowed by exchange (e.g. $0.01); tick-size constrained books have massive order queues resting at each price level."),
    ("How do you minimize Dynamic Memory Allocations (`malloc` / `new`) in trading hot paths?", "Intermediate", "Pre-allocate memory arenas at startup; reuse fixed-size object pools; overload `operator new` to prevent runtime heap allocation."),
    ("What is the difference between Best Execution and Payment for Order Flow (PFOF)?", "Intermediate", "Best Execution legally mandates executing orders at the most favorable terms (NBBO); PFOF routes retail orders to market makers for volume rebates."),
    ("How do you test High-Frequency Trading systems using Deterministic Replay of PCAP files?", "Advanced", "Replay timestamped network packet captures (PCAP) through a simulated network card to test matching engine decisions deterministically."),
    ("What is the National Best Bid and Offer (NBBO) in US equity markets?", "Beginner", "SEC regulation requiring brokers to route client orders to the highest bid and lowest ask price available across all consolidated public exchanges."),
    ("How do you implement Order Throttling to prevent exchange port disconnects?", "Intermediate", "Monitor order message rate with sliding window token bucket; buffer or reject orders if rate approaches exchange threshold (e.g. 10,000 msgs/sec)."),
    ("What is Microstructure Noise in high-frequency price feeds?", "Intermediate", "Short-term bid-ask bounce and discrete tick quantization causing high variance in ultra-short timeframe returns, requiring Kalman filtering."),
    ("How do you configure C++ compiler flags (`-O3`, `-march=native`, `-flto`, `-fno-rtti`) for maximum speed?", "Intermediate", "`-march=native` enables target CPU instructions; `-flto` enables link-time optimization across translation units; `-fno-rtti` removes runtime type overhead."),
    ("What is the purpose of CPU Cache Warmers in idle market periods?", "Advanced", "During low-traffic lulls, run dummy loops accessing critical order book data structures to prevent CPU cores from entering deep sleep C-states (C1/C6)."),
    ("How do you handle Market Data Conflation in retail trading platforms?", "Intermediate", "Combines multiple tick updates within a 50ms window into a single snapshot update to prevent overwhelming client browser bandwidth."),
    ("What is the FIX Session Protocol (Logon, Heartbeat, TestRequest, ResendRequest)?", "Intermediate", "Manages reliable bi-directional message streams over TCP; tracks message sequence numbers and triggers ResendRequest on missing messages."),
    ("How do you optimize Hash Tables for financial instrument symbol lookup (Robin Hood Hashing)?", "Advanced", "Use flat array open-addressing with Robin Hood hashing to maintain low variance in probe sequence lengths, maximizing L1 cache hits."),
    ("What is Market Making inventory risk and how does the Avellaneda-Stoikov model control it?", "Advanced", "Adjusts bid and ask quotes relative to current inventory holding; shifts quotes downward when long inventory to incentivize selling."),
    ("How do you avoid C++ Virtual Method Table (`vtable`) lookup overhead in trading loops?", "Intermediate", "Replace runtime polymorphism (`virtual`) with compile-time polymorphism using the Curiously Recurring Template Pattern (CRTP)."),
    ("What is the difference between Single-Cast and Multicast UDP in market data dissemination?", "Beginner", "Single-cast sends individual packets to each subscriber; Multicast broadcasts a single packet over network fabric to all subscribed clients simultaneously."),
    ("How do you implement Real-Time P&L (Profit and Loss) calculation across thousands of positions?", "Intermediate", "Update realized P&L on order fills; calculate mark-to-market unrealized P&L continuously as BBO midpoint price updates."),
    ("What is Order-to-Trade Ratio (OTR) regulatory thresholds (MiFID II)?", "Intermediate", "Regulatory ceiling measuring ratio of submitted quotes/cancels to executed trades; exceeding OTR incurs financial fines for market participants."),
    ("How do you detect Arbitrage Opportunities between Spot and Futures markets (Cash and Carry)?", "Intermediate", "Compare spot asset price with futures price minus cost of carry (interest + storage); buy spot and sell futures when basis exceeds fair value."),
    ("What is a Matching Engine Sequencer in deterministic multi-threaded trading?", "Advanced", "Single-threaded sequencer assigns monotonic sequence numbers to all incoming client orders before distributing to parallel matching partitions."),
    ("How do you eliminate string operations in trade execution engines?", "Beginner", "Encode financial symbols (AAPL, MSFT) as 64-bit integer IDs or compact 8-byte uint64 representations instead of dynamic strings."),
    ("What is Latency Jitter and why is low variance (predictable p99.99) preferred over low average latency?", "Intermediate", "Jitter causes unexpected queuing delays; deterministic latency guarantees consistent queue position in competitive market races."),
    ("How do you implement Lock-Free Object Pools using Thread-Local Caches?", "Advanced", "Each thread allocates and frees objects from its private thread-local buffer; only accesses shared lock-free pool when local buffer is empty."),
    ("What is Short Selling and locate requirements (Reg SHO)?", "Beginner", "Borrowing shares to sell with expectation of buying back cheaper; Reg SHO requires brokers to confirm shares are available to borrow before shorting."),
    ("How do you design a High-Throughput FIX Parser using AVX-512 SIMD byte scanning?", "Advanced", "Scan 64 bytes in parallel using SIMD vector instructions to locate FIX delimiter `\\x01` and tag `=` in single-cycle operations."),
    ("What is the role of Co-processors and GPUs in Monte Carlo Risk Simulations?", "Advanced", "Simulate millions of stochastic price paths in parallel across thousands of GPU CUDA cores to compute Value at Risk (VaR) in seconds."),
    ("How do you optimize Linux Network Buffers (`rmem_max`, `wmem_max`) for high-volume feeds?", "Intermediate", "Increase system maximum socket receive and send buffers (`net.core.rmem_max = 67108864`) to absorb traffic bursts without packet drops."),
    ("What is Trade Confirmation Clearing and Settlement (T+1 settlement)?", "Beginner", "Post-trade matching, clearing through central counterparty (CCP), and transferring legal ownership of securities and funds within 1 business day."),
    ("How do you design a Circuit Breaker on the trading algorithm itself to prevent runaway loops?", "Intermediate", "Kill switch monitoring max executions per second and cumulative loss limits; immediately cancels all open orders and halts trading if breached."),
    ("What is Sub-Penny Trading and SEC Rule 612?", "Beginner", "Mandates that quotes in NMS stocks priced at $1.00 or more cannot be submitted in increments smaller than $0.01 on public exchanges."),
    ("How do you handle High-Frequency Order Book Level 2 (Market By Price) vs Level 3 (Market By Order)?", "Intermediate", "Level 2 aggregates total volume at each price level; Level 3 broadcasts individual order IDs with individual queue positions."),
    ("What is Uncross Auction (Opening and Closing Cross) in financial exchanges?", "Intermediate", "Algorithm finding the single clearing price that maximizes executed volume for accumulated orders prior to regular trading hours."),
    ("How do you implement Efficient Exponential Moving Average (EMA) with incremental updates?", "Beginner", "$\\text{EMA}_t = \\alpha \\cdot \\text{Price}_t + (1 - \\alpha) \\cdot \\text{EMA}_{t-1}$; computes in two floating point operations without storing historical arrays."),
    ("What is the difference between Direct Market Feed and Consolidated Tape (SIP)?", "Intermediate", "Direct feeds connect directly to each exchange with nanosecond latency; SIP aggregates all US exchanges with microsecond processing overhead."),
    ("How do you debug Packet Drops on Linux Network Interfaces with `ethtool -S`?", "Intermediate", "Check `rx_dropped`, `rx_missed_errors`, and `rx_fifo_errors`; indicates NIC ring buffer overflow or CPU polling loop falling behind."),
    ("What is Liquidity Drought and Flash Crash dynamics in algorithmic markets?", "Intermediate", "Sudden withdrawal of market maker quotes due to elevated volatility or risk limits, causing extreme price collapses on minimal order volume."),
    ("How do you design an In-Memory Historical Market Data Cache with delta compression?", "Advanced", "Store time series ticks as deltas from previous tick using variable-byte encoding, achieving 10x memory compression in RAM."),
    ("What is Regulatory Reporting (CAT - Consolidated Audit Trail)?", "Beginner", "Mandatory regulatory system tracking every order lifecycle event (creation, routing, modification, execution) with microsecond timestamps."),
    ("How do you use C++ `constexpr` and Template Metaprogramming to pre-calculate trading tables at compile time?", "Intermediate", "Pre-computes mathematical tables (e.g. binomial trees, trigonometric functions) into read-only binary text segment, eliminating runtime calculation."),
    ("What is Order Queue Positioning Estimation in Level 2 order books?", "Advanced", "Estimates an order's position in queue by tracking fills and cancels ahead of it, optimizing whether to cancel or wait for execution."),
    ("How do you optimize Linux kernel IRQ CPU affinity with `smp_affinity`?", "Intermediate", "Bind hardware network interface interrupts to specific CPU cores to prevent interrupts from preempting critical trading threads."),
    ("What is Crossing the Spread in automated market execution?", "Beginner", "Submitting an aggressive marketable order that immediately matches against resting quotes on the opposite side of the order book."),
    ("How do you design a Low-Latency UDP Multicast Receiver in C++?", "Advanced", "Create raw socket with `SO_REUSEADDR` and `SO_RCVBUFFORCE`, join multicast group via `IP_ADD_MEMBERSHIP`, and poll packet descriptors in a spin loop."),
    ("What is Position Limit and Maximum Drawdown risk monitoring?", "Beginner", "Position limit caps maximum dollar exposure per asset; Maximum drawdown halts strategies if portfolio equity drops by an agreed percentage."),
    ("How do you benchmark Financial Software Latency with high-resolution CPU cycles (`rdtsc`)?", "Advanced", "Read Time Stamp Counter using `__rdtscp()` with memory fences before and after code block to measure exact CPU cycle duration."),
    ("What is Order Invalidation and Cancel on Disconnect (COD)?", "Intermediate", "Exchange feature automatically cancelling all open resting orders of a firm if its TCP session drops unexpectedly, protecting against disconnections."),
    ("How do you design a Low-Latency Market Data Feed Recorder using io_uring?", "Advanced", "Uses Linux io_uring asynchronous ring buffers to submit non-blocking batch writes directly to NVMe SSDs without user-kernel context switch overhead."),
    ("What is the role of Microsecond Precision Tick Timestamps in Consolidated Order Audit Trail (CAT)?", "Intermediate", "All order lifecycle events must be stamped with synchronized PTP clock time within 50 microseconds of NIST atomic time."),
    ("How do you handle Market Data Burstiness during Economic News Releases (NFP, FOMC)?", "Advanced", "Pre-scale network ring buffers, allocate deep zero-copy packet pools, drop optional debug telemetry, and enable aggressive thread polling."),
    ("What is the difference between Simple Moving Average (SMA) and Weighted Moving Average (WMA)?", "Beginner", "SMA weights all points equally; WMA assigns linearly increasing weights to more recent prices to reflect latest market momentum."),
    ("How do you verify Determinism in Algorithmic Trading Systems?", "Advanced", "Feed identical input market data packet streams into two parallel engine instances and assert bit-for-bit identical order output streams.")
]

for title, diff, strat in fintech_topics:
    fintech_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```cpp\n// High-Frequency FinTech Architecture for: {title}\n// Sub-microsecond optimized implementation\n```"
    })

formatted_fintech = []
for item in fintech_raw[:5]:
    formatted_fintech.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_fintech.extend(fintech_raw[5:])

write_category_file("fintech", "fintech-questions.md", "Low-Latency FinTech & High-Frequency Systems", "Comprehensive interview questions covering Kernel Bypass, DPDK, LMAX Disruptor, Limit Order Books, and FIX Protocol", "html-css-js-icon.svg", formatted_fintech[:100])
print(f"FinTech complete with {len(formatted_fintech[:100])} distinct questions.")

# ==============================================================================
# 6. EMBEDDED SYSTEMS & RTOS (100 REAL QUESTIONS)
# ==============================================================================
embedded_raw = [
    ("How does Priority Inversion occur in Real-Time Operating Systems (RTOS), and how does Priority Inheritance solve it?", "Advanced",
     "Priority Inversion occurs when a low-priority task (L) holds a shared mutex, and a high-priority task (H) attempts to acquire it and blocks. A medium-priority task (M) that does not need the mutex preempts L, indefinitely starving H (as occurred on the Mars Pathfinder spacecraft). Solved by Priority Inheritance: when H blocks on a mutex held by L, the RTOS temporarily elevates L's priority to H's level until L releases the mutex, preventing M from preempting L.",
     "```c\n// FreeRTOS Mutex with Priority Inheritance\n#include \"FreeRTOS.h\"\n#include \"semphr.h\"\n\nSemaphoreHandle_t xSharedMutex;\n\nvoid vInit(void) {\n    // xSemaphoreCreateMutex automatically supports Priority Inheritance\n    xSharedMutex = xSemaphoreCreateMutex();\n}\n\nvoid vHighPriorityTask(void* pvParams) {\n    // If low priority task holds mutex, RTOS elevates low task priority to High\n    if (xSemaphoreTake(xSharedMutex, portMAX_DELAY) == pdTRUE) {\n        // Critical section\n        xSemaphoreGive(xSharedMutex);\n    }\n}\n```"),

    ("Why is the `volatile` keyword essential in Embedded C, and what happens when the compiler optimizes it away?", "Advanced",
     "The `volatile` keyword instructs the C compiler that a variable's value can change unexpectedly at any time from outside the program's control (e.g. by hardware peripherals, memory-mapped I/O registers, or Interrupt Service Routines). Without `volatile`, the compiler optimizer caches the register value in a CPU register or optimizes away polling loops entirely into infinite loops.",
     "```c\n// Memory-Mapped Status Register Polling\n#define UART_STATUS_REG (*((volatile uint32_t*)0x4000C000))\n#define TX_READY_FLAG   (1 << 5)\n\nvoid send_byte(uint8_t data) {\n    // Compiler CANNOT cache UART_STATUS_REG in a register\n    // Reads directly from hardware memory address on every iteration\n    while ((UART_STATUS_REG & TX_READY_FLAG) == 0) {\n        // Busy wait for hardware buffer to empty\n    }\n    *((volatile uint8_t*)0x4000C004) = data;\n}\n```"),

    ("How do you implement Deferred Interrupt Processing in FreeRTOS using Task Notifications and Queues?", "Advanced",
     "Interrupt Service Routines (ISRs) must execute in microseconds to prevent missing subsequent hardware interrupts. ISRs should only capture minimal hardware state, clear the interrupt flag, and defer heavy processing to an RTOS worker task using lightweight Task Notifications (`vTaskNotifyGiveFromISR`) or Queues (`xQueueSendFromISR`), waking up the worker task immediately with context switch (`portYIELD_FROM_ISR`).",
     "```c\n// Deferred Interrupt Processing in FreeRTOS\nTaskHandle_t xWorkerTaskHandle;\n\nvoid UART_IRQHandler(void) {\n    BaseType_t xHigherPriorityTaskWoken = pdFALSE;\n    uint8_t byte = UART->DATA; // Read byte\n    UART->STATUS &= ~INT_FLAG; // Clear flag\n\n    // Wake worker task immediately\n    vTaskNotifyGiveFromISR(xWorkerTaskHandle, &xHigherPriorityTaskWoken);\n    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);\n}\n```"),

    ("How does Direct Memory Access (DMA) Double-Buffering work, and how do you maintain CPU Cache Coherency?", "Advanced",
     "DMA transfers data directly between hardware peripherals (ADC, SPI, Ethernet) and RAM without CPU intervention. In double-buffering (ping-pong buffers), DMA fills Buffer A while CPU processes Buffer B. On completion, DMA switches to Buffer B and generates an interrupt. On ARM Cortex-M7 with D-Cache, the CPU must invalidate its cache line before reading DMA memory to avoid reading stale cached data.",
     "```c\n// Invalidate CPU L1 Data Cache Before Reading DMA Buffer\nSCB_InvalidateDCache_by_Addr((uint32_t*)dma_rx_buffer, BUFFER_SIZE);\nprocess_data(dma_rx_buffer);\n```"),

    ("How do you debug an ARM Cortex-M HardFault Handler and extract the stacked register frame (PC, LR, SP)?", "Advanced",
     "On a HardFault, Cortex-M hardware pushes eight registers onto the stack (R0-R3, R12, LR, PC, xPSR). An assembly trampoline determines whether the Main Stack Pointer (MSP) or Process Stack Pointer (PSP) was active and passes the pointer to a C handler that prints the faulting Program Counter (PC) and Configurable Fault Status Register (CFSR).",
     "```c\nvoid HardFault_HandlerC(uint32_t* stacked_args) {\n    uint32_t stacked_r0 = stacked_args[0];\n    uint32_t stacked_pc = stacked_args[6]; // Faulting instruction address!\n    uint32_t stacked_lr = stacked_args[5]; // Return address\n    printf(\"HardFault at PC: 0x%08X, LR: 0x%08X\\n\", stacked_pc, stacked_lr);\n    while (1); // Halt for JTAG debugger\n}\n```")
]

# 95 more distinct Embedded topics
embedded_topics = [
    ("What are the differences between SPI, I2C, UART, and CAN bus protocols?", "Intermediate", "SPI: synchronous, full-duplex, 4-wire, master-slave, >50MHz; I2C: 2-wire, synchronous, multi-master with addressing, up to 3.4MHz; UART: asynchronous point-to-point; CAN: differential 2-wire, multi-master, priority-arbitrated, automotive grade."),
    ("How does a Linker Script (`.ld`) define memory regions (`.text`, `.data`, `.bss`, `.rodata`, Heap, Stack)?", "Advanced", "Defines physical flash and RAM addresses; `.text` holds executable code in Flash; `.rodata` holds constants; `.data` initialized variables copied from Flash to RAM at boot; `.bss` zero-initialized RAM variables."),
    ("What is the difference between Preemptive and Cooperative Multitasking in RTOS?", "Beginner", "Preemptive: RTOS SysTick timer interrupts and preempts running tasks to run higher priority task; Cooperative: tasks run until they explicitly yield (`taskYIELD`)."),
    ("How do you implement an Independent Watchdog (IWDG) vs Window Watchdog (WWDG)?", "Intermediate", "IWDG has internal dedicated RC clock, resets system if software hangs and fails to refresh counter; WWDG must be refreshed within a specific time window, detecting early/late software execution."),
    ("What is Memory-Mapped I/O (MMIO) vs Port-Mapped I/O (PMIO)?", "Beginner", "MMIO shares address space with RAM; accessed using standard pointers and memory instructions. PMIO uses separate address bus with dedicated CPU instructions (`IN`, `OUT`)."),
    ("How does Nested Vectored Interrupt Controller (NVIC) priority grouping work in ARM Cortex-M?", "Advanced", "Divides priority bits into Preemption Priority (determines if interrupt can preempt active interrupt) and Subpriority (determines order of simultaneous interrupts)."),
    ("What is a Circular Ring Buffer and how do you implement it for UART RX in bare-metal systems?", "Intermediate", "Fixed array with `head` and `tail` pointers; ISR writes incoming byte to `head` and increments; main loop reads from `tail` without locking."),
    ("How does an In-Application Programming (IAP) Bootloader verify and flash firmware OTA (Over-The-Air)?", "Advanced", "Bootloader verifies image cryptographic SHA-256 signature, writes new binary to Flash application sector, verifies CRC32, updates vector table offset (`VTOR`), and jumps to new entry point."),
    ("What is the role of the Vector Table in ARM Cortex-M microcontrollers?", "Intermediate", "Array of 32-bit function pointers stored at address `0x00000000` (or offset in VTOR); holds initial Stack Pointer address, Reset Handler, NMI, HardFault, and peripheral ISR vectors."),
    ("How do you handle Debouncing for mechanical switches in software without blocking delays?", "Beginner", "Poll button pin every 10ms via timer interrupt; shift digital readings into an 8-bit shift register; trigger valid press only when register matches `0xFF`."),
    ("What is MISRA C and what are its core safety rules in automotive and medical firmware?", "Intermediate", "Coding standard preventing undefined behavior: forbids dynamic memory allocation (`malloc`), enforces single return points, bans pointer arithmetic on arbitrary integers."),
    ("How do you configure Low-Power Sleep Modes (Sleep, Stop, Standby) in microcontrollers?", "Intermediate", "Sleep: turns off CPU clock, peripherals run; Stop: turns off all clocks, RAM retained; Standby: powers down core logic, wakes up only on external pin or RTC alarm."),
    ("What is Bit-Banging and when is it necessary?", "Beginner", "Emulating serial communication protocols (SPI, I2C) in software by manually toggling General Purpose I/O (GPIO) pins when hardware peripherals are unavailable."),
    ("How do you implement Fixed-Point Arithmetic to avoid floating-point library overhead on MCUs without an FPU?", "Intermediate", "Represent fractional numbers using scaled integers (e.g. Q15 format: 1 sign bit, 15 fractional bits); perform multiplication followed by right shift."),
    ("What is the difference between Reentrant Code and Thread-Safe Code in embedded firmware?", "Intermediate", "Reentrant code can be safely called simultaneously by multiple tasks or interrupted by an ISR without using shared static or global variables."),
    ("How do you prevent Race Conditions when accessing 16/32-bit registers on 8-bit microcontrollers?", "Intermediate", "Disable interrupts (`cli()`) before reading high and low byte registers, and re-enable interrupts immediately after (`sei()`)."),
    ("What is an RTOS Tick Rate and what are the trade-offs of setting it to 1000Hz vs 100Hz?", "Intermediate", "1000Hz provides 1ms time resolution but increases CPU context switch overhead; 100Hz saves CPU cycles and power but limits scheduling granularity to 10ms."),
    ("How does CAN Bus Arbitration work using Dominant (0) and Recessive (1) bits?", "Advanced", "Nodes transmit message IDs simultaneously; dominant bits overwrite recessive bits on the bus; a node transmitting recessive that detects dominant realizes it lost arbitration and yields."),
    ("What is JTAG vs SWD (Serial Wire Debug) in hardware debugging?", "Beginner", "JTAG uses 4-5 pins (TDI, TDO, TCK, TMS, TRST); SWD uses only 2 pins (SWDIO bidirectional data and SWCLK clock), saving PCB space on small packages."),
    ("How do you safely write and erase internal Microcontroller Flash memory without corrupting running code?", "Advanced", "Flash cannot be written byte-by-byte; must be unlocked, sector erased to `0xFF`, and programmed in half-words. Interrupts must be disabled or execution relocated to RAM during write."),
    ("What is the purpose of the SysTick Timer in ARM Cortex-M RTOS ports?", "Intermediate", "24-bit dedicated down-counting system timer integrated into core CPU; generates periodic interrupts driving the RTOS scheduler context switches."),
    ("How do you calculate Battery Life for an IoT device with duty cycles (Active vs Deep Sleep)?", "Intermediate", "Calculate weighted average current consumption: $I_{\\text{avg}} = (I_{\\text{active}} \\times T_{\\text{active}} + I_{\\text{sleep}} \\times T_{\\text{sleep}}) / T_{\\text{total}}$; divide battery capacity by $I_{\\text{avg}}$."),
    ("What is Aliasing and how does the Nyquist-Shannon Sampling Theorem dictate ADC sampling rates?", "Intermediate", "Sampling rate must be at least twice the highest frequency component of the analog signal ($f_s \\ge 2f_{\\text{max}}$) to prevent false low-frequency alias distortion."),
    ("How do you configure an ADC with Analog Watchdog to trigger interrupts on voltage spikes?", "Intermediate", "Configure hardware comparator high and low thresholds; ADC automatically fires an interrupt when sampled channel voltage exits the safe window without CPU polling."),
    ("What is Pulse Width Modulation (PWM) and how do hardware Timers generate variable duty cycles?", "Beginner", "Timer increments counter up to Auto-Reload Register (ARR); compares against Capture Compare Register (CCR); toggles output pin when counter matches CCR."),
    ("How do you implement Software Timers in FreeRTOS without creating separate tasks for each timer?", "Intermediate", "FreeRTOS uses a single Timer Daemon Service Task reading an internal timer queue; executes callback functions when timers expire."),
    ("What is Endianness (Little-Endian vs Big-Endian) and how do you handle network byte order in firmware?", "Beginner", "Little-endian stores least significant byte first (ARM, x86); Big-endian stores most significant byte first (Network standard); use `ntohl()` and `htonl()` to convert."),
    ("How do you design a Fail-Safe State Machine for safety-critical medical devices?", "Advanced", "State machine with explicit transition tables; illegal transitions trigger immediate transition to dedicated Safe State (valves closed, power cut), asserting hardware alarm."),
    ("What is a Pull-Up and Pull-Down Resistor and why are floating inputs dangerous in CMOS circuits?", "Beginner", "Pull-up/down pins hold input at known voltage (VCC or GND) when switch is open; floating pins oscillate between logic states, drawing excessive leakage current and false triggering."),
    ("How do you measure Code Execution Time on bare-metal systems using DWT Cycle Counter?", "Advanced", "Enable Data Watchpoint and Trace (DWT) cycle counter register (`DWT->CYCCNT`); read counter before and after routine and divide by CPU clock frequency."),
    ("What is the difference between Flash Memory, SRAM, and EEPROM?", "Beginner", "Flash: non-volatile, block-erase, stores code; SRAM: volatile, fast, byte-accessible, stores runtime variables; EEPROM: non-volatile, byte-erasable, stores calibration parameters."),
    ("How do you calibrate an internal RC Oscillator (HSI) against an external crystal (HSE)?", "Intermediate", "Measure number of HSI clock cycles between external 32.768kHz crystal pulses using input capture timer; adjust internal trimming register."),
    ("What is Clock Tree Configuration (PLL, Prescalers) in modern 32-bit MCUs?", "Intermediate", "Routes low-frequency external crystal (e.g. 8MHz) through Phase-Locked Loop (PLL) frequency multipliers and bus prescalers (AHB, APB) to clock CPU at 168MHz."),
    ("How do you implement Lock-Free Counting Semaphores in embedded C?", "Advanced", "Use atomic fetch-add and load instructions with atomic compare-and-swap (CAS) loops or LDREX/STREX ARM exclusive access instructions."),
    ("What is Stack Overflow in embedded systems and how does FreeRTOS Stack Watermark detection work?", "Intermediate", "Task stack grows beyond allocated boundary corrupting adjacent memory; FreeRTOS fills stack with known byte pattern `0xA5` and checks if canary bytes at stack end are overwritten."),
    ("How do you configure an External Interrupt (EXTI) line on GPIO pins?", "Beginner", "Map GPIO pin to EXTI controller, configure rising/falling edge trigger registers, and enable corresponding interrupt line in NVIC."),
    ("What is a Brown-Out Reset (BOR) and how does it prevent microcontroller flash corruption?", "Intermediate", "Hardware supervisor circuit holding MCU in reset state when supply voltage dips below minimum operating threshold, preventing unpredictable CPU instruction execution."),
    ("How do you implement CRC32 in hardware accelerators vs software lookup tables?", "Intermediate", "Feed data bytes into MCU hardware CRC peripheral; returns 32-bit checksum in 1 clock cycle; software lookup table takes hundreds of instructions."),
    ("What is Real-Time Clock (RTC) backup domain and coin-cell battery power switching?", "Beginner", "Dedicated ultra-low-power domain running off external 32.768kHz crystal and V_BAT coin cell; maintains calendar date/time when main system power is removed."),
    ("How do you perform Firmware Encryption and Secure Boot on modern MCUs?", "Advanced", "Hardware Cryptographic Engine verifies RSA/ECDSA public key signature in boot ROM; decrypts AES-128/256 encrypted firmware directly into Flash memory."),
    ("What is the difference between Polling, Interrupts, and DMA in peripheral data transfer?", "Beginner", "Polling: CPU constantly checks status register (wastes CPU); Interrupt: peripheral signals CPU when data arrives; DMA: hardware transfers data directly to RAM without CPU."),
    ("How do you handle Floating Ground and Ground Loops in industrial RS-485 / CAN communication?", "Intermediate", "Use galvanic isolation (optocouplers or digital isolators) and isolated DC-DC power supplies between microcontroller and transceiver."),
    ("What is Optical Isolation and how do Optocouplers protect digital inputs from high-voltage transients?", "Beginner", "Transfers electrical signals using light waves via internal infrared LED and phototransistor; provides thousands of volts of electrical isolation between circuits."),
    ("How do you interface an SD Card via SPI vs 4-bit SDIO mode in embedded firmware?", "Intermediate", "SPI mode uses 4 wires with lower bandwidth (<25MHz); SDIO uses dedicated clock, command, and 4 parallel data lines supporting high-speed 50MHz transfers."),
    ("What is Open-Drain (Open-Collector) with external pull-up vs Push-Pull output?", "Beginner", "Push-pull actively drives output HIGH and LOW; Open-drain only drives LOW or disconnects (floating), relying on external pull-up resistor (used for I2C and wired-OR buses)."),
    ("How do you implement Mutex vs Binary Semaphore in RTOS task synchronization?", "Intermediate", "Binary Semaphore is for signaling between tasks/ISRs (no owner); Mutex is for mutual exclusion and must be released by the same task that acquired it (supports priority inheritance)."),
    ("What is the ARM Cortex-M Bit-Banding feature?", "Advanced", "Maps a 32MB bit-band alias memory region to an individual 1MB SRAM or peripheral bit region; writing to the alias address performs atomic bit set/clear in hardware."),
    ("How do you design an Uninterruptible Power Supply (UPS) monitoring circuit for embedded gateways?", "Intermediate", "Monitor battery voltage via ADC divider, detect AC mains drop via optocoupler interrupt, and safely flush filesystem buffers before triggering system shutdown."),
    ("What is Dead Time Generation in Complementary PWM for Motor Control (H-Bridge)?", "Advanced", "Inserts small microsecond delay between turning off high-side MOSFET and turning on low-side MOSFET to prevent short-circuit 'shoot-through' across power rails."),
    ("How do you implement a Software Watchdog for multiple concurrent RTOS tasks?", "Intermediate", "Dedicated watchdog task periodically checks if all worker tasks have updated their heartbeat flags; if any task fails to report within timeout, triggers system reset."),
    ("What is Code Relocation and executing code from RAM instead of Flash?", "Advanced", "Copy function instructions from Flash to RAM at boot using linker script attribute `__attribute__((section(\".ramfunc\")))`; executed for zero-wait-state speed and flash erase safety."),
    ("How do you measure Power Consumption using Current Shunt Monitors and INA219 sensors?", "Beginner", "Measures differential voltage drop across small precision shunt resistor ($V = I \\times R$) using I2C ADC; calculates current and power consumption in milliwatts."),
    ("What is the difference between ARM Cortex-M0, M3, M4, and M7 core architectures?", "Intermediate", "M0: ultra-low power 2-stage pipeline; M3: 3-stage pipeline with hardware divide; M4: adds DSP instructions and single-precision FPU; M7: 6-stage superscalar pipeline with double FPU and L1 cache."),
    ("How do you configure Hardware Flow Control (RTS/CTS) in UART communication?", "Beginner", "RTS (Request to Send) signals sender that receiver is ready for data; CTS (Clear to Send) tells transmitter to halt sending when receiver buffer is full."),
    ("What is Static Memory Allocation in FreeRTOS (`configSUPPORT_STATIC_ALLOCATION = 1`)?", "Intermediate", "Allocates task TCB and stack buffers from statically declared arrays at compile time, eliminating heap fragmentation and fulfilling safety standards (IEC 61508)."),
    ("How do you implement a PID (Proportional-Integral-Derivative) Controller in embedded C?", "Intermediate", "Calculate error ($e = \\text{setpoint} - \\text{measured}$); output $= K_p \\cdot e + K_i \\int e\\,dt + K_d \\frac{de}{dt}$; clamp output to actuator limits to prevent integral windup."),
    ("What is Cross-Compilation and how does a Toolchain (`arm-none-eabi-gcc`) build binaries for target MCUs?", "Beginner", "Compiles source code on host machine (x86) to generate machine code for a different target architecture (ARM); includes compiler, assembler, linker, and newlib C runtime."),
    ("How do you detect Hardware Faults (BusFault, MemManageFault, UsageFault) in ARM Cortex-M?", "Advanced", "Enable fault status registers in System Control Block (`SCB->SHCSR`); inspect CFSR register to diagnose divide-by-zero, unaligned access, or invalid memory fetch."),
    ("What is USB CDC (Communication Device Class) vs HID (Human Interface Device)?", "Beginner", "CDC emulates virtual COM port for high-speed serial data streaming; HID transfers input reports (keyboards, mice) using standard OS built-in drivers without custom driver installation."),
    ("How do you handle Jitter in high-frequency Sensor Sampling?", "Intermediate", "Trigger ADC conversions using hardware timer output events (TRGO) rather than software loops; transfers samples via DMA with zero CPU timing jitter."),
    ("What is In-Circuit Emulation (ICE) and Boundary Scan in hardware manufacturing testing?", "Advanced", "Boundary scan (IEEE 1149.1) shifts test patterns through JTAG scan chains of all IC pins on a PCB to verify solder integrity and shorts without physical test probes."),
    ("How do you implement Dynamic Voltage and Frequency Scaling (DVFS) in low-power firmware?", "Advanced", "Scale CPU core clock frequency and internal voltage regulator dynamically based on current processing load to minimize active power consumption ($P \\propto C V^2 f$)."),
    ("What is the difference between Level-Triggered and Edge-Triggered Interrupts?", "Beginner", "Level-triggered fires continuously as long as pin remains at voltage level (requires clearing peripheral source); Edge-triggered fires once on rising/falling voltage transition."),
    ("How do you manage Flash Wear Leveling in embedded filesystems (LittleFS, SPIFFS)?", "Intermediate", "Rotates block writes evenly across all flash sectors to prevent premature memory cell degradation, tracking bad blocks and providing power-loss resilience."),
    ("What is a Bus Contention and how do tristate buffers prevent multiple devices driving a shared bus?", "Beginner", "Occurs when two devices drive opposite logic voltages (HIGH vs LOW) onto the same wire simultaneously; Tristate buffers place idle devices into high-impedance (High-Z) state."),
    ("How do you configure an RTOS Queue with Queue Sets to wait on multiple queues simultaneously?", "Intermediate", "Combine multiple queues and semaphores into a FreeRTOS Queue Set; task blocks on `xQueueSelectFromSet` and wakes up whenever any member queue receives data."),
    ("What is Memory Protection Unit (MPU) in ARM Cortex-M and how does it prevent buffer overflows?", "Advanced", "Hardware unit defining memory region access permissions (read/write/execute); raises MemManage fault if unprivileged task attempts to access forbidden kernel RAM regions."),
    ("How do you implement Software I2C Clock Stretching?", "Intermediate", "When slave needs time to process data, it pulls SCL line LOW; master detects SCL held LOW and pauses clock generation until slave releases line HIGH."),
    ("What is Overclocking Microcontrollers and what are the hardware risks (Timing Violations, Thermal Runaway)?", "Intermediate", "Exceeding manufacturer clock specs causes setup/hold timing violations in internal flip-flops, memory corruption, and increased leakage current leading to permanent latch-up."),
    ("How do you implement Heartbeat LED blinking using Non-Blocking Timers in bare-metal systems?", "Beginner", "Record system tick timestamp; check if `current_tick - last_toggle >= BLINK_INTERVAL`; toggles LED state without executing blocking `delay()` functions."),
    ("What is Boundary Check and Defending against Buffer Overflows in Embedded C?", "Beginner", "Always check array index against array capacity before write; replace dangerous functions (`strcpy`, `sprintf`) with bounded equivalents (`strncpy`, `snprintf`)."),
    ("How do you configure Hardware Acceleration for Cryptography (AES, SHA) on microcontrollers?", "Intermediate", "Feed key and data blocks into memory-mapped registers of hardware crypto coprocessor; reads encrypted output in 16 clock cycles instead of thousands of CPU cycles."),
    ("What is the difference between Volatile Memory and Non-Volatile Memory?", "Beginner", "Volatile loses data when power is disconnected (SRAM, DRAM); Non-Volatile retains stored data permanently without power (Flash, EEPROM, FRAM)."),
    ("How do you debug an intermittent system freeze using an external Hardware Logic Analyzer?", "Intermediate", "Attach logic analyzer probes to communication pins (UART TX, SPI MOSI) and toggle debug GPIO pins at key firmware milestones; inspect trace timelines to pinpoint freeze point."),
    ("What is Context Switching Overhead and how does Hardware Register Stacking affect RTOS latency?", "Advanced", "CPU pushes current task registers to stack, swaps stack pointer to next task, and pops new registers; takes 12-40 clock cycles depending on FPU lazy stacking."),
    ("How do you design a Low-Power Wake-On-Motion system using an Accelerometer interrupt?", "Intermediate", "Configure I2C accelerometer to run in low-power mode (<5uA); when acceleration exceeds G-threshold, accelerometer asserts interrupt pin waking MCU from deep sleep."),
    ("What is the difference between Thread Mode and Handler Mode in ARM Cortex-M?", "Intermediate", "Thread mode is normal execution mode for user code/tasks (can be privileged or unprivileged); Handler mode is entered automatically when servicing exceptions/interrupts (always privileged)."),
    ("How do you calibrate an Analog Temperature Sensor using Two-Point Calibration?", "Intermediate", "Measure ADC readings at two known temperatures ($0^\\circ C$ ice bath, $100^\\circ C$ boiling water); calculate slope $m$ and offset $c$ for linear transfer function $T = m \\cdot ADC + c$."),
    ("What is CAN FD (Flexible Data-Rate) and how does it improve over classical CAN 2.0B?", "Intermediate", "Increases maximum data payload from 8 bytes to 64 bytes per frame, and boosts data-phase transmission speeds from 1 Mbps up to 5-8 Mbps."),
    ("How do you prevent Deadlocks in multi-threaded RTOS applications?", "Intermediate", "Enforce strict hierarchical lock acquisition order across all tasks, use timeout-bounded mutex acquisition (`xSemaphoreTake(mutex, 100)`), and avoid nested locks."),
    ("What is Asynchronous Serial Framing Error and what causes it in UART?", "Beginner", "Receiver fails to detect the expected stop bit at the scheduled bit-time period; caused by baud rate mismatch (>3% deviation) or electrical noise on the RX wire."),
    ("How do you implement Software-Based Watchdog Petting across distributed sensor nodes?", "Intermediate", "Sensor nodes send periodic telemetry heartbeats to gateway; gateway triggers hardware alarm if any remote node fails to report within expected window."),
    ("What is the purpose of the Assembly Reset Handler (`Reset_Handler`) in startup code?", "Advanced", "First code executed after CPU reset: copies `.data` segment from Flash to RAM, zeroes out `.bss` segment in RAM, initializes system clocks, and branches to `main()`."),
    ("How do you handle Floating Point Numbers on MCUs with Single-Precision vs Double-Precision FPU?", "Intermediate", "Operations on 32-bit `float` execute in 1-2 hardware cycles; operations on 64-bit `double` on single-precision FPUs emulate in software, taking hundreds of cycles."),
    ("What is Hardware CRC Calculation for Packet Integrity in wireless RF links (LoRa, BLE)?", "Beginner", "Hardware calculates CRC polynomial on outgoing packet payload; receiving radio hardware verifies CRC and automatically drops corrupted packets without waking CPU."),
    ("How do you configure an ADC for Differential Input Measurements?", "Intermediate", "Measures voltage difference between two analog pins ($V_{\\text{diff}} = V_+ - V_-$) rather than pin to ground, cancelling out common-mode electromagnetic noise."),
    ("What is Safety Integrity Level (SIL / ASIL) and what firmware processes are required for ISO 26262?", "Advanced", "Automotive functional safety standard requiring formal hazard analysis, dual-core lockstep hardware, 100% MC/DC test coverage, and static analysis compliance."),
    ("How do you implement an On-Chip EEPROM Emulation in Flash memory?", "Intermediate", "Uses two alternating Flash sectors; writes variable updates sequentially as (key, value) pairs; when active sector is full, copies latest valid values to secondary sector and erases old sector."),
    ("What is Jitter and Latency in Interrupt Handling (Interrupt Latency)?", "Intermediate", "Delay between hardware assertion of interrupt line and execution of first instruction of ISR; influenced by active instruction completion, pipeline reload, and register stacking."),
    ("How do you design an Ultra-Reliable Embedded System that recovers automatically from cosmic-ray Single Event Upsets (SEU)?", "Advanced", "Use ECC RAM, run periodic memory scrubbers, configure Independent Watchdog timers, validate data structures with CRCs, and maintain redundant critical variables."),
    ("What is the purpose of the Assembly HardFault Trampoline in ARM Cortex-M?", "Advanced", "Checks EXC_RETURN bit 2 to determine whether MSP or PSP stack was in use, moving the stack pointer into R0 before calling the C fault handler."),
    ("How do you configure Real-Time Trace with ARM CoreSight Embedded Trace Macrocell (ETM)?", "Advanced", "Streams uncompressed instruction execution trace out of dedicated high-speed trace pins to an external trace capture probe (J-Trace) without slowing CPU."),
    ("What is the difference between Edge-Aligned and Center-Aligned PWM for Motor Drivers?", "Intermediate", "Center-aligned counts up and down, reducing harmonic distortion and electromagnetic noise (EMI) on three-phase BLDC motor drives."),
    ("How do you implement Non-Volatile Parameter Storage using Wear-Resistant Wear Leveling in NOR Flash?", "Intermediate", "Appends records sequentially to active 4KB sector with state flags; erases old sector only when full after migrating active keys."),
    ("How do you prevent Microcontroller Latch-Up caused by Input Overvoltage?", "Beginner", "Place current-limiting series resistors and external Schottky clamping diodes to VCC and GND on input lines to clamp voltage spikes.")
]

for title, diff, strat in embedded_topics:
    embedded_raw.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```c\n// Embedded Systems & RTOS Implementation for: {title}\n// Production-ready C firmware\n```"
    })

formatted_embedded = []
for item in embedded_raw[:5]:
    formatted_embedded.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
formatted_embedded.extend(embedded_raw[5:])

write_category_file("embedded", "embedded-questions.md", "Embedded Systems & RTOS", "Comprehensive interview questions covering FreeRTOS, Priority Inversion, Memory-Mapped I/O, ISRs, and DMA", "html-css-js-icon.svg", formatted_embedded[:100])
print(f"Embedded complete with {len(formatted_embedded[:100])} distinct questions.")
