import os
import sys
sys.path.append(os.path.dirname(__file__))
from writer_helper import write_category_file

# ==============================================================================
# 1. BEHAVIORAL & LEADERSHIP (100 DISTINCT QUESTIONS)
# ==============================================================================
behavioral_questions = [
    ("Tell me about a time you led a complex technical migration with tight deadlines and shifting requirements?", "Advanced",
     "Structure using STAR: Detail the technical challenges (monolith to microservices, database migration, zero downtime requirements), team alignment across 3 departments, setting up an iterative Strangler Fig pattern, and delivering with zero customer downtime and 45% latency reduction.",
     "```markdown\nSTAR Framework:\n- Situation: Monolith payment migration with shifting currency requirements.\n- Task: Technical leadership, architecture design, and cross-team execution.\n- Action: Strangler Fig pattern, gRPC contracts, automated canary deployments.\n- Result: Zero downtime, 45% latency reduction, 1 week ahead of schedule.\n```"),
    
    ("How do you handle severe technical disagreements with a principal architect or staff engineer?", "Intermediate",
     "Focus on depersonalizing the debate: Build empirical spikes/prototypes, create a quantitative Decision Matrix comparing memory, latency p99, and operational cost, and document consensus in an Architecture Decision Record (ADR).",
     "```markdown\nConflict Resolution Steps:\n1. Separate ego from architecture.\n2. Disagree and commit when needed, but prioritize data over opinions.\n3. Build small empirical prototypes (spikes) to measure actual tradeoffs.\n4. Document consensus via Architecture Decision Records (ADRs).\n```"),

    ("Describe a situation where a major production outage occurred under your watch. How did you lead the response?", "Advanced",
     "Walk through your incident commander role: Triage first, rollback immediately to restore service, communicate with stakeholders every 15 minutes, and lead a blameless 5-Whys postmortem producing concrete architectural safeguards.",
     "```markdown\nBlameless Incident Protocol:\n1. Triage & Stabilize (Rollback first, investigate root cause second).\n2. Transparent stakeholder status page updates every 15 minutes.\n3. Blameless 5-Whys Postmortem identifying systemic failure modes.\n4. Action items tracked as P0/P1 Jira tickets.\n```"),

    ("Tell me about a time you had to deliver a critical project with incomplete or ambiguous specifications?", "Intermediate",
     "Explain how you drove clarity: Created rapid wireframes/API mockups, held weekly stakeholder alignment sessions, implemented phased milestone delivery, and established feedback loops that uncovered edge cases early.",
     "```markdown\nDe-risking Ambiguity:\n1. Break project into minimum verifiable milestones.\n2. Create interactive contract mocks for client teams.\n3. Implement feature flags to ship dark launches.\n4. Measure real user behavior to guide iterations.\n```"),

    ("How do you manage a direct report or team member who is consistently underperforming technically?", "Intermediate",
     "Demonstrate compassionate but firm leadership: Conduct 1-on-1 discovery to identify root causes (personal, knowledge gaps, burnout), set clear 30-day SMART goals, pair them with a senior mentor, and track objective deliverables weekly.",
     "```markdown\nPerformance Turnaround Plan:\n- Week 1: Clarify expectations and diagnose bottlenecks.\n- Week 2-3: Pair programming on isolated, well-defined bug fixes.\n- Week 4: Objective review against agreed pull request quality benchmarks.\n```"),

    ("Tell me about a time you advocated for paying down technical debt against product management pushback?", "Advanced",
     "Explain how you translated technical debt into business metrics: Quantified the cost of slow developer velocity, incident downtime ($/hr), and customer drop-off. Proposed the '20% tax' rule allocating 20% of every sprint to platform health.",
     "```markdown\nBusiness Justification for Tech Debt:\n- 'Refactoring authentication will reduce login failures by 90% and save $50k/yr in AWS support.'\n- 'Upgrading compiler saves 8 minutes per CI build, saving 40 engineering hours/month.'\n```"),

    ("Describe a scenario where you mentored a junior or mid-level engineer into a senior or tech lead role?", "Intermediate",
     "Highlight intentional delegating: Assigned them end-to-end design doc ownership, coached them through cross-functional reviews without taking over, guided their PR review quality, and celebrated their promotions.",
     "```markdown\nMentorship Milestones:\n1. Shadowing design reviews -> Co-authoring RFC -> Solo RFC defense.\n2. Guided code reviews focused on architectural patterns rather than syntax.\n3. Providing safe-fail environments on non-critical path services.\n```"),

    ("Tell me about a time you made an architectural decision that failed or backfired. What did you learn?", "Advanced",
     "Show extreme ownership and humility: Describe choosing an immature database or over-engineering a microservice when a modular monolith sufficed. Detail how you recognized the failure early, communicated transparently, and migrated cleanly.",
     "```markdown\nArchitecture Retrospective:\n- Lesson: Match tool maturity to operational team size.\n- Recovery: Abstracted DB behind a repository interface to swap storage engine in 2 sprints.\n- Guardrail: Instituted Technology Radar to vet libraries before adoption.\n```"),

    ("How do you manage cross-team dependencies when another team is blocking your release roadmap?", "Intermediate",
     "Explain proactive dependency management: Establish shared API contracts, mock their endpoints in staging using MSW/WireMock, maintain a shared Jira dependency board, and escalate constructively through engineering managers.",
     "```markdown\nDependency Management Strategy:\n1. Shift left on API Contract Definition (OpenAPI / Protobuf).\n2. Build mock server to decouple frontend/backend timelines.\n3. Bi-weekly syncs between tech leads to track critical path blockers.\n```"),

    ("Describe a situation where you had to push back on an unreasonable deadline from executive leadership?", "Advanced",
     "Demonstrate executive communication: Validate business urgency, present the iron triangle (Scope, Time, Quality), offer concrete trade-off options (e.g. ship MVP core features on time, phase 2 enhancements 3 weeks later), and show risks of cutting quality.",
     "```markdown\nExecutive Negotiation Framework:\n- 'We can hit the May 1st date if we defer payment method X and launch with credit cards only.'\n- 'Shipping the full scope by May 1st requires bypassing penetration testing, exposing us to compliance fines.'\n```")
]

# Add 90 more distinct behavioral questions
behavioral_topics = [
    ("How do you foster a blameless engineering culture while still maintaining high individual accountability?", "Advanced", "Emphasize focusing on process failure over personal blame, implementing blameless postmortems, and setting objective code review guidelines."),
    ("Tell me about a time you had to onboard rapidly onto a massive, undocumented legacy codebase?", "Intermediate", "Detail reading test suites, tracing execution flow with debuggers, drawing architecture diagrams, and documenting runbooks for future hires."),
    ("Describe a time you identified a critical security vulnerability in production before an external audit?", "Advanced", "Explain finding an IDOR or SQLi vulnerability, immediately reporting through responsible disclosure, deploying an emergency hotfix, and adding automated SAST tests."),
    ("How do you ensure diverse perspectives are heard during technical brainstorming and architecture sessions?", "Intermediate", "Describe using asynchronous RFCs where introverted engineers can write feedback, round-robin design reviews, and anonymous question forms."),
    ("Tell me about a time you had to balance short-term product shipping speed with long-term software maintainability?", "Intermediate", "Explain shipping an MVP with feature flags, documenting known tech debt items as tickets, and scheduling refactoring immediately post-launch."),
    ("How do you handle scope creep when a client or product manager keeps requesting new features mid-sprint?", "Intermediate", "Describe using formal change control, estimating added velocity impact, and agreeing on which existing ticket moves out of the sprint."),
    ("Tell me about a time you improved the deployment frequency or developer productivity of your entire organization?", "Advanced", "Explain reducing CI build times from 45 min to 6 min using caching, containerization, parallel test execution, and trunk-based development."),
    ("Describe how you handled a high-stakes cross-functional disagreement between engineering and design/UX?", "Intermediate", "Detail organizing user testing sessions with real customer prototypes to let quantitative user metrics settle design debates."),
    ("Tell me about a time you had to deprecate and sunset a legacy system used by thousands of active users?", "Advanced", "Explain defining deprecation timelines, building telemetry monitoring traffic on legacy endpoints, offering migration guides, and dark-launching traffic diversion."),
    ("How do you foster continuous learning and technical excellence within your engineering team?", "Intermediate", "Describe hosting bi-weekly technical brown-bags, postmortem reading clubs, encouraging open-source contributions, and allocating learning budgets."),
    ("Tell me about a time you had to coordinate a zero-downtime database schema migration on a high-throughput table?", "Advanced", "Detail using the Expand-and-Contract (Parallel Run) pattern with dual writes, backfilling data in batches, and switching reads with feature flags."),
    ("Describe a time you proactively prevented a major production outage before it happened?", "Advanced", "Explain noticing anomalous connection pool saturation on Grafana during a marketing campaign and immediately tuning thread pool sizes."),
    ("How do you approach code reviews: what do you focus on and how do you give constructive feedback?", "Intermediate", "Focus on architectural boundaries, error handling, performance, and security; automate linting/formatting in CI; phrase suggestions as questions."),
    ("Tell me about a time you helped resolve a team conflict between two engineers with opposing coding styles?", "Intermediate", "Explain adopting automated formatters (Prettier, rustfmt, clang-format) into CI pre-commit hooks to permanently eliminate formatting arguments."),
    ("Describe a time you received difficult constructive feedback from your manager or team. How did you adapt?", "Intermediate", "Demonstrate coachability: listened without defending, asked for concrete examples, implemented a 30-day feedback checkpoint, and improved."),
    ("Tell me about a time you had to lead an incident response for an external API provider outage?", "Advanced", "Explain engaging circuit breakers, enabling cached stale fallback data, informing customer support teams, and evaluating alternative backup providers."),
    ("How do you evaluate whether to build an in-house tool versus purchasing an off-the-shelf SaaS solution?", "Advanced", "Conduct Total Cost of Ownership (TCO) analysis comparing engineering build/maintenance hours against subscription costs and data privacy needs."),
    ("Tell me about a time you optimized a team's Agile/Scrum process that was feeling bureaucratic or bloated?", "Intermediate", "Replace 30-minute daily standups with asynchronous Slack check-ins, focus retrospectives on actionable items, and shorten sprint planning."),
    ("Describe a situation where an executive asked for an impossible technical feature. How did you handle it?", "Advanced", "Educate the executive respectfully on physical/computational limits (e.g. CAP theorem or network latency), and propose viable alternatives that achieve the business goal."),
    ("Tell me about a time you worked with remote, distributed teams across multiple time zones?", "Intermediate", "Implement documentation-first culture, recorded architecture demos, overlapping core hours for sync meetings, and clear handoff protocols."),
    ("How do you identify and mitigate single points of failure (bus factor) on your engineering team?", "Intermediate", "Institute rotation of service ownership, mandatory peer code reviews, shared on-call duties, and collaborative architecture documentation."),
    ("Tell me about a time you had to make a high-impact technical decision with only 60% of the information available?", "Advanced", "Adopt Amazon's two-way door decision framework: identify if the decision is reversible, gather high-signal data, proceed decisively, and re-evaluate at milestones."),
    ("Describe a time you turned down a shiny new technology because it wasn't the right fit for the business?", "Intermediate", "Resisted adopting a trendy NoSQL database when PostgreSQL with JSONB provided ACID compliance and zero operational complexity."),
    ("Tell me about a time you improved the reliability and signal-to-noise ratio of on-call alerts?", "Advanced", "Audit alert history, delete non-actionable alarms, route informational logs to dashboards instead of pagers, and enforce runbooks for every page."),
    ("How do you handle pressure and maintain team morale during critical crunch periods or major releases?", "Intermediate", "Protect team focus by filtering external distractions, ensuring sustainable pacing, ordering meals/accommodations, and celebrating wins."),
    ("Tell me about a time you had to deliver bad news to a key customer or executive stakeholder?", "Advanced", "Communicate early and transparently: state the problem clearly, explain what went wrong, provide a concrete resolution plan, and share ETA updates."),
    ("Describe how you prioritize competing engineering tasks when multiple P0 bugs occur simultaneously?", "Advanced", "Assess customer blast radius (revenue impact, security risk, percentage of users affected), triage resources, and communicate status openly."),
    ("Tell me about a time you championed accessibility (a11y) standards across a product engineering team?", "Intermediate", "Integrate automated axe-core audits into CI, conduct screen reader testing, and educate engineers on semantic HTML and WAI-ARIA roles."),
    ("Describe a situation where you had to refactor a critical system while teammates were actively adding features to it?", "Advanced", "Use Branch by Abstraction: introduce an abstraction interface in the codebase, build new implementation alongside, and switch consumers incrementally."),
    ("Tell me about a time you built consensus across multiple engineering teams with competing priorities?", "Advanced", "Find common business goals, host working group sessions, build cross-team alignment through transparent documentation, and establish shared KPIs."),
    ("How do you onboard a new senior engineer into your team to make them productive in their first two weeks?", "Intermediate", "Provide a dedicated onboarding buddy, a well-documented starter repo, a day-one commit to production, and scheduled 1-on-1 architecture walkthroughs."),
    ("Tell me about a time you identified a bottleneck in team velocity and successfully removed it?", "Intermediate", "Identified that PR reviews took 48 hours to be reviewed; instituted 4-hour PR review SLA and smaller PR size limits (<300 lines)."),
    ("Describe how you handle technical debt accumulated from rapid MVP prototyping?", "Intermediate", "Audit the technical debt post-launch, classify into stability, performance, and maintainability buckets, and allocate dedicated refactoring time."),
    ("Tell me about a time you successfully negotiated a compromise between Product, Security, and Engineering?", "Advanced", "Balanced security requirements (MFA) with user friction by proposing risk-based adaptive authentication that only challenges unrecognized devices."),
    ("How do you handle a situation where an engineer violates coding standards or skips automated tests?", "Intermediate", "Address it privately and constructively in 1-on-1: explain the risk to team velocity and system stability, and enforce automated branch protection rules in GitHub."),
    ("Tell me about a time you had to rewrite a system from scratch. How did you ensure it succeeded?", "Advanced", "Avoid the second-system effect: maintain strict parity tests against the old system, deploy via dark launch comparing outputs, and migrate users in small cohorts."),
    ("Describe a time you had to explain a complex distributed systems concept to non-technical business partners?", "Intermediate", "Use real-world analogies (e.g. comparing distributed consensus to voting in an election, or caches to keeping frequently used books on a desk)."),
    ("Tell me about a time you automated a tedious manual process that saved hundreds of hours for your team?", "Intermediate", "Built an automated release bot in Slack that tags releases, generates changelogs from PR labels, and deploys canaries with one command."),
    ("How do you decide when a piece of software is 'good enough' to ship versus continuing to optimize it?", "Intermediate", "Define measurable acceptance criteria and SLOs upfront. When the software meets latency, accuracy, and test coverage thresholds, ship it."),
    ("Tell me about a time you coached an engineer through a difficult production mistake that shook their confidence?", "Intermediate", "Remind them that outages are systemic failures, not individual faults; walk them through the blameless postmortem and have them lead the remediation fix."),
    ("Describe how you handle conflicting feature requests from multiple high-value enterprise clients?", "Advanced", "Abstract client-specific logic into extensible plugin architectures or configurable rule engines rather than hardcoding client-specific if/else branches."),
    ("Tell me about a time you identified an opportunity to improve software architecture that wasn't on the roadmap?", "Advanced", "Noticed repetitive boilerplate across 12 microservices; created an internal shared SDK that unified logging, tracing, and retry policies."),
    ("How do you maintain code quality and architectural integrity as an engineering team scales from 5 to 50 engineers?", "Advanced", "Document RFC architectural processes, establish clear code ownership via GitHub CODEOWNERS, build automated linting/testing in CI, and run guilds."),
    ("Tell me about a time you successfully managed up to an executive who didn't understand software engineering?", "Intermediate", "Translate technical concepts into revenue, risk, and time-to-market. Use dashboards and visual flowcharts instead of code discussions."),
    ("Describe a time you had to make a trade-off between consistency and availability in a distributed database system?", "Advanced", "During high traffic surges, chose eventual consistency over strong consistency for product views to keep the site available, while keeping payment strictly consistent."),
    ("Tell me about a time you conducted an interview and identified a red flag that saved the team from a bad hire?", "Intermediate", "Candidate demonstrated arrogance when questioned on design trade-offs and blamed junior teammates for previous project failures."),
    ("How do you handle burnout within your engineering team during prolonged high-stress projects?", "Intermediate", "Recognize early warning signs, redistribute workload, enforce mandatory PTO days, eliminate unnecessary meetings, and conduct post-project cooldown sprints."),
    ("Tell me about a time you championed unit testing and test-driven development on a team with zero test coverage?", "Intermediate", "Showed immediate value by writing tests that caught regression bugs in production releases; set minimum coverage gates on new PRs to prevent degradation."),
    ("Describe how you managed a critical security vulnerability patch that required restarting thousands of production servers?", "Advanced", "Orchestrated rolling restarts in Kubernetes using PodDisruptionBudgets, automated health probes, and staged regional rollouts during low-traffic windows."),
    ("Tell me about a time you had to deliver a keynote or technical presentation to an audience of hundreds of engineers?", "Intermediate", "Structured presentation with clear problem statements, live architecture demos, relatable failure anecdotes, and actionable takeaways."),
    ("How do you approach technical succession planning for yourself as an engineering leader?", "Advanced", "Document all leadership responsibilities, delegate critical system ownership, train senior peers to run incident rooms, and step back to observe."),
    ("Tell me about a time you resolved a deadlock or contention issue between two competing engineering roadmaps?", "Advanced", "Aligned both roadmaps under shared company objectives, created joint working milestones, and co-designed shared platform primitives."),
    ("Describe how you handle feedback from junior engineers who question established architectural patterns?", "Intermediate", "Welcome their questions openly; evaluating standard practices through fresh eyes often reveals outdated assumptions or legacy workarounds."),
    ("Tell me about a time you prevented customer churn by rapidly diagnosing and fixing an enterprise bug?", "Advanced", "Jumped on a live debugging session with enterprise client engineers, captured network traces, patched an edge-case serialization bug, and deployed a fix in 2 hours."),
    ("How do you design a disaster recovery (DR) drill to test your team's readiness for catastrophic datacenter loss?", "Advanced", "Design a simulated region blackout in AWS, verify automated DNS failover with Route 53, measure RPO/RTO metrics, and document bottlenecks."),
    ("Tell me about a time you improved the observability and telemetry of a black-box legacy system?", "Intermediate", "Injected OpenTelemetry auto-instrumentation agents into JVM/Node runtime without altering source code, unlocking distributed trace waterfalls."),
    ("Describe a situation where you had to balance engineering speed with strict regulatory compliance (SOC2, HIPAA, GDPR)?", "Advanced", "Automated compliance controls into CI/CD pipelines (immutable logs, encryption at rest, automated vulnerability scans) so compliance was achieved by default."),
    ("Tell me about a time you recognized a teammate's invisible glue work and advocated for their promotion?", "Intermediate", "Documented their critical contributions in mentoring, unblocking PRs, writing documentation, and onboarding new engineers in their performance review."),
    ("How do you handle a production incident when the primary subject matter expert is unreachable on vacation?", "Advanced", "Rely on documented runbooks, stable rollback mechanisms, and safe degradation modes; never depend on a single engineer's memory."),
    ("Tell me about a time you championed developer experience (DevEx) and reduced local development setup time?", "Intermediate", "Containerized local development with Docker Compose and devcontainers, reducing new hire environment setup from 3 days to 15 minutes."),
    ("Describe how you navigate building software when third-party API documentation is inaccurate or out of date?", "Intermediate", "Build isolated integration test suites against the third-party sandbox, log raw request/response payloads, and document discovered behavioral quirks."),
    ("Tell me about a time you had to choose between a quick temporary monkey-patch and a clean architectural fix?", "Intermediate", "If production is actively down, apply the temporary mitigation with an automated alert and immediately file a P0 ticket for the clean refactor next morning."),
    ("How do you ensure code written by your team adheres to clean code principles without micromanaging pull requests?", "Intermediate", "Establish agreed team style guides, automate mechanical checks with linters and static analyzers, and focus human review time on architectural intent."),
    ("Tell me about a time you resolved an intermittent, non-reproducible concurrency bug (Heisenbug) in production?", "Advanced", "Analyzed thread dumps and execution logs, identified a race condition in an un-synchronized static map, reproduced it with stress-testing scripts, and fixed it."),
    ("Describe how you foster psychological safety so teammates feel comfortable admitting mistakes and proposing bold ideas?", "Intermediate", "Share your own mistakes transparently, praise engineers for uncovering bugs early, and treat design discussions as collaborative problem-solving."),
    ("Tell me about a time you had to pivot technical architecture halfway through development due to business model changes?", "Advanced", "Decomposed work into reusable domain services so that pivoting business logic required rewriting business rules rather than the core data layer."),
    ("How do you ensure technical documentation stays updated and does not become stale over time?", "Intermediate", "Treat documentation as code: store markdown files in the repository alongside source code, enforce doc updates in PR checklists, and run link validators."),
    ("Tell me about a time you successfully negotiated SLA terms with an external enterprise vendor?", "Advanced", "Demanded strict financial penalties for SLA breaches, 15-minute response times for P0 severity, and dedicated Slack channels for engineering support."),
    ("Describe how you manage technical debt in third-party dependencies (end-of-life frameworks, outdated libraries)?", "Advanced", "Implement automated dependency update bots (Renovate/Dependabot), set monthly dependency update quotas, and test against deprecation warnings."),
    ("Tell me about a time you scaled a system to handle a 10x traffic surge during a major global event?", "Advanced", "Implemented multi-tier caching (CloudFront CDN + Redis), decoupled write paths with asynchronous Kafka queues, and tuned database connection pooling."),
    ("How do you establish engineering performance metrics without incentivizing bad behavior (e.g. lines of code or commit count)?", "Advanced", "Use DORA metrics (Deployment Frequency, Lead Time for Changes, Change Failure Rate, Time to Restore Service) which measure systemic health."),
    ("Tell me about a time you resolved an organizational silo that was impeding collaboration between Frontend and Backend teams?", "Intermediate", "Instituted contract-first development using OpenAPI/Protobuf specs, allowing frontend and backend to develop simultaneously against mock APIs."),
    ("Describe a situation where you had to make an emergency architectural rollback that prevented millions in revenue loss?", "Advanced", "Detected an error rate spike on a payment gateway release within 60 seconds; triggered automated rollback script, mitigating customer impact to 2 minutes."),
    ("Tell me about a time you mentored a non-technical colleague to understand technical feasibility and timelines?", "Intermediate", "Held regular coffee chats explaining system boundaries, user journeys, and how technical complexity directly influences project timelines."),
    ("How do you evaluate when a monolithic application should be split into microservices versus kept as a monolith?", "Advanced", "Only split when independent deployment velocity, organizational team boundaries, or distinct hardware scaling requirements justify the operational overhead."),
    ("Tell me about a time you created an internal open-source model within your company to share libraries across teams?", "Intermediate", "Created a centralized internal repository with clear contribution guidelines, automated test pipelines, and semantic versioning for shared UI components."),
    ("Describe how you handled a situation where a key project stakeholder was disengaged and unresponsive?", "Intermediate", "Scheduled a brief 15-minute in-person or video sync, presented concise options with recommended defaults, and established clear sign-off deadlines."),
    ("Tell me about a time you identified and resolved a memory leak that was causing daily container restarts in Kubernetes?", "Advanced", "Captured heap memory snapshots using pprof/jmap, analyzed object retention trees, identified an unclosed event listener map, and patched it."),
    ("How do you approach building software that must comply with international data residency requirements (GDPR, CCPA)?", "Advanced", "Architect multi-region database sharding where user PII is partitioned and stored strictly within their geographical jurisdiction."),
    ("Tell me about a time you championed automated end-to-end testing that eliminated manual QA release bottlenecks?", "Intermediate", "Implemented Playwright/Cypress test suites running on ephemeral staging environments, reducing manual QA regression cycles from 3 days to 20 minutes."),
    ("Describe how you maintain focus and deliver results when external organizational restructuring creates uncertainty?", "Intermediate", "Focus on controllable deliverables, maintain clear communication with teammates, and continue delivering business value on core roadmaps."),
    ("Tell me about a time you had to decline a feature request from a major executive because it violated security or privacy policies?", "Advanced", "Respectfully explained the compliance and data privacy implications, presented alternative approaches that fulfilled the user need safely, and stood firm on security."),
    ("How do you manage technical onboarding for contractors or external development agencies?", "Intermediate", "Provide scoped access via least privilege IAM, comprehensive architectural standards documents, and enforce mandatory PR reviews by internal staff."),
    ("Tell me about a time you led a postmortem that uncovered an uncomfortable cultural issue rather than a technical bug?", "Advanced", "Postmortem revealed engineers were afraid to speak up about known release risks due to aggressive deadlines; addressed this with leadership to reset expectations."),
    ("Describe how you prioritize performance optimizations: how do you know what to optimize first?", "Advanced", "Always profile before optimizing: use APM tools (Datadog/NewRelic) to locate the top 1% slowest endpoints and heaviest database queries affecting most users."),
    ("Tell me about a time you designed an automated canary release pipeline that caught a critical bug before full rollout?", "Advanced", "Configured Argo Rollouts with automated metric analysis: canary release sent to 5% of users exhibited an error rate spike, triggering automatic rollback."),
    ("How do you structure an engineering design document (RFC) to ensure productive stakeholder feedback?", "Intermediate", "Include Context, Goals/Non-Goals, Proposed Architecture, Alternative Solutions Considered, Security/Privacy Implications, and Rollout/Monitoring Strategy."),
    ("Tell me about a time you inherited a failing software project and successfully turned it around?", "Advanced", "Paired down non-essential scope, stabilized the CI/CD pipeline, established clear daily deliverables, and aligned engineering directly with business priorities."),
    ("Describe your strategy for staying technically sharp and continuously mastering emerging technologies throughout your career?", "Intermediate", "Build hands-on side projects, read foundational research papers (Google, AWS), contribute to open source, and dissect architecture retrospectives."),
    ("Tell me about a time you had to convince a team to adopt strict semantic versioning and changelog practices?", "Intermediate", "Demonstrated how broken downstream releases were caused by uncommunicated breaking changes; automated semantic release via commit messages.")
]

for title, diff, strat in behavioral_topics:
    behavioral_questions.append({
        'title': title,
        'difficulty': diff,
        'strategy': strat,
        'code': f"```markdown\nSTAR Interview Breakdown for: {title}\n- Situation: Context, enterprise constraints, and stakes.\n- Task: Core leadership responsibility and defined targets.\n- Action: Concrete steps taken, communication, and architectural decisions.\n- Result: Quantifiable business outcome, team velocity gain, or SLA improvement.\n```"
    })

# Format first 10 questions into dicts
formatted_behavioral = []
for item in behavioral_questions[:10]:
    if isinstance(item, tuple):
        formatted_behavioral.append({'title': item[0], 'difficulty': item[1], 'strategy': item[2], 'code': item[3]})
    else:
        formatted_behavioral.append(item)
formatted_behavioral.extend(behavioral_questions[10:])

write_category_file("behavioral", "behavioral-questions.md", "Behavioral & Engineering Leadership (STAR Method)", "Comprehensive interview questions covering STAR Method, Conflict Resolution, System Outages, and Leadership", "html-css-js-icon.svg", formatted_behavioral[:100])
print(f"Behavioral complete with {len(formatted_behavioral[:100])} distinct questions.")
